Repository OCA/product-attribute, pull requests merged in 2018-11, with the labels that each got.

#399 [12.0][MIG] product manufacturer
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_manufacturer.py
  product_manufacturer/static/description/icon.png
  product_manufacturer/views/product_manufacturer_view.xml
Labels: needs review

#409 [11.0][FIX] product_supplierinfo_for_customer: Hide variant suppliers in product template
  product_supplierinfo_for_customer/views/product_view.xml
Labels: approved, ready to merge

#406 [FIX] 10.0 product_profile : do not customize product easy form view
  product_profile/models/product.py
Labels: approved
