Repository OCA/product-attribute, pull requests merged in 2019-04, with the labels that each got.

#443 [FIX] product_supplierinfo_for_customer: Adapt views to variants handling
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/views/product_view.xml
Labels: approved

#444 [12.0][MIG] product_secondary_unit
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/views/product_views.xml
Labels: approved

#445 [11.0][IMP] product_secondary_unit: Add security group
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/migrations/11.0.1.0.2/post-migration.py
  product_secondary_unit/security/security.xml
  product_secondary_unit/views/product_views.xml
Labels: approved

#442 [12.0][MIG] product_supplierinfo_revision
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/readme/CONTRIBUTORS.rst
  product_supplierinfo_revision/readme/DESCRIPTION.rst
  product_supplierinfo_revision/readme/USAGE.rst
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
Labels: approved, ready to merge

#448 [MIG][12.0] product_template_tags
  product_template_tags/README.rst
  product_template_tags/__init__.py
  product_template_tags/__manifest__.py
  product_template_tags/i18n/de.po
  product_template_tags/i18n/es.po
  product_template_tags/i18n/fr.po
  product_template_tags/i18n/hr.po
  product_template_tags/i18n/it.po
  product_template_tags/i18n/nl_NL.po
  product_template_tags/i18n/product_template_tags.pot
  product_template_tags/i18n/sl.po
  product_template_tags/models/__init__.py
  product_template_tags/models/__pycache__/__init__.cpython-36.pyc
  product_template_tags/models/__pycache__/product_template.cpython-36.pyc
  product_template_tags/models/__pycache__/product_template_tag.cpython-36.pyc
  product_template_tags/models/product_template.py
  product_template_tags/models/product_template_tag.py
  product_template_tags/readme/CONFIGURE.rst
  product_template_tags/readme/CONTRIBUTORS.rst
  product_template_tags/readme/DESCRIPTION.rst
  product_template_tags/readme/USAGE.rst
  product_template_tags/security/product_template_rule.xml
  product_template_tags/security/product_template_tag.xml
  product_template_tags/static/description/icon.png
  product_template_tags/views/product_template.xml
  product_template_tags/views/product_template_tag.xml
Labels: needs review
