Repository OCA/product-attribute, pull requests merged in 2019-03, with the labels that each got.

#415 [12.0][MIG] Migrated product_multi_category to v12.
  product_multi_category/README.rst
  product_multi_category/__init__.py
  product_multi_category/__manifest__.py
  product_multi_category/i18n/ca.po
  product_multi_category/i18n/de.po
  product_multi_category/i18n/es.po
  product_multi_category/i18n/fr.po
  product_multi_category/i18n/fr_BE.po
  product_multi_category/i18n/hr.po
  product_multi_category/i18n/nl_NL.po
  product_multi_category/i18n/product_multi_category.pot
  product_multi_category/i18n/sv.po
  product_multi_category/i18n/tr.po
  product_multi_category/models/__init__.py
  product_multi_category/models/product.py
  product_multi_category/readme/CONTRIBUTORS.rst
  product_multi_category/readme/DESCRIPTION.rst
  product_multi_category/readme/USAGE.rst
  product_multi_category/static/description/icon.png
  product_multi_category/views/product_view.xml
Labels: approved, needs review, ready to merge

#407 [11.0][ADD] product_cost_security: New module to restrict product cost view
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/es.po
  product_cost_security/models/__init__.py
  product_cost_security/models/product.py
  product_cost_security/readme/CONFIGURE.rst
  product_cost_security/readme/CONTRIBUTORS.rst
  product_cost_security/readme/DESCRIPTION.rst
  product_cost_security/readme/USAGE.rst
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/views/product_views.xml
Labels: approved, needs review

#439 [ADD] 12.0 module product_base_mass_add
  base_product_mass_addition/README.rst
  base_product_mass_addition/__init__.py
  base_product_mass_addition/__manifest__.py
  base_product_mass_addition/models/__init__.py
  base_product_mass_addition/models/product_mass_addition.py
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
  base_product_mass_addition/readme/DESCRIPTION.rst
  base_product_mass_addition/readme/ROADMAP.rst
  base_product_mass_addition/static/description/filter.png
  base_product_mass_addition/static/description/index.html
  base_product_mass_addition/static/description/po-product.png
  base_product_mass_addition/static/description/po.png
  base_product_mass_addition/views/product_view.xml
Labels: approved

#440 [11.0][IMP] product_secondary_unit: Make secondary unit name translatable
  product_secondary_unit/models/product_second_unit.py
Labels: approved
