Repository OCA/product-attribute, pull requests merged in 2020-12, with the labels that each got.

#593 [12.0] Add product_packaging_dimension
  product_packaging_dimension/__init__.py
  product_packaging_dimension/__manifest__.py
  product_packaging_dimension/models/__init__.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/readme/CONTRIBUTORS.rst
  product_packaging_dimension/readme/DESCRIPTION.rst
  product_packaging_dimension/readme/ROADMAP.rst
  product_packaging_dimension/views/product_packaging.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#721 [14.0][MIG]product_cost_security
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/es.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product.py
  product_cost_security/readme/CONFIGURE.rst
  product_cost_security/readme/CONTRIBUTORS.rst
  product_cost_security/readme/DESCRIPTION.rst
  product_cost_security/readme/USAGE.rst
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/views/product_views.xml
  product_sequence/README.rst
  product_sequence/readme/CONTRIBUTORS.rst
  setup/product_cost_security/odoo/addons/product_cost_security
  setup/product_cost_security/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#733 [12.0][FIX] fix, an unactive variant should stay inactive
  product_variant_inactive/models/product_template.py
  product_variant_inactive/models/product_variant.py
  product_variant_inactive/tests/test_button.py
Labels: approved, bot is merging ⏳

#723 [14.0][MIG] product_multi_category
  product_multi_category/README.rst
  product_multi_category/__init__.py
  product_multi_category/__manifest__.py
  product_multi_category/i18n/ca.po
  product_multi_category/i18n/de.po
  product_multi_category/i18n/es.po
  product_multi_category/i18n/fr.po
  product_multi_category/i18n/fr_BE.po
  product_multi_category/i18n/hr.po
  product_multi_category/i18n/nl_NL.po
  product_multi_category/i18n/product_multi_category.pot
  product_multi_category/i18n/sv.po
  product_multi_category/i18n/tr.po
  product_multi_category/models/__init__.py
  product_multi_category/models/product.py
  product_multi_category/readme/CONTRIBUTORS.rst
  product_multi_category/readme/DESCRIPTION.rst
  product_multi_category/static/description/icon.png
  product_multi_category/static/description/index.html
  product_multi_category/views/product_view.xml
  setup/product_multi_category/odoo/addons/product_multi_category
  setup/product_multi_category/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#729 [12.0] [IMP+FIX] product_assortment: added partners + 2 bugs solved
  product_assortment/README.rst
  product_assortment/__manifest__.py
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/readme/CONTRIBUTORS.rst
  product_assortment/static/description/index.html
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#732 [ADD] product_order_noname: Speedup product retrieve
  product_order_noname/README.rst
  product_order_noname/__init__.py
  product_order_noname/__manifest__.py
  product_order_noname/models/__init__.py
  product_order_noname/models/product.py
  product_order_noname/readme/CONTRIBUTORS.rst
  product_order_noname/readme/CREDITS.rst
  product_order_noname/readme/DESCRIPTION.rst
  product_order_noname/readme/USAGE.rst
  product_order_noname/static/description/index.html
Labels: enhancement

#738 [13.0][ADD] product_order_noname: Speedup product retrieve
  product_order_noname/README.rst
  product_order_noname/__init__.py
  product_order_noname/__manifest__.py
  product_order_noname/models/__init__.py
  product_order_noname/models/product.py
  product_order_noname/readme/CONTRIBUTORS.rst
  product_order_noname/readme/CREDITS.rst
  product_order_noname/readme/DESCRIPTION.rst
  product_order_noname/readme/USAGE.rst
  product_order_noname/static/description/index.html
Labels: bot is merging ⏳

#743 [REF] product_order_noname: Change product.template order
  product_order_noname/models/__init__.py
  product_order_noname/models/product_template.py
Labels: approved, bot is merging ⏳, needs review

#744 [13.0][REF] product_order_noname: Change product.template order
  product_order_noname/models/__init__.py
  product_order_noname/models/product_template.py
Labels: bot is merging ⏳

#685 [FIX] product_assortment: fix domain widget in view
  product_assortment/views/product_assortment.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#719 [14.0][MIG] product_code_mandatory
  product_code_mandatory/README.rst
  product_code_mandatory/__init__.py
  product_code_mandatory/__manifest__.py
  product_code_mandatory/data/product_code_seq.xml
  product_code_mandatory/i18n/product_code_mandatory.pot
  product_code_mandatory/i18n/pt.po
  product_code_mandatory/models/__init__.py
  product_code_mandatory/models/product.py
  product_code_mandatory/readme/CONTRIBUTORS.rst
  product_code_mandatory/readme/DESCRIPTION.rst
  product_code_mandatory/readme/USAGE.rst
  product_code_mandatory/static/description/icon.png
  product_code_mandatory/static/description/index.html
  product_code_mandatory/tests/__init__.py
  product_code_mandatory/tests/test_product_code.py
  product_code_mandatory/views/product_view.xml
  setup/product_code_mandatory/odoo/addons/product_code_mandatory
  setup/product_code_mandatory/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#714 [13.0] [MIG] product_lot_sequence
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/stock_production_lot.py
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/DESCRIPTION.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  setup/product_lot_sequence/odoo/addons/product_lot_sequence
  setup/product_lot_sequence/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#674 [FIX] [12.0] product_dimension Contributors website
  product_dimension/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#675 [FIX] [13.0] product_dimension Contributors website
  product_dimension/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#672 [FIX] [12.0] product_bom_revision Contributors website
  product_bom_revision/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#673 [FIX] [13.0] product_bom_revision Contributors website
  product_bom_revision/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#643 [13.0][IMP] product_packaging_unit_price_calculator
  product_packaging_unit_price_calculator/models/product.py
  product_packaging_unit_price_calculator/models/product_packaging.py
  product_packaging_unit_price_calculator/tests/test_product_price_packaging_qty.py
  product_packaging_unit_price_calculator/wizards/product_package_price.py
  product_packaging_unit_price_calculator/wizards/product_package_price.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#742 [14.0][MIG] product_pricelist_direct_print: Migration to 14.0
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/data/mail_template_data.xml
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONFIGURE.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/readme/DESCRIPTION.rst
  product_pricelist_direct_print/readme/USAGE.rst
  product_pricelist_direct_print/security/ir.model.access.csv
  product_pricelist_direct_print/static/description/icon.png
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/tests/__init__.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/__init__.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print/odoo/addons/product_pricelist_direct_print
  setup/product_pricelist_direct_print/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#655 [13.0][FIX] product_assortment : avoid errors when trying to open assortment products
  product_assortment/models/ir_filters.py
  product_assortment/views/product_assortment.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#726 [13.0] Add product_uom_updatable
  product_uom_updatable/README.rst
  product_uom_updatable/__init__.py
  product_uom_updatable/__manifest__.py
  product_uom_updatable/models/__init__.py
  product_uom_updatable/models/product_template.py
  product_uom_updatable/readme/CONTRIBUTORS.rst
  product_uom_updatable/readme/DESCRIPTION.rst
  product_uom_updatable/static/description/index.html
  product_uom_updatable/tests/__init__.py
  product_uom_updatable/tests/test_product_uom_update.py
  setup/product_uom_updatable/odoo/addons/product_uom_updatable
  setup/product_uom_updatable/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#706 product_barcode_required: fix required on template form
  product_barcode_required/models/product_barcode_mixin.py
  product_barcode_required/models/product_template.py
  product_barcode_required/tests/test_barcode.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#751 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  .travis.yml
Labels: bot is merging ⏳, help wanted, needs review

#753 [8.0][IMP] Travis: Update to latest template
  .travis.yml
  product_m2mcategories/__openerp__.py
  product_sale_tax_price_included/i18n/fr.po
Labels: bot is merging ⏳

#127 8.0 Add module product_categ_image
  product_categ_image/README.rst
  product_categ_image/__init__.py
  product_categ_image/__openerp__.py
  product_categ_image/models/__init__.py
  product_categ_image/models/product_category.py
  product_categ_image/views/product_view.xml
Labels: bot is merging ⏳

#309 [ADD] product_uom_technology: Module for techno units
  product_uom_technology/README.rst
  product_uom_technology/__init__.py
  product_uom_technology/__manifest__.py
  product_uom_technology/data/product_uom_categ_data.xml
  product_uom_technology/data/product_uom_data.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge
