Repository OCA/product-attribute, pull requests merged in 2020-03, with the labels that each got.

#582 [FIX] Remove isort seed
  .isort.cfg
  .pre-commit-config.yaml
Labels: approved

#583 [FIX] product_bom_revision Readme duplicate bug tracker
  product_bom_revision/README.rst
Labels: approved

#591 [IMP] product_secondary_unit: Remove product secondary units if a product is deleted
  product_secondary_unit/models/product_second_unit.py
Labels: approved, enhancement, needs review

#541 [13.0][MIG] product_multi_category
  product_multi_category/README.rst
  product_multi_category/__init__.py
  product_multi_category/__manifest__.py
  product_multi_category/i18n/ca.po
  product_multi_category/i18n/de.po
  product_multi_category/i18n/es.po
  product_multi_category/i18n/fr.po
  product_multi_category/i18n/fr_BE.po
  product_multi_category/i18n/hr.po
  product_multi_category/i18n/nl_NL.po
  product_multi_category/i18n/product_multi_category.pot
  product_multi_category/i18n/sv.po
  product_multi_category/i18n/tr.po
  product_multi_category/models/__init__.py
  product_multi_category/models/product.py
  product_multi_category/readme/CONTRIBUTORS.rst
  product_multi_category/readme/DESCRIPTION.rst
  product_multi_category/static/description/icon.png
  product_multi_category/static/description/index.html
  product_multi_category/views/product_view.xml
Labels: approved, ready to merge

#536 [13.0] Migrate product_packaging_type to 13.0
  product_packaging_type/__init__.py
  product_packaging_type/__manifest__.py
  product_packaging_type/data/product_packaging_type.xml
  product_packaging_type/models/__init__.py
  product_packaging_type/models/product_packaging_type.py
  product_packaging_type/readme/CONTRIBUTORS.rst
  product_packaging_type/readme/DESCRIPTION.rst
  product_packaging_type/readme/USAGE.rst
  product_packaging_type/security/ir.model.access.csv
  product_packaging_type/views/product_packaging_type_view.xml
  product_packaging_type/views/product_packaging_view.xml
  product_packaging_type_required/__init__.py
  product_packaging_type_required/__manifest__.py
  product_packaging_type_required/data/cron.xml
  product_packaging_type_required/models/__init__.py
  product_packaging_type_required/models/product_packaging_type.py
  product_packaging_type_required/readme/CONTRIBUTORS.rst
  product_packaging_type_required/readme/DESCRIPTION.rst
  product_packaging_type_required/readme/USAGE.rst
  product_packaging_type_required/views/product_packaging_type_view.xml
  setup/product_packaging_type/odoo/addons/product_packaging_type
  setup/product_packaging_type/setup.py
  setup/product_packaging_type_required/odoo/addons/product_packaging_type_required
  setup/product_packaging_type_required/setup.py
Labels: approved, ready to merge

#552 [13.0][MIG] product_packaging_type_pallet
  product_packaging_type_pallet/__init__.py
  product_packaging_type_pallet/__manifest__.py
  product_packaging_type_pallet/models/__init__.py
  product_packaging_type_pallet/models/product_packaging.py
  product_packaging_type_pallet/readme/CONTRIBUTORS.rst
  product_packaging_type_pallet/readme/DESCRIPTION.rst
  product_packaging_type_pallet/views/product_packaging.xml
  product_packaging_type_pallet/views/product_packaging_type.xml
  setup/product_packaging_type_pallet/odoo/addons/product_packaging_type_pallet
  setup/product_packaging_type_pallet/setup.py
Labels: approved, ready to merge

#575 [12.0][ADD] product_stock_state
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/data/data.xml
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/res_config_settings.py
  product_stock_state/readme/CONFIGURE.rst
  product_stock_state/readme/CONTRIBUTORS.rst
  product_stock_state/readme/CREDITS.rst
  product_stock_state/readme/DESCRIPTION.rst
  product_stock_state/readme/USAGE.rst
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/index.html
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/res_company_view.xml
  product_stock_state/views/res_config_settings_view.xml
Labels: needs review
