Repository OCA/product-attribute, pull requests merged in 2020-09, with the labels that each got.

#679 [FIX] product_pricelist_direct_print: archived ordered products
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: approved, bot is merging ⏳

#663 [IMP] add sale_price basond on sale_margin to supplierinfo
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/DESCRIPTION.rst
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
Labels: approved, bot is merging ⏳, needs review

#686 [IMP] product_template_tags: speed up tag.products_count compute
  product_template_tags/models/product_template_tag.py
Labels: approved, bot is merging ⏳, enhancement
