Repository OCA/product-attribute, pull requests merged in 2020-10, with the labels that each got.

#691 [13.0][UPD] Eficent -> ForgeFlow
  product_manufacturer/readme/CONTRIBUTORS.rst
  product_sequence/__manifest__.py
  product_sequence/models/product_category.py
  product_sequence/models/product_product.py
  product_sequence/readme/CONTRIBUTORS.rst
  product_sequence/views/product_category.xml
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_view.xml
Labels: bot is merging ⏳

#667 [FIX] product_pricelist_supplierinfo: variant domain
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: bot is merging ⏳

#683 [12.0][FIX] product_pricelist_supplierinfo: Converting Price
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: approved, bot is merging ⏳, ready to merge

#690 [IMP] product_template_tags: speed up tag.products_count compute
  product_template_tags/models/product_template_tag.py
Labels: bot is merging ⏳

#682 [12.0][ADD] product_pricelist_show_product_ref
  product_pricelist_show_product_ref/README.rst
  product_pricelist_show_product_ref/__init__.py
  product_pricelist_show_product_ref/__manifest__.py
  product_pricelist_show_product_ref/models/__init__.py
  product_pricelist_show_product_ref/models/product_pricelist.py
  product_pricelist_show_product_ref/readme/CONFIGURE.rst
  product_pricelist_show_product_ref/readme/CONTRIBUTORS.rst
  product_pricelist_show_product_ref/readme/DESCRIPTION.rst
  product_pricelist_show_product_ref/readme/USAGE.rst
  product_pricelist_show_product_ref/static/description/index.html
  product_pricelist_show_product_ref/tests/__init__.py
  product_pricelist_show_product_ref/tests/test_product_pricelist_show_product_ref.py
Labels: approved, bot is merging ⏳, ready to merge

#694 [12.0] IMP product_pricelist_supplierinfo allowing to filter suppliers to get prices from
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.rst
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
Labels: bot is merging ⏳

#692 [MIG] product_custom_info
  oca_dependencies.txt
  product_custom_info/README.rst
  product_custom_info/__init__.py
  product_custom_info/__manifest__.py
  product_custom_info/i18n/es.po
  product_custom_info/i18n/product_custom_info.pot
  product_custom_info/models/__init__.py
  product_custom_info/models/product_product.py
  product_custom_info/models/product_template.py
  product_custom_info/static/description/icon.png
  product_custom_info/views/product_product_view.xml
  product_custom_info/views/product_template_view.xml
Labels: bot is merging ⏳

#700 [13.0][MIG] product_multi_price
  product_multi_price/README.rst
  product_multi_price/__init__.py
  product_multi_price/__manifest__.py
  product_multi_price/demo/multi_price_demo_data.xml
  product_multi_price/hooks.py
  product_multi_price/i18n/es.po
  product_multi_price/i18n/it.po
  product_multi_price/i18n/product_multi_price.pot
  product_multi_price/migrations/13.0.1.0.0/noupdate_changes.xml
  product_multi_price/migrations/13.0.1.0.0/post-migration.py
  product_multi_price/models/__init__.py
  product_multi_price/models/product_multi_price.py
  product_multi_price/models/product_pricelist.py
  product_multi_price/models/product_product.py
  product_multi_price/models/product_template.py
  product_multi_price/readme/CONFIGURE.rst
  product_multi_price/readme/CONTRIBUTORS.rst
  product_multi_price/readme/DESCRIPTION.rst
  product_multi_price/readme/ROADMAP.rst
  product_multi_price/readme/USAGE.rst
  product_multi_price/security/ir.model.access.csv
  product_multi_price/security/multi_price_security.xml
  product_multi_price/static/description/icon.png
  product_multi_price/static/description/index.html
  product_multi_price/tests/__init__.py
  product_multi_price/tests/test_product_multi_price.py
  product_multi_price/views/multi_price_views.xml
  product_multi_price/views/product_pricelist_views.xml
  product_multi_price/views/product_views.xml
  setup/product_multi_price/odoo/addons/product_multi_price
  setup/product_multi_price/setup.py
Labels: approved, bot is merging ⏳

#699 [14.0] [MIG] product_dimension
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product.py
  product_dimension/readme/CONTRIBUTORS.rst
  product_dimension/readme/DESCRIPTION.rst
  product_dimension/readme/HISTORY.rst
  product_dimension/readme/USAGE.rst
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/views/product_view.xml
  setup/product_dimension/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#701 [12.0][IMP] product_pricelist_show_product_ref: display product code in pricelists for templates
  product_pricelist_show_product_ref/README.rst
  product_pricelist_show_product_ref/__manifest__.py
  product_pricelist_show_product_ref/models/product_pricelist.py
  product_pricelist_show_product_ref/readme/USAGE.rst
  product_pricelist_show_product_ref/static/description/index.html
  product_pricelist_show_product_ref/tests/test_product_pricelist_show_product_ref.py
Labels: approved, bot is merging ⏳

#677 [13.0] Add product_barcode_required
  product_barcode_required/README.rst
  product_barcode_required/__init__.py
  product_barcode_required/__manifest__.py
  product_barcode_required/models/__init__.py
  product_barcode_required/models/product_barcode_mixin.py
  product_barcode_required/models/product_product.py
  product_barcode_required/models/product_template.py
  product_barcode_required/models/res_company.py
  product_barcode_required/models/res_config_settings.py
  product_barcode_required/readme/CONFIGURE.rst
  product_barcode_required/readme/CONTRIBUTORS.rst
  product_barcode_required/readme/DESCRIPTION.rst
  product_barcode_required/static/description/index.html
  product_barcode_required/tests/__init__.py
  product_barcode_required/tests/test_barcode.py
  product_barcode_required/views/product_template_view.xml
  product_barcode_required/views/product_view.xml
  product_barcode_required/views/res_config_settings.xml
  setup/product_barcode_required/odoo/addons/product_barcode_required
  setup/product_barcode_required/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
