Repository OCA/product-attribute, pull requests merged in 2020-05, with the labels that each got.

#608 [12.0][ADD] product_category_active: new module
  product_category_active/README.rst
  product_category_active/__init__.py
  product_category_active/__manifest__.py
  product_category_active/i18n/es.po
  product_category_active/i18n/product_category_archive.pot
  product_category_active/models/__init__.py
  product_category_active/models/product.py
  product_category_active/readme/CONTRIBUTORS.rst
  product_category_active/readme/DESCRIPTION.rst
  product_category_active/readme/ROADMAP.rst
  product_category_active/readme/USAGE.rst
  product_category_active/static/description/index.html
  product_category_active/tests/__init__.py
  product_category_active/tests/test_product_category_archive.py
  product_category_active/views/product_views.xml
Labels: approved, bot is merging ⏳

#615 [12.0][IMP] product_category_archive: add a test
  product_category_active/tests/test_product_category_archive.py
Labels: approved, bot is merging ⏳

#597 [13.0][MIG] product_dimension
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product.py
  product_dimension/readme/CONTRIBUTORS.rst
  product_dimension/readme/DESCRIPTION.rst
  product_dimension/readme/HISTORY.rst
  product_dimension/readme/USAGE.rst
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/views/product_view.xml
  setup/product_dimension/odoo/addons/product_dimension
  setup/product_dimension/setup.py
Labels: approved, bot is merging ⏳, needs review

#495 [12.0][MIG] product_standard_price_tax_included
  product_standard_price_tax_included/README.rst
  product_standard_price_tax_included/__init__.py
  product_standard_price_tax_included/__manifest__.py
  product_standard_price_tax_included/demo/account_tax.xml
  product_standard_price_tax_included/demo/product_pricelist.xml
  product_standard_price_tax_included/demo/product_product.xml
  product_standard_price_tax_included/demo/res_groups.xml
  product_standard_price_tax_included/i18n/de.po
  product_standard_price_tax_included/i18n/es.po
  product_standard_price_tax_included/i18n/fr.po
  product_standard_price_tax_included/i18n/product_standard_price_tax_included.pot
  product_standard_price_tax_included/i18n/sl.po
  product_standard_price_tax_included/models/__init__.py
  product_standard_price_tax_included/models/account_tax.py
  product_standard_price_tax_included/models/product_pricelist.py
  product_standard_price_tax_included/models/product_pricelist_item.py
  product_standard_price_tax_included/models/product_product.py
  product_standard_price_tax_included/readme/CONTRIBUTORS.rst
  product_standard_price_tax_included/readme/DESCRIPTION.rst
  product_standard_price_tax_included/readme/USAGE.rst
  product_standard_price_tax_included/static/description/icon.png
  product_standard_price_tax_included/static/description/index.html
  product_standard_price_tax_included/static/description/product_pricelist_item_form.png
  product_standard_price_tax_included/static/description/product_product_form.png
  product_standard_price_tax_included/static/description/sale_order_form.png
  product_standard_price_tax_included/static/description/sale_order_form_without_module.png
  product_standard_price_tax_included/tests/__init__.py
  product_standard_price_tax_included/tests/test_module.py
  product_standard_price_tax_included/views/view_product_product.xml
Labels: merged 🎉
