Repository OCA/product-attribute, pull requests merged in 2020-02, with the labels that each got.

#567 [FIX] product_supplierinfo_for_customer: Get incorrect customerinfo for customer product price evaluation
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
Labels: approved

#572 [FIX] product_pricelist_direct_print: Fix bootstrap v4 elements
  product_pricelist_direct_print/views/report_product_pricelist.xml
Labels: approved

#413 [12.0][MIG] Migrated product_code_mandatory to v12
  product_code_mandatory/README.rst
  product_code_mandatory/__init__.py
  product_code_mandatory/__manifest__.py
  product_code_mandatory/data/product_code_seq.xml
  product_code_mandatory/i18n/product_code_mandatory.pot
  product_code_mandatory/models/__init__.py
  product_code_mandatory/models/product.py
  product_code_mandatory/readme/CONTRIBUTORS.rst
  product_code_mandatory/readme/DESCRIPTION.rst
  product_code_mandatory/readme/USAGE.rst
  product_code_mandatory/static/description/icon.png
  product_code_mandatory/tests/__init__.py
  product_code_mandatory/tests/test_product_code.py
  product_code_mandatory/views/product_view.xml
Labels: approved, merged 🎉, needs review, ready to merge

#568 Fix position of field product_tag_ids
  product_template_tags/views/product_template.xml
Labels: approved, ready to merge

#571 [13.0][MIG] packaging_uom
  packaging_uom/README.rst
  packaging_uom/__init__.py
  packaging_uom/__manifest__.py
  packaging_uom/i18n/cs_CZ.po
  packaging_uom/i18n/de.po
  packaging_uom/i18n/es.po
  packaging_uom/i18n/fi.po
  packaging_uom/i18n/fr.po
  packaging_uom/i18n/hr.po
  packaging_uom/i18n/hr_HR.po
  packaging_uom/i18n/it.po
  packaging_uom/i18n/nl.po
  packaging_uom/i18n/packaging_uom.pot
  packaging_uom/i18n/pt.po
  packaging_uom/i18n/pt_BR.po
  packaging_uom/i18n/sl.po
  packaging_uom/models/__init__.py
  packaging_uom/models/product_packaging.py
  packaging_uom/readme/CONFIGURE.rst
  packaging_uom/readme/CONTRIBUTORS.rst
  packaging_uom/readme/DESCRIPTION.rst
  packaging_uom/readme/HISTORY.rst
  packaging_uom/readme/USAGE.rst
  packaging_uom/static/description/icon.png
  packaging_uom/static/description/index.html
  packaging_uom/tests/__init__.py
  packaging_uom/tests/test_product_packaging.py
  packaging_uom/views/product_packaging_views.xml
Labels: approved, ready to merge

#581 [12.0][IMP] product_pricelist_direct_print: Hide pricelist name option
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved

#570 [ADD] product_bom_revision
  product_bom_revision/README.rst
  product_bom_revision/__init__.py
  product_bom_revision/__manifest__.py
  product_bom_revision/models/__init__.py
  product_bom_revision/models/mrp.py
  product_bom_revision/models/product.py
  product_bom_revision/readme/CONTRIBUTORS.rst
  product_bom_revision/readme/DESCRIPTION.rst
  product_bom_revision/readme/USAGE.rst
  product_bom_revision/static/description/icon.png
  product_bom_revision/static/description/index.html
  product_bom_revision/views/mrp_view.xml
  product_bom_revision/views/product_view.xml
Labels: approved, ready to merge
