Repository OCA/product-attribute, pull requests merged in 2020-11, with the labels that each got.

#710 [IMP] product_brand: faster BI
  product_brand/models/product_brand.py
  product_brand/reports/sale_report.py
Labels: bot is merging ⏳

#681 [13.0][IMP] product_manufacturer: Manage Manufacture Info for Variants
  product_manufacturer/migrations/13.0.2.0.0/post-migration.py
  product_manufacturer/models/product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#709 [UPD] Brainbean Apps => CorporateHub
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#712 [UPD] Brainbean Apps => CorporateHub
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#717 [14.0][MIG] migration of module product_secondary_unit
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/es_MX.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/views/product_views.xml
  setup/product_secondary_unit/odoo/addons/product_secondary_unit
  setup/product_secondary_unit/setup.py
Labels: approved, bot is merging ⏳

#722 [13.0][MIG] product_supplierinfo_revision: Migration to 13.0
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/readme/CONTRIBUTORS.rst
  product_supplierinfo_revision/readme/DESCRIPTION.rst
  product_supplierinfo_revision/readme/USAGE.rst
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
  setup/product_supplierinfo_revision/odoo/addons/product_supplierinfo_revision
  setup/product_supplierinfo_revision/setup.py
Labels: approved, bot is merging ⏳

#713 [14.0][MIG] product_code_unique
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/readme/CONTRIBUTORS.rst
  product_code_unique/readme/DESCRIPTION.rst
  product_code_unique/readme/USAGE.rst
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
  setup/product_code_unique/odoo/addons/product_code_unique
  setup/product_code_unique/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#704 [14.0][MIG] product_bom_revision
  product_bom_revision/README.rst
  product_bom_revision/__init__.py
  product_bom_revision/__manifest__.py
  product_bom_revision/i18n/product_bom_revision.pot
  product_bom_revision/models/__init__.py
  product_bom_revision/models/mrp.py
  product_bom_revision/models/product.py
  product_bom_revision/readme/CONTRIBUTORS.rst
  product_bom_revision/readme/DESCRIPTION.rst
  product_bom_revision/readme/USAGE.rst
  product_bom_revision/static/description/icon.png
  product_bom_revision/static/description/index.html
  product_bom_revision/views/mrp_view.xml
  product_bom_revision/views/product_view.xml
  setup/product_bom_revision/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge
