Repository OCA/product-attribute, pull requests merged in 2020-06, with the labels that each got.

#562 [MIG][13.0] product_pricelist_direct_print: Migration to v13.0
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/data/mail_template_data.xml
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONFIGURE.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/readme/DESCRIPTION.rst
  product_pricelist_direct_print/readme/USAGE.rst
  product_pricelist_direct_print/static/description/icon.png
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/tests/__init__.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/__init__.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print/odoo/addons/product_pricelist_direct_print
  setup/product_pricelist_direct_print/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#624 [IMP] product_cost_security: Add user_root to security group
  product_cost_security/security/product_cost_security.xml
Labels: approved, bot is merging ⏳

#576 [10.0][BACKPORT] product_secondary_unit
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/views/product_views.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#617 [13.0] [MIG] product_bom_revision
  product_bom_revision/README.rst
  product_bom_revision/__init__.py
  product_bom_revision/__manifest__.py
  product_bom_revision/i18n/product_bom_revision.pot
  product_bom_revision/models/__init__.py
  product_bom_revision/models/mrp.py
  product_bom_revision/models/product.py
  product_bom_revision/readme/CONTRIBUTORS.rst
  product_bom_revision/readme/DESCRIPTION.rst
  product_bom_revision/readme/USAGE.rst
  product_bom_revision/static/description/icon.png
  product_bom_revision/static/description/index.html
  product_bom_revision/views/mrp_view.xml
  product_bom_revision/views/product_view.xml
  setup/product_bom_revision/odoo/addons/product_bom_revision
  setup/product_bom_revision/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#384 Fix tab name in product form
  product_supplierinfo_revision/README.rst
Labels: approved, bot is merging ⏳, ready to merge

#474 [10.0] [NEW] Add module product_code_remove.
  product_code_remove/README.rst
  product_code_remove/__init__.py
  product_code_remove/__manifest__.py
  product_code_remove/models/__init__.py
  product_code_remove/models/product_product.py
  product_code_remove/static/description/icon.png
  product_code_remove/tests/__init__.py
  product_code_remove/tests/test_product_code.py
Labels: approved, bot is merging ⏳, ready to merge

#618 [MIG] product_weight: Migration to 13.0
  product_weight/README.rst
  product_weight/__init__.py
  product_weight/__manifest__.py
  product_weight/i18n/ca.po
  product_weight/i18n/de.po
  product_weight/i18n/es.po
  product_weight/i18n/fr.po
  product_weight/i18n/hr.po
  product_weight/i18n/it.po
  product_weight/i18n/nl_NL.po
  product_weight/i18n/product_weight.pot
  product_weight/i18n/sl.po
  product_weight/models/__init__.py
  product_weight/readme/CONTRIBUTORS.rst
  product_weight/readme/DESCRIPTION.rst
  product_weight/readme/USAGE.rst
  product_weight/static/description/icon.png
  product_weight/static/description/index.html
  product_weight/tests/__init__.py
  product_weight/tests/test_compute_bom_weight.py
  product_weight/views/product_view.xml
  product_weight/wizard/__init__.py
  product_weight/wizard/product_weight_update.py
  product_weight/wizard/product_weight_update_view.xml
  setup/product_weight/odoo/addons/product_weight
  setup/product_weight/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#636 [9.0][FIX] .travis: Update to latest template
  .travis.yml
Labels: bot is merging ⏳

#634 [13.0][MIG] product_state to v13 + improvements
  product_state/README.rst
  product_state/__init__.py
  product_state/__manifest__.py
  product_state/data/product_state_data.xml
  product_state/i18n/de.po
  product_state/i18n/es.po
  product_state/i18n/fr.po
  product_state/i18n/hr.po
  product_state/i18n/nl_NL.po
  product_state/i18n/product_state.pot
  product_state/i18n/pt.po
  product_state/i18n/sl.po
  product_state/migrations/13.0.1.0.0/post-migration.py
  product_state/models/__init__.py
  product_state/models/product_state.py
  product_state/models/product_template.py
  product_state/readme/CONTRIBUTORS.rst
  product_state/readme/DESCRIPTION.rst
  product_state/readme/USAGE.rst
  product_state/security/ir.model.access.csv
  product_state/static/description/icon.png
  product_state/static/description/index.html
  product_state/views/product_template.xml
  setup/product_state/.eggs/README.txt
  setup/product_state/odoo/addons/product_state
  setup/product_state/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#561 [13.0][NEW] stock_account_product_cost_security: New module to hide cost elements according to product cost security
  setup/stock_account_product_cost_security/odoo/addons/stock_account_product_cost_security
  setup/stock_account_product_cost_security/setup.py
  stock_account_product_cost_security/README.rst
  stock_account_product_cost_security/__init__.py
  stock_account_product_cost_security/__manifest__.py
  stock_account_product_cost_security/readme/CONTRIBUTORS.rst
  stock_account_product_cost_security/readme/DESCRIPTION.rst
  stock_account_product_cost_security/static/description/icon.png
  stock_account_product_cost_security/static/description/index.html
  stock_account_product_cost_security/views/product_views.xml
  stock_account_product_cost_security/wizard/stock_change_standard_price_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#641 [13.0] packaging_uom: Fix xmlid of product packaging tree view
  packaging_uom/views/product_packaging_views.xml
Labels: approved, bot is merging ⏳, enhancement

#640 [13.0][ADD] product_packaging_unit_price_calculator
  product_packaging_unit_price_calculator/__init__.py
  product_packaging_unit_price_calculator/__manifest__.py
  product_packaging_unit_price_calculator/models/__init__.py
  product_packaging_unit_price_calculator/models/product.py
  product_packaging_unit_price_calculator/models/product_packaging.py
  product_packaging_unit_price_calculator/models/product_pricelist.py
  product_packaging_unit_price_calculator/models/product_supplierinfo.py
  product_packaging_unit_price_calculator/readme/CONTRIBUTORS.rst
  product_packaging_unit_price_calculator/readme/DESCRIPTION.rst
  product_packaging_unit_price_calculator/readme/USAGE.rst
  product_packaging_unit_price_calculator/tests/__init__.py
  product_packaging_unit_price_calculator/tests/test_product_price_packaging_qty.py
  product_packaging_unit_price_calculator/views/product_packaging.xml
  product_packaging_unit_price_calculator/views/product_pricelist.xml
  product_packaging_unit_price_calculator/views/product_supplierinfo.xml
  product_packaging_unit_price_calculator/views/product_view.xml
  product_packaging_unit_price_calculator/wizards/__init__.py
  product_packaging_unit_price_calculator/wizards/product_package_price.py
  product_packaging_unit_price_calculator/wizards/product_package_price.xml
Labels: bot is merging ⏳, needs review
