Repository OCA/product-attribute, pull requests merged in 2021-04, with the labels that each got.

#843 [13.0][IMP] product_secondary_unit: Add a tree view for secondary UoM
  product_secondary_unit/README.rst
  product_secondary_unit/__manifest__.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/static/description/index.html
  product_secondary_unit/views/product_secondary_unit_views.xml
  product_secondary_unit/views/product_views.xml
Labels: approved, bot is merging ⏳

#684 [12.0][FIX] mixed check on id and record
  product_state/models/product_template.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#760 [MIG] product_packaging_type: Migration to 14.0
  product_packaging_type/README.rst
  product_packaging_type/__init__.py
  product_packaging_type/__manifest__.py
  product_packaging_type/data/product_packaging_type.xml
  product_packaging_type/i18n/es.po
  product_packaging_type/i18n/product_packaging_type.pot
  product_packaging_type/models/__init__.py
  product_packaging_type/models/product_packaging_type.py
  product_packaging_type/readme/CONTRIBUTORS.rst
  product_packaging_type/readme/CREDITS.rst
  product_packaging_type/readme/DESCRIPTION.rst
  product_packaging_type/readme/USAGE.rst
  product_packaging_type/security/ir.model.access.csv
  product_packaging_type/static/description/icon.png
  product_packaging_type/static/description/index.html
  product_packaging_type/views/product_packaging_type_view.xml
  product_packaging_type/views/product_packaging_view.xml
  setup/product_packaging_type/odoo/addons/product_packaging_type
  setup/product_packaging_type/setup.py
Labels: approved, bot is merging ⏳

#842 [12.0][IMP] product_pricelist_revision: Allow create pricelist item
  product_pricelist_revision/views/pricelist_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#715 [14.0][MIG] product_stock_state
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/data/data.xml
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/res_config_settings.py
  product_stock_state/readme/CONFIGURE.rst
  product_stock_state/readme/CONTRIBUTORS.rst
  product_stock_state/readme/CREDITS.rst
  product_stock_state/readme/DESCRIPTION.rst
  product_stock_state/readme/USAGE.rst
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/icon.png
  product_stock_state/static/description/index.html
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/res_company_view.xml
  product_stock_state/views/res_config_settings_view.xml
  setup/product_stock_state/odoo/addons/product_stock_state
  setup/product_stock_state/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#764 [14.0][MIG] product_logistics_uom
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/readme/CONFIGURE.rst
  product_logistics_uom/readme/CONTRIBUTORS.rst
  product_logistics_uom/readme/CREDITS.rst
  product_logistics_uom/readme/DESCRIPTION.rst
  product_logistics_uom/readme/INSTALL.rst
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
  setup/product_logistics_uom/odoo/addons/product_logistics_uom
  setup/product_logistics_uom/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#828 [13.0] [MIG] product_pricelist_supplierinfo: MIgration to v13.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/CONFIGURE.rst
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.rst
  product_pricelist_supplierinfo/readme/DESCRIPTION.rst
  product_pricelist_supplierinfo/readme/INSTALL.rst
  product_pricelist_supplierinfo/readme/ROADMAP.rst
  product_pricelist_supplierinfo/readme/USAGE.rst
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
  setup/product_pricelist_supplierinfo/odoo/addons/product_pricelist_supplierinfo
  setup/product_pricelist_supplierinfo/setup.py
Labels: approved, bot is merging ⏳, ready to merge
