Repository OCA/product-attribute, pull requests merged in 2021-05, with the labels that each got.

#774 [13.0][CHG] product_pricelist_assortment: improve computation performance
  product_pricelist_assortment/models/product_pricelist_assortment_item.py
  product_pricelist_assortment/tests/test_pricelist_assortment.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#550 12.0 mig product sale tax price included
  product_sale_tax_price_included/README.rst
  product_sale_tax_price_included/__init__.py
  product_sale_tax_price_included/__manifest__.py
  product_sale_tax_price_included/demo/account_tax.xml
  product_sale_tax_price_included/demo/product_template.xml
  product_sale_tax_price_included/i18n/fr.po
  product_sale_tax_price_included/models/__init__.py
  product_sale_tax_price_included/models/product_template.py
  product_sale_tax_price_included/readme/CONTRIBUTORS.rst
  product_sale_tax_price_included/readme/DESCRIPTION.rst
  product_sale_tax_price_included/static/description/icon.png
  product_sale_tax_price_included/static/description/index.html
  product_sale_tax_price_included/static/description/product_not_tax.png
  product_sale_tax_price_included/static/description/product_tax_excluded.png
  product_sale_tax_price_included/static/description/product_tax_included.png
  product_sale_tax_price_included/static/description/product_tax_included_and_not.png
  product_sale_tax_price_included/static/description/taxes_creation.png
  product_sale_tax_price_included/tests/__init__.py
  product_sale_tax_price_included/tests/test_module.py
  product_sale_tax_price_included/views/product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#725 [14.0][MIG]product_state
  product_state/README.rst
  product_state/__init__.py
  product_state/__manifest__.py
  product_state/data/product_state_data.xml
  product_state/i18n/de.po
  product_state/i18n/es.po
  product_state/i18n/fr.po
  product_state/i18n/hr.po
  product_state/i18n/nl_NL.po
  product_state/i18n/product_state.pot
  product_state/i18n/pt.po
  product_state/i18n/sl.po
  product_state/migrations/13.0.1.0.0/post-migration.py
  product_state/models/__init__.py
  product_state/models/product_state.py
  product_state/models/product_template.py
  product_state/readme/CONTRIBUTORS.rst
  product_state/readme/DESCRIPTION.rst
  product_state/readme/USAGE.rst
  product_state/security/ir.model.access.csv
  product_state/static/description/icon.png
  product_state/static/description/index.html
  product_state/tests/__init__.py
  product_state/tests/test_product_state.py
  product_state/views/product_template.xml
  setup/product_state/odoo/addons/product_state
  setup/product_state/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#447 [10][ADD] product exception
  product_exception/README.rst
  product_exception/__init__.py
  product_exception/__manifest__.py
  product_exception/data/data.xml
  product_exception/demo/product_exception.xml
  product_exception/models/__init__.py
  product_exception/models/exception_rule.py
  product_exception/models/product.py
  product_exception/readme/CONFIGURE.rst
  product_exception/readme/CONTRIBUTORS.rst
  product_exception/readme/CREDITS.rst
  product_exception/readme/DESCRIPTION.rst
  product_exception/readme/ROADMAP.rst
  product_exception/readme/USAGE.rst
  product_exception/tests/__init__.py
  product_exception/tests/test_product_exception.py
  product_exception/views/product.xml
Labels: approved, bot is merging ⏳, needs review

#671 [ADD] product_template_copy_attributes
  product_template_copy_attributes/__init__.py
  product_template_copy_attributes/__manifest__.py
  product_template_copy_attributes/models/__init__.py
  product_template_copy_attributes/models/product_template.py
  product_template_copy_attributes/readme/CONTRIBUTORS.rst
  product_template_copy_attributes/readme/DESCRIPTION.rst
  product_template_copy_attributes/readme/ROADMAP.rst
  product_template_copy_attributes/tests/__init__.py
  product_template_copy_attributes/tests/test_product_template_copy_attributes.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#755 [MIG] 14.0 base_product_mass_addition
  base_product_mass_addition/README.rst
  base_product_mass_addition/__init__.py
  base_product_mass_addition/__manifest__.py
  base_product_mass_addition/i18n/base_product_mass_addition.pot
  base_product_mass_addition/models/__init__.py
  base_product_mass_addition/models/product_mass_addition.py
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
  base_product_mass_addition/readme/DESCRIPTION.rst
  base_product_mass_addition/readme/ROADMAP.rst
  base_product_mass_addition/static/description/filter.png
  base_product_mass_addition/static/description/icon.png
  base_product_mass_addition/static/description/index.html
  base_product_mass_addition/static/description/po-product.png
  base_product_mass_addition/static/description/po.png
  base_product_mass_addition/views/product_view.xml
  setup/base_product_mass_addition/odoo/addons/base_product_mass_addition
  setup/base_product_mass_addition/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#840 [14.0][MIG] product_assortment
  product_assortment/README.rst
  product_assortment/__init__.py
  product_assortment/__manifest__.py
  product_assortment/i18n/ca.po
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/readme/CONTRIBUTORS.rst
  product_assortment/readme/DESCRIPTION.rst
  product_assortment/readme/HISTORY.rst
  product_assortment/readme/USAGE.rst
  product_assortment/static/description/icon.png
  product_assortment/static/description/index.html
  product_assortment/tests/__init__.py
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
  setup/product_assortment/odoo/addons/product_assortment
  setup/product_assortment/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#850 14.0 mig product packaging dimension
  product_packaging_dimension/README.rst
  product_packaging_dimension/__init__.py
  product_packaging_dimension/__manifest__.py
  product_packaging_dimension/i18n/ca.po
  product_packaging_dimension/i18n/es.po
  product_packaging_dimension/i18n/product_packaging_dimension.pot
  product_packaging_dimension/migrations/14.0.1.0.0/pre-migrate.py
  product_packaging_dimension/models/__init__.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/readme/CONTRIBUTORS.rst
  product_packaging_dimension/readme/DESCRIPTION.rst
  product_packaging_dimension/readme/ROADMAP.rst
  product_packaging_dimension/static/description/icon.png
  product_packaging_dimension/static/description/index.html
  product_packaging_dimension/tests/__init__.py
  product_packaging_dimension/tests/test_packaging_volume.py
  product_packaging_dimension/views/product_packaging.xml
  setup/product_packaging_dimension/odoo/addons/product_packaging_dimension
  setup/product_packaging_dimension/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#768 [14.0][MIG] product_weight
  product_weight/README.rst
  product_weight/__init__.py
  product_weight/__manifest__.py
  product_weight/i18n/ca.po
  product_weight/i18n/de.po
  product_weight/i18n/es.po
  product_weight/i18n/fr.po
  product_weight/i18n/hr.po
  product_weight/i18n/it.po
  product_weight/i18n/nl_NL.po
  product_weight/i18n/product_weight.pot
  product_weight/i18n/sl.po
  product_weight/models/__init__.py
  product_weight/readme/CONTRIBUTORS.rst
  product_weight/readme/DESCRIPTION.rst
  product_weight/readme/USAGE.rst
  product_weight/security/ir.model.access.csv
  product_weight/static/description/icon.png
  product_weight/static/description/index.html
  product_weight/tests/__init__.py
  product_weight/tests/test_compute_bom_weight.py
  product_weight/views/product_view.xml
  product_weight/wizard/__init__.py
  product_weight/wizard/product_weight_update.py
  product_weight/wizard/product_weight_update_view.xml
  setup/product_weight/odoo/addons/product_weight
  setup/product_weight/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge, work in progress

#852 [12.0] new module product_uom_po_domain
  product_uom_po_domain/README.rst
  product_uom_po_domain/__init__.py
  product_uom_po_domain/__manifest__.py
  product_uom_po_domain/demo/res_groups.xml
  product_uom_po_domain/i18n/fr.po
  product_uom_po_domain/models/__init__.py
  product_uom_po_domain/models/product_template.py
  product_uom_po_domain/readme/CONTRIBUTORS.rst
  product_uom_po_domain/readme/DESCRIPTION.rst
  product_uom_po_domain/readme/DEVELOP.rst
  product_uom_po_domain/static/description/with_module.png
  product_uom_po_domain/static/description/without_module.png
  product_uom_po_domain/views/view_product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#855 [14.0] Add product_seasonality
  product_seasonality/README.rst
  product_seasonality/__init__.py
  product_seasonality/__manifest__.py
  product_seasonality/i18n/fr.po
  product_seasonality/models/__init__.py
  product_seasonality/models/res_company.py
  product_seasonality/models/res_partner.py
  product_seasonality/models/seasonal_config.py
  product_seasonality/models/seasonal_config_line.py
  product_seasonality/readme/CONFIGURE.rst
  product_seasonality/readme/CONTRIBUTORS.rst
  product_seasonality/readme/DESCRIPTION.rst
  product_seasonality/security/ir.model.access.csv
  product_seasonality/tests/__init__.py
  product_seasonality/tests/common.py
  product_seasonality/tests/test_company.py
  product_seasonality/tests/test_seasonal_config.py
  product_seasonality/views/res_company.xml
  product_seasonality/views/res_partner.xml
  product_seasonality/views/seasonal_config.xml
  product_seasonality/views/seasonal_config_line.xml
  setup/product_seasonality/odoo/addons/product_seasonality
  setup/product_seasonality/setup.py
Labels: approved, bot is merging ⏳, needs review

#858 [14.0][FIX] product_seasonality: Allow to copy lines
  product_seasonality/models/seasonal_config.py
Labels: bot is merging ⏳

#860 [13.0][FIX] product_pricelist_direct_print: Error when date is not defined
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_supplierinfo/models/product_template.py
Labels: approved, bot is merging ⏳

#844 [14.0][ADD] product_category_code
  product_category_code/README.rst
  product_category_code/__init__.py
  product_category_code/__manifest__.py
  product_category_code/models/__init__.py
  product_category_code/models/product_category.py
  product_category_code/readme/CONTRIBUTORS.rst
  product_category_code/readme/DESCRIPTION.rst
  product_category_code/static/description/icon.png
  product_category_code/static/description/index.html
  product_category_code/tests/__init__.py
  product_category_code/tests/test_category_code.py
  product_category_code/views/product_category.xml
  setup/product_category_code/odoo/addons/product_category_code
  setup/product_category_code/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
