Repository OCA/product-attribute, pull requests merged in 2021-11, with the labels that each got.

#933 [FIX] product_pricelist_direct_print: fix date context
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
Labels: bot is merging ⏳

#757 [ADD] add module product_form_pricelist
  product_form_pricelist/__init__.py
  product_form_pricelist/__manifest__.py
  product_form_pricelist/models/__init__.py
  product_form_pricelist/models/product_pricelist_item.py
  product_form_pricelist/models/product_template.py
  product_form_pricelist/models/res_config_settings.py
  product_form_pricelist/readme/CONFIGURATION.rst
  product_form_pricelist/readme/CONTRIBUTORS.rst
  product_form_pricelist/readme/DESCRIPTION.rst
  product_form_pricelist/readme/USAGE.rst
  product_form_pricelist/security/res_groups.xml
  product_form_pricelist/tests/__init__.py
  product_form_pricelist/tests/test_pricelist.py
  product_form_pricelist/views/product_template_view.xml
  product_form_pricelist/views/product_view.xml
  product_form_pricelist/views/res_config_settings_view.xml
  setup/product_form_pricelist/odoo/addons/product_form_pricelist
  setup/product_form_pricelist/setup.py
Labels: needs review, bot is merging ⏳

#804 12.0 add product category type
  product_category_active/views/product_views.xml
  product_category_type/README.rst
  product_category_type/__init__.py
  product_category_type/__manifest__.py
  product_category_type/demo/product_category.xml
  product_category_type/models/__init__.py
  product_category_type/models/product_category.py
  product_category_type/models/product_template.py
  product_category_type/readme/CONTRIBUTORS.rst
  product_category_type/readme/DESCRIPTION.rst
  product_category_type/static/description/icon.png
  product_category_type/static/description/product_category_tree.png
  product_category_type/static/description/product_template_form.png
  product_category_type/views/product_category.xml
Labels: approved, ready to merge, bot is merging ⏳

#930 [13.0][FIX] product_manufacturer: Keep manufacture information for first variant product creation
  product_manufacturer/models/product_manufacturer.py
  product_manufacturer/readme/CONTRIBUTORS.rst
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
Labels: approved, ready to merge, bot is merging ⏳

#917 [14.0][FIX] product_packaging_unit_price_calculator: fix access rights
  product_packaging_unit_price_calculator/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#939 [14.0][MIG] product_pricelist_revision: Migration to 14.0
  product_pricelist_revision/README.rst
  product_pricelist_revision/__init__.py
  product_pricelist_revision/__manifest__.py
  product_pricelist_revision/i18n/ca.po
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/models/__init__.py
  product_pricelist_revision/models/pricelist.py
  product_pricelist_revision/readme/CONFIGURE.rst
  product_pricelist_revision/readme/CONTRIBUTORS.rst
  product_pricelist_revision/readme/DESCRIPTION.rst
  product_pricelist_revision/readme/USAGE.rst
  product_pricelist_revision/security/ir.model.access.csv
  product_pricelist_revision/static/description/icon.png
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/tests/__init__.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/views/pricelist_view.xml
  product_pricelist_revision/wizards/__init__.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard_view.xml
  setup/product_pricelist_revision/odoo/addons/product_pricelist_revision
  setup/product_pricelist_revision/setup.py
Labels: approved, bot is merging ⏳

#940 [14.0][MIG] product_supplierinfo_revision: Migration to 14.0
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/ca.po
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/readme/CONTRIBUTORS.rst
  product_supplierinfo_revision/readme/DESCRIPTION.rst
  product_supplierinfo_revision/readme/USAGE.rst
  product_supplierinfo_revision/security/ir.model.access.csv
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
  setup/product_supplierinfo_revision/odoo/addons/product_supplierinfo_revision
  setup/product_supplierinfo_revision/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#915 [14.0][ADD] uom_extra_data: have mm, ml, week, work week uom
  uom_extra_data/README.rst
  uom_extra_data/__init__.py
  uom_extra_data/__manifest__.py
  uom_extra_data/data/uom.xml
  uom_extra_data/readme/CONTRIBUTORS.rst
  uom_extra_data/readme/DESCRIPTION.rst
  uom_extra_data/readme/ROADMAP.rst
  uom_extra_data/static/description/icon.png
  uom_extra_data/static/description/index.html
Labels: needs review, approved, ready to merge, bot is merging ⏳

#938 [13.0][ADD] product_pricelist_by_contact: Pricelist per contact
  product_pricelist_by_contact/README.rst
  product_pricelist_by_contact/__init__.py
  product_pricelist_by_contact/__manifest__.py
  product_pricelist_by_contact/readme/CONTRIBUTORS.rst
  product_pricelist_by_contact/readme/DESCRIPTION.rst
  product_pricelist_by_contact/readme/ROADMAP.rst
  product_pricelist_by_contact/readme/USAGE.rst
  product_pricelist_by_contact/static/description/icon.png
  product_pricelist_by_contact/static/description/index.html
  product_pricelist_by_contact/views/res_partner_views.xml
  setup/product_pricelist_by_contact/odoo/addons/product_pricelist_by_contact
  setup/product_pricelist_by_contact/setup.py
Labels: approved, bot is merging ⏳

#941 [14.0][FW] [FIX] [13.0] product_dimension Contributors website
  product_dimension/README.rst
  product_dimension/readme/CONTRIBUTORS.rst
  product_dimension/static/description/index.html
Labels: bot is merging ⏳

#937 [13.0][ADD] product_attribute_archive
  product_attribute_archive/README.rst
  product_attribute_archive/__init__.py
  product_attribute_archive/__manifest__.py
  product_attribute_archive/i18n/product_attribute_archive.pot
  product_attribute_archive/models/__init__.py
  product_attribute_archive/models/product_attribute.py
  product_attribute_archive/models/product_attribute_value.py
  product_attribute_archive/readme/CONTRIBUTORS.rst
  product_attribute_archive/readme/DESCRIPTION.rst
  product_attribute_archive/readme/USAGE.rst
  product_attribute_archive/static/description/icon.png
  product_attribute_archive/static/description/index.html
  product_attribute_archive/views/product_attribute.xml
  setup/product_attribute_archive/odoo/addons/product_attribute_archive
  setup/product_attribute_archive/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#936 [14.0][FIX] product_manufacture: Keep manufacture information for first variant product creation
  product_manufacturer/models/product_manufacturer.py
  product_manufacturer/tests/test_product_manufacturer.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#946 [13.0][FIX] product_pricelist_assortment: fix ir.rule
  product_pricelist_assortment/security/product_pricelist_assortment_item.xml
Labels: enhancement, approved, bot is merging ⏳

#931 [14.0] product_state: move default states to demo data
  product_state/README.rst
  product_state/data/product_state_data.xml
  product_state/models/product_state.py
  product_state/models/product_template.py
  product_state/readme/ROADMAP.rst
  product_state/static/description/index.html
  product_state/tests/test_product_state.py
  product_tier_validation/data/product_state_data.xml
Labels: bot is merging ⏳

#934 [MIG] product_supplierinfo_for_customer: Migration to 15.0
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__init__.py
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/demo/product_demo.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/sl.po
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_pricelist.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/models/res_partner.py
  product_supplierinfo_for_customer/readme/CONFIGURE.rst
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/readme/ROADMAP.rst
  product_supplierinfo_for_customer/readme/USAGE.rst
  product_supplierinfo_for_customer/security/ir.model.access.csv
  product_supplierinfo_for_customer/static/description/icon.png
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/static/xls/product_customerinfo.xls
  product_supplierinfo_for_customer/tests/__init__.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_view.xml
  setup/product_supplierinfo_for_customer/odoo/addons/product_supplierinfo_for_customer
  setup/product_supplierinfo_for_customer/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#846 [14.0][MIG] product_state_history
  product_state_history/README.rst
  product_state_history/__init__.py
  product_state_history/__manifest__.py
  product_state_history/i18n/product_state_history.pot
  product_state_history/migrations/14.0.1.0.1/pre-migrate.py
  product_state_history/models/__init__.py
  product_state_history/models/product_state_history.py
  product_state_history/models/product_template.py
  product_state_history/models/report_product_state_history.py
  product_state_history/readme/CONTRIBUTORS.rst
  product_state_history/readme/DESCRIPTION.rst
  product_state_history/readme/USAGE.rst
  product_state_history/report/report_product_state_history.xml
  product_state_history/security/product_state_history.xml
  product_state_history/security/product_state_history_wizard.xml
  product_state_history/static/description/icon.png
  product_state_history/static/description/index.html
  product_state_history/tests/__init__.py
  product_state_history/tests/common.py
  product_state_history/tests/test_product_state_history.py
  product_state_history/views/product_state_history.xml
  product_state_history/views/product_template.xml
  product_state_history/wizards/__init__.py
  product_state_history/wizards/product_state_history_wizard.py
  product_state_history/wizards/product_state_history_wizard.xml
  setup/product_state_history/odoo/addons/product_state_history
  setup/product_state_history/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
