Repository OCA/product-attribute, pull requests merged in 2021-08, with the labels that each got.

#886 [14.0] [MIG] product_lot_sequence
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/stock_production_lot.py
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/DESCRIPTION.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  setup/product_lot_sequence/odoo/addons/product_lot_sequence
  setup/product_lot_sequence/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#895 [IMP][14.0] product_template_tags: Add tag_ids to tree views
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
Labels: approved, bot is merging ⏳

#898 [13.0][IMP] product_assortment: add icon to menu
  product_assortment/static/description/icon.png
  product_assortment/views/product_assortment.xml
Labels: bot is merging ⏳

#899 Init copier template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  product_custom_info/__manifest__.py
  product_list_pricelist_price/__manifest__.py
  product_lot_sequence/__manifest__.py
  product_manufacturer/__manifest__.py
  product_packaging_unit_price_calculator/__manifest__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print_website_sale/__manifest__.py
  product_pricelist_revision/__manifest__.py
  product_stock_state/__manifest__.py
  product_supplierinfo_revision/__manifest__.py
  product_total_weight_from_packaging/__manifest__.py
Labels: bot is merging ⏳

#901 [MIG] product_barcode_required: Migration to 14.0
  product_barcode_required/README.rst
  product_barcode_required/__init__.py
  product_barcode_required/__manifest__.py
  product_barcode_required/i18n/ca.po
  product_barcode_required/i18n/es.po
  product_barcode_required/models/__init__.py
  product_barcode_required/models/product_barcode_mixin.py
  product_barcode_required/models/product_product.py
  product_barcode_required/models/product_template.py
  product_barcode_required/models/res_company.py
  product_barcode_required/models/res_config_settings.py
  product_barcode_required/readme/CONFIGURE.rst
  product_barcode_required/readme/CONTRIBUTORS.rst
  product_barcode_required/readme/DESCRIPTION.rst
  product_barcode_required/static/description/icon.png
  product_barcode_required/static/description/index.html
  product_barcode_required/tests/__init__.py
  product_barcode_required/tests/test_barcode.py
  product_barcode_required/views/product_template_view.xml
  product_barcode_required/views/product_view.xml
  product_barcode_required/views/res_config_settings.xml
  setup/product_barcode_required/odoo/addons/product_barcode_required
  setup/product_barcode_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#903 [13.0] product_packaging_type_required: improve + add test
  product_packaging_type_required/__manifest__.py
  product_packaging_type_required/data/cron.xml
  product_packaging_type_required/migrations/13.0.1.1.0/post-migrate.py
  product_packaging_type_required/models/product_packaging_type.py
  product_packaging_type_required/readme/CONTRIBUTORS.rst
  product_packaging_type_required/tests/__init__.py
  product_packaging_type_required/tests/test_packaging_required.py
Labels: approved, bot is merging ⏳

#792 [MIG] product_packaging_type_required: Migration to 14.0
  product_packaging_type_required/README.rst
  product_packaging_type_required/__init__.py
  product_packaging_type_required/__manifest__.py
  product_packaging_type_required/data/cron.xml
  product_packaging_type_required/i18n/es.po
  product_packaging_type_required/i18n/product_packaging_type_required.pot
  product_packaging_type_required/models/__init__.py
  product_packaging_type_required/models/product_packaging_type.py
  product_packaging_type_required/readme/CONTRIBUTORS.rst
  product_packaging_type_required/readme/CREDITS.rst
  product_packaging_type_required/readme/DESCRIPTION.rst
  product_packaging_type_required/readme/USAGE.rst
  product_packaging_type_required/static/description/icon.png
  product_packaging_type_required/static/description/index.html
  product_packaging_type_required/views/product_packaging_type_view.xml
  setup/product_packaging_type_required/odoo/addons/product_packaging_type_required
  setup/product_packaging_type_required/setup.py
Labels: approved, bot is merging ⏳

#894 [ADD][12.0] new module product_net_weight
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/fr.po
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/readme/CONTRIBUTORS.rst
  product_net_weight/readme/DESCRIPTION.rst
  product_net_weight/readme/ROADMAP.rst
  product_net_weight/readme/USAGE.rst
  product_net_weight/static/description/product_form.png
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
