Repository OCA/product-attribute, pull requests merged in 2021-01, with the labels that each got.

#754 [12.0][IMP] product_pricelist_direct_print: Improve inheritability and simplify Qweb
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#763 [13.0][IMP] product_pricelist_direct_print: Improve inheritability
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#758 [FIX] product_pricelist_supplierinfo: ensure product exists
  product_pricelist_supplierinfo/models/product_template.py
Labels: bot is merging ⏳

#762 [MIG] product_product_template_navigation: Migration to 13.0
  product_product_template_navigation/README.rst
  product_product_template_navigation/__init__.py
  product_product_template_navigation/__manifest__.py
  product_product_template_navigation/i18n/es.po
  product_product_template_navigation/i18n/product_product_template_navigation.pot
  product_product_template_navigation/models/__init__.py
  product_product_template_navigation/models/product_product.py
  product_product_template_navigation/readme/CONTRIBUTORS.rst
  product_product_template_navigation/readme/DESCRIPTION.rst
  product_product_template_navigation/static/description/icon.png
  product_product_template_navigation/static/description/index.html
  product_product_template_navigation/static/img/template_navigation.gif
  product_product_template_navigation/views/product_product_views.xml
  setup/product_product_template_navigation/odoo/addons/product_product_template_navigation
  setup/product_product_template_navigation/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#767 [13.0][IMP] product_secondary_unit: Add mixin model to be inherited from other models
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  requirements.txt
Labels: approved, bot is merging ⏳

#770 [13.0] Fix barcode required error on variants creation
  product_barcode_required/models/product_template.py
Labels: approved, bot is merging ⏳

#737 [12.0][IMP] product_sequence: Use parent categories to determine the prefix …
  product_sequence/__manifest__.py
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/readme/USAGE.rst
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#776 [12.0][FIX] product_pricelist_supplierinfo: Convert price to UOM on the Sale
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: approved, bot is merging ⏳

#778 [13.0][IMP] Use parent categories to determine the prefix if the category has no …
  product_sequence/__manifest__.py
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/readme/USAGE.rst
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#775 [12.0][FIX] product_dimension : compatibility with product_logistics_uom's volume_uom_id
  product_dimension/__manifest__.py
  product_dimension/models/product.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/views/product_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
