Repository OCA/product-attribute, pull requests merged in 2021-06, with the labels that each got.

#864 [IMP][14.0] base_product_mass_addition: add support for UoM
  base_product_mass_addition/models/product_mass_addition.py
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, enhancement, needs review

#837 [14.0][ADD] product_category_product_link
  product_category_product_link/README.rst
  product_category_product_link/__init__.py
  product_category_product_link/__manifest__.py
  product_category_product_link/models/__init__.py
  product_category_product_link/models/product_category.py
  product_category_product_link/models/product_template.py
  product_category_product_link/readme/CONTRIBUTORS.rst
  product_category_product_link/readme/DESCRIPTION.rst
  product_category_product_link/static/description/icon.png
  product_category_product_link/static/description/index.html
  setup/product_category_product_link/odoo/addons/product_category_product_link
  setup/product_category_product_link/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#752 [ADD] 12.0 : product_active_propagate : new module to avoid having inconsistent states between the active field of the variant and the active field of the template
  product_active_propagate/README.rst
  product_active_propagate/__init__.py
  product_active_propagate/__manifest__.py
  product_active_propagate/i18n/fr.po
  product_active_propagate/models/__init__.py
  product_active_propagate/models/product_product.py
  product_active_propagate/readme/CONTRIBUTORS.rst
  product_active_propagate/readme/DESCRIPTION.rst
  product_active_propagate/readme/DEVELOP.rst
  product_active_propagate/readme/INSTALL.rst
  product_active_propagate/tests/__init__.py
  product_active_propagate/tests/test_module.py
Labels: approved, bot is merging ⏳, ready to merge

#871 [14.0][IMP] product_seasonality: Add product template on config lines
  product_seasonality/__manifest__.py
  product_seasonality/i18n/fr.po
  product_seasonality/i18n/product_seasonality.pot
  product_seasonality/migrations/14.0.1.1.0/post-migration.py
  product_seasonality/models/seasonal_config_line.py
  product_seasonality/tests/common.py
  product_seasonality/views/seasonal_config.xml
  product_seasonality/views/seasonal_config_line.xml
Labels: approved, bot is merging ⏳

#866 [14.0] product_seasonality: add display_name to config line
  product_seasonality/models/seasonal_config_line.py
  product_seasonality/tests/test_seasonal_config.py
Labels: bot is merging ⏳

#867 [14.0][ADD] product_attribute_archive
  product_attribute_archive/README.rst
  product_attribute_archive/__init__.py
  product_attribute_archive/__manifest__.py
  product_attribute_archive/models/__init__.py
  product_attribute_archive/models/product_attribute.py
  product_attribute_archive/models/product_attribute_value.py
  product_attribute_archive/readme/CONTRIBUTORS.rst
  product_attribute_archive/readme/DESCRIPTION.rst
  product_attribute_archive/readme/USAGE.rst
  product_attribute_archive/static/description/icon.png
  product_attribute_archive/views/product_attribute.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#800 [MIG] product_packaging_type_pallet: Migration to 14.0
  product_packaging_type_pallet/README.rst
  product_packaging_type_pallet/__init__.py
  product_packaging_type_pallet/__manifest__.py
  product_packaging_type_pallet/i18n/es.po
  product_packaging_type_pallet/i18n/product_packaging_type_pallet.pot
  product_packaging_type_pallet/models/__init__.py
  product_packaging_type_pallet/models/product_packaging.py
  product_packaging_type_pallet/readme/CONTRIBUTORS.rst
  product_packaging_type_pallet/readme/DESCRIPTION.rst
  product_packaging_type_pallet/readme/README.md
  product_packaging_type_pallet/static/description/icon.png
  product_packaging_type_pallet/static/description/index.html
  product_packaging_type_pallet/views/product_packaging.xml
  product_packaging_type_pallet/views/product_packaging_type.xml
  setup/product_packaging_type_pallet/odoo/addons/product_packaging_type_pallet
  setup/product_packaging_type_pallet/setup.py
Labels: approved, bot is merging ⏳, ready to merge
