Repository OCA/product-attribute, pull requests merged in 2021-07, with the labels that each got.

#769 [14.0][ADD] product_weight_logistics_uom
  product_weight_logistics_uom/README.rst
  product_weight_logistics_uom/__init__.py
  product_weight_logistics_uom/__manifest__.py
  product_weight_logistics_uom/readme/CONFIGURE.rst
  product_weight_logistics_uom/readme/CONTRIBUTORS.rst
  product_weight_logistics_uom/readme/CREDITS.rst
  product_weight_logistics_uom/readme/DESCRIPTION.rst
  product_weight_logistics_uom/static/description/icon.png
  product_weight_logistics_uom/static/description/index.html
  product_weight_logistics_uom/tests/__init__.py
  product_weight_logistics_uom/tests/test_product_weight_logistics_uom.py
  product_weight_logistics_uom/wizard/__init__.py
  product_weight_logistics_uom/wizard/product_weight_update.py
  setup/product_weight_logistics_uom/odoo/addons/product_weight_logistics_uom
  setup/product_weight_logistics_uom/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#505 [10.0][RM] conflicts key from manifest file - product_categ_image
  product_categ_image/README.rst
  product_categ_image/__manifest__.py
Labels: approved, bot is merging ⏳

#874 [FIX] product_template_tags: fix rule because multicompany scheme change
  product_template_tags/__manifest__.py
  product_template_tags/security/product_template_rule.xml
Labels: approved, bot is merging ⏳, ready to merge

#765 [14.0][MIG] product_total_weight_from_packaging
  product_total_weight_from_packaging/README.rst
  product_total_weight_from_packaging/__init__.py
  product_total_weight_from_packaging/__manifest__.py
  product_total_weight_from_packaging/i18n/es.po
  product_total_weight_from_packaging/i18n/product_total_weight_from_packaging.pot
  product_total_weight_from_packaging/models/__init__.py
  product_total_weight_from_packaging/models/product.py
  product_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  product_total_weight_from_packaging/readme/DESCRIPTION.rst
  product_total_weight_from_packaging/static/description/icon.png
  product_total_weight_from_packaging/static/description/index.html
  product_total_weight_from_packaging/tests/__init__.py
  product_total_weight_from_packaging/tests/test_product_total_weight_from_packaging.py
  setup/product_total_weight_from_packaging/odoo/addons/product_total_weight_from_packaging
  setup/product_total_weight_from_packaging/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#861 [14.0][MIG] - packaging_uom
  packaging_uom/README.rst
  packaging_uom/__init__.py
  packaging_uom/__manifest__.py
  packaging_uom/i18n/ca.po
  packaging_uom/i18n/cs_CZ.po
  packaging_uom/i18n/de.po
  packaging_uom/i18n/es.po
  packaging_uom/i18n/fi.po
  packaging_uom/i18n/fr.po
  packaging_uom/i18n/hr.po
  packaging_uom/i18n/hr_HR.po
  packaging_uom/i18n/it.po
  packaging_uom/i18n/nl.po
  packaging_uom/i18n/packaging_uom.pot
  packaging_uom/i18n/pt.po
  packaging_uom/i18n/pt_BR.po
  packaging_uom/i18n/sl.po
  packaging_uom/models/__init__.py
  packaging_uom/models/product_packaging.py
  packaging_uom/readme/CONFIGURE.rst
  packaging_uom/readme/CONTRIBUTORS.rst
  packaging_uom/readme/DESCRIPTION.rst
  packaging_uom/readme/HISTORY.rst
  packaging_uom/readme/USAGE.rst
  packaging_uom/static/description/icon.png
  packaging_uom/static/description/index.html
  packaging_uom/tests/__init__.py
  packaging_uom/tests/test_product_packaging.py
  packaging_uom/views/product_packaging_views.xml
  setup/packaging_uom/odoo/addons/packaging_uom
  setup/packaging_uom/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#876 [14.0] product_seasonality: fix name compute w/out variant
  product_seasonality/models/seasonal_config_line.py
  product_seasonality/tests/test_seasonal_config.py
Labels: bot is merging ⏳

#806 [MIG][13.0] product_custom_info
  product_custom_info/README.rst
  product_custom_info/__init__.py
  product_custom_info/__manifest__.py
  product_custom_info/i18n/ca.po
  product_custom_info/i18n/es.po
  product_custom_info/i18n/product_custom_info.pot
  product_custom_info/i18n/pt.po
  product_custom_info/models/__init__.py
  product_custom_info/models/product_product.py
  product_custom_info/models/product_template.py
  product_custom_info/static/description/icon.png
  product_custom_info/views/product_product_view.xml
  product_custom_info/views/product_template_view.xml
  setup/product_custom_info/odoo/addons/product_custom_info
  setup/product_custom_info/setup.py
Labels: approved, bot is merging ⏳

#884 [13.0][FIX] product_secondary_unit: Cache miss error.
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#880 [14.0][IMP] product_template_tags: usability improvements
  product_template_tags/__manifest__.py
  product_template_tags/models/product_template.py
  product_template_tags/models/product_template_tag.py
  product_template_tags/readme/CONTRIBUTORS.rst
  product_template_tags/security/product_template_rule.xml
  product_template_tags/security/product_template_tag.xml
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
  product_template_tags/views/product_template_tag.xml
  purchase_product_template_tags/README.rst
  purchase_product_template_tags/__init__.py
  purchase_product_template_tags/__manifest__.py
  purchase_product_template_tags/readme/CONTRIBUTORS.rst
  purchase_product_template_tags/readme/DESCRIPTION.rst
  purchase_product_template_tags/views/product_template_tag.xml
  sale_product_template_tags/README.rst
  sale_product_template_tags/__init__.py
  sale_product_template_tags/__manifest__.py
  sale_product_template_tags/readme/CONTRIBUTORS.rst
  sale_product_template_tags/readme/DESCRIPTION.rst
  sale_product_template_tags/views/product_template_tag.xml
  setup/purchase_product_template_tags/odoo/addons/purchase_product_template_tags
  setup/purchase_product_template_tags/setup.py
  setup/sale_product_template_tags/odoo/addons/sale_product_template_tags
  setup/sale_product_template_tags/setup.py
  setup/stock_product_template_tags/odoo/addons/stock_product_template_tags
  setup/stock_product_template_tags/setup.py
  stock_product_template_tags/README.rst
  stock_product_template_tags/__init__.py
  stock_product_template_tags/__manifest__.py
  stock_product_template_tags/readme/CONTRIBUTORS.rst
  stock_product_template_tags/readme/DESCRIPTION.rst
  stock_product_template_tags/views/product_template_tag.xml
Labels: approved, bot is merging ⏳, ready to merge

#875 [14.0] product_assortment: fix default model_id
  product_assortment/models/ir_filters.py
Labels: approved, bot is merging ⏳, bug, ready to merge

#883 [13.0][ADD] product_list_pricelist_price
  product_list_pricelist_price/README.rst
  product_list_pricelist_price/__init__.py
  product_list_pricelist_price/__manifest__.py
  product_list_pricelist_price/models/__init__.py
  product_list_pricelist_price/models/product_pricelist.py
  product_list_pricelist_price/models/product_product.py
  product_list_pricelist_price/models/product_template.py
  product_list_pricelist_price/readme/CONTRIBUTORS.rst
  product_list_pricelist_price/readme/DESCRIPTION.rst
  product_list_pricelist_price/readme/USAGE.rst
  product_list_pricelist_price/static/description/icon.png
  product_list_pricelist_price/static/description/index.html
  product_list_pricelist_price/tests/__init__.py
  product_list_pricelist_price/tests/test_product_list_pricelist_price.py
  product_list_pricelist_price/views/product_pricelist_views.xml
  product_list_pricelist_price/views/product_template_views.xml
  product_list_pricelist_price/views/product_views.xml
  setup/product_list_pricelist_price/odoo/addons/product_list_pricelist_price
  setup/product_list_pricelist_price/setup.py
Labels: approved, bot is merging ⏳

#802 [MIG] product_uom_updatable: Migration to 14.0
  product_uom_updatable/README.rst
  product_uom_updatable/__init__.py
  product_uom_updatable/__manifest__.py
  product_uom_updatable/i18n/product_uom_updatable.pot
  product_uom_updatable/models/__init__.py
  product_uom_updatable/models/product_template.py
  product_uom_updatable/readme/CONTRIBUTORS.rst
  product_uom_updatable/readme/CREDITS.rst
  product_uom_updatable/readme/DESCRIPTION.rst
  product_uom_updatable/static/description/icon.png
  product_uom_updatable/static/description/index.html
  product_uom_updatable/tests/__init__.py
  product_uom_updatable/tests/test_product_uom_update.py
  setup/product_uom_updatable/odoo/addons/product_uom_updatable
  setup/product_uom_updatable/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#888 p_packaging_type: imp qty per type
  product_packaging_type/models/product_packaging_type.py
Labels: approved, bot is merging ⏳, needs review

#859 [14.0] mig product_supplierinfo_for_customer
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__init__.py
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/demo/product_demo.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/sl.po
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_pricelist.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/models/res_partner.py
  product_supplierinfo_for_customer/readme/CONFIGURE.rst
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/readme/ROADMAP.rst
  product_supplierinfo_for_customer/readme/USAGE.rst
  product_supplierinfo_for_customer/security/ir.model.access.csv
  product_supplierinfo_for_customer/static/description/icon.png
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/static/xls/product_customerinfo.xls
  product_supplierinfo_for_customer/tests/__init__.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_view.xml
Labels: approved, bot is merging ⏳, migration, needs review

#891 [13.0][IMP] product_supplierinfo_for_customer: add `_select_customerinfo
  product_supplierinfo_for_customer/models/product_product.py
Labels: approved, bot is merging ⏳

#885 [14.0][FIX] product_manufacturer: access form view from tree view
  product_manufacturer/views/product_manufacturer_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#879 [14.0][IMP] product_state: Prevent a write with both values
  product_state/models/product_template.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#803 [MIG] product_template_tags_code: Migration to 14.0
  product_template_tags_code/README.rst
  product_template_tags_code/__init__.py
  product_template_tags_code/__manifest__.py
  product_template_tags_code/i18n/es.po
  product_template_tags_code/i18n/product_template_tags_code.pot
  product_template_tags_code/migrations/13.0.1.0.0/post-migration.py
  product_template_tags_code/models/__init__.py
  product_template_tags_code/models/product_template_tag.py
  product_template_tags_code/readme/CONFIGURE.rst
  product_template_tags_code/readme/CONTRIBUTORS.rst
  product_template_tags_code/readme/CREDITS.rst
  product_template_tags_code/readme/DESCRIPTION.rst
  product_template_tags_code/static/description/icon.png
  product_template_tags_code/static/description/index.html
  product_template_tags_code/tests/__init__.py
  product_template_tags_code/tests/test_product_template_tags.py
  product_template_tags_code/views/product_template_tag.xml
  setup/product_template_tags_code/odoo/addons/product_template_tags_code
  setup/product_template_tags_code/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#805 [MIG] product_medical: Migration to 14.0
  product_medical/README.rst
  product_medical/__init__.py
  product_medical/__manifest__.py
  product_medical/data/in_vitro_diagnostic_data.xml
  product_medical/data/medical_data.xml
  product_medical/data/medicine_category_data.xml
  product_medical/data/ppe_category_data.xml
  product_medical/i18n/ca.po
  product_medical/i18n/de.po
  product_medical/i18n/es.po
  product_medical/i18n/product_medical.pot
  product_medical/migrations/13.0.1.1.0/post-migration.py
  product_medical/models/__init__.py
  product_medical/models/in_vitro_diagnostic.py
  product_medical/models/medical_category.py
  product_medical/models/medical_class.py
  product_medical/models/ppe_category.py
  product_medical/models/product_template.py
  product_medical/readme/CONTRIBUTORS.rst
  product_medical/readme/CREDITS.rst
  product_medical/readme/DESCRIPTION.rst
  product_medical/security/ir.model.access.csv
  product_medical/static/description/icon.png
  product_medical/static/description/index.html
  product_medical/views/in_vitro_diagnostic.xml
  product_medical/views/medical_class.xml
  product_medical/views/medicine_category.xml
  product_medical/views/ppe_category.xml
  product_medical/views/product_template.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#848 14 add product secondary unit mixin
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳

#878 [13.0][IMP] product_assortment: Allow to use assortment based on partner domain
  product_assortment/models/ir_filters.py
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
Labels: approved, bot is merging ⏳

#893 [14.0][IMP] product_supplierinfo_for_customer: add `_select_customerinfo`
  product_supplierinfo_for_customer/models/product_product.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#889 [13.0][ADD] product_dimension_volumetric_weight: Add Product Uom Volumetric Weight
  product_dimension_volumetric_weight/README.rst
  product_dimension_volumetric_weight/__init__.py
  product_dimension_volumetric_weight/__manifest__.py
  product_dimension_volumetric_weight/i18n/es.po
  product_dimension_volumetric_weight/i18n/product_uom_volumetric_weight.pot
  product_dimension_volumetric_weight/models/__init__.py
  product_dimension_volumetric_weight/models/product_product.py
  product_dimension_volumetric_weight/models/product_template.py
  product_dimension_volumetric_weight/models/uom_uom.py
  product_dimension_volumetric_weight/readme/CONFIGURE.rst
  product_dimension_volumetric_weight/readme/CONTRIBUTORS.rst
  product_dimension_volumetric_weight/readme/DESCRIPTION.rst
  product_dimension_volumetric_weight/readme/USAGE.rst
  product_dimension_volumetric_weight/static/description/icon.png
  product_dimension_volumetric_weight/static/description/index.html
  product_dimension_volumetric_weight/tests/__init__.py
  product_dimension_volumetric_weight/tests/test_product_uom.py
  product_dimension_volumetric_weight/views/product_view.xml
  product_dimension_volumetric_weight/views/uom_uom_view.xml
  setup/product_dimension_volumetric_weight/odoo/addons/product_dimension_volumetric_weight
  setup/product_dimension_volumetric_weight/setup.py
Labels: approved, bot is merging ⏳, needs review
