Repository OCA/product-attribute, pull requests merged in 2021-12, with the labels that each got.

#623 [13.0][ADD] product_abc_classification
  product_abc_classification/__init__.py
  product_abc_classification/__manifest__.py
  product_abc_classification/data/ir_cron.xml
  product_abc_classification/models/__init__.py
  product_abc_classification/models/abc_classification_level.py
  product_abc_classification/models/abc_classification_profile.py
  product_abc_classification/models/product_category.py
  product_abc_classification/models/product_product.py
  product_abc_classification/readme/CONTRIBUTORS.rst
  product_abc_classification/readme/DESCRIPTION.rst
  product_abc_classification/readme/USAGE.rst
  product_abc_classification/security/ir.model.access.csv
  product_abc_classification/static/description/icon.png
  product_abc_classification/views/abc_classification_view.xml
  product_abc_classification/views/product_view.xml
Labels: needs review, bot is merging ⏳

#950 [13.0][ADD] product_variant_attribute_name_manager
  product_variant_attribute_name_manager/__init__.py
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/models/__init__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/tests/__init__.py
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
  setup/product_variant_attribute_name_manager/odoo/addons/product_variant_attribute_name_manager
  setup/product_variant_attribute_name_manager/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#514 [12.0] [ADD] Product Documentation Set feature
  product_documentation_set/README.rst
  product_documentation_set/__init__.py
  product_documentation_set/__manifest__.py
  product_documentation_set/models/__init__.py
  product_documentation_set/models/product_category.py
  product_documentation_set/models/product_documentation_set.py
  product_documentation_set/models/product_template.py
  product_documentation_set/readme/CONFIGURE.rst
  product_documentation_set/readme/CONTRIBUTORS.rst
  product_documentation_set/readme/DESCRIPTION.rst
  product_documentation_set/readme/USAGE.rst
  product_documentation_set/security/product_documentation_set.xml
  product_documentation_set/static/description/icon.png
  product_documentation_set/tests/__init__.py
  product_documentation_set/tests/test_product_doc.py
  product_documentation_set/views/product_category.xml
  product_documentation_set/views/product_documentation_set.xml
  product_documentation_set/views/product_template.xml
Labels: enhancement, needs review, bot is merging ⏳

#948 [14.0][ADD] product_state_active
  product_state_active/README.rst
  product_state_active/__init__.py
  product_state_active/__manifest__.py
  product_state_active/models/__init__.py
  product_state_active/models/product_state.py
  product_state_active/models/product_template.py
  product_state_active/readme/CONTRIBUTORS.rst
  product_state_active/readme/DESCRIPTION.rst
  product_state_active/readme/USAGE.rst
  product_state_active/static/description/icon.png
  product_state_active/static/description/index.html
  product_state_active/tests/__init__.py
  product_state_active/tests/test_product_state.py
  product_state_active/views/product_state.xml
  setup/product_state_active/odoo/addons/product_state_active
  setup/product_state_active/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#959 [13.0][IMP] product_assortment: Add demo data for product_assortment module
  product_assortment/__manifest__.py
  product_assortment/demo/assortments.xml
Labels: approved, bot is merging ⏳

#869 [14.0] product_assortment: misc fixes
  product_assortment/models/ir_filters.py
  product_assortment/tests/test_product_assortment.py
Labels: enhancement, question, approved, ready to merge, bot is merging ⏳

#961 [14.0] [FIX] product_state
  product_state/models/product_template.py
  product_state/tests/test_product_state.py
  product_state/views/product_template.xml
Labels: approved, bot is merging ⏳

#951 [14.0][IMP] product_tier_validation: Simplify flow
  product_tier_validation/__manifest__.py
  product_tier_validation/data/product_state_data.xml
  product_tier_validation/models/product_template.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#958 [IMP] add module for adding video on product and category
  product_video_link/__init__.py
  product_video_link/__manifest__.py
  product_video_link/demo/product_demo.xml
  product_video_link/models/__init__.py
  product_video_link/models/product_category.py
  product_video_link/models/product_template.py
  product_video_link/readme/CONTRIBUTORS.rst
  product_video_link/readme/DESCRIPTION.rst
  product_video_link/readme/USAGE.rst
  product_video_link/security/ir.model.access.csv
  product_video_link/views/product_category_view.xml
  product_video_link/views/product_template_view.xml
  setup/product_video_link/odoo/addons/product_video_link
  setup/product_video_link/setup.py
Labels: approved, bot is merging ⏳

#910 [14.0][ADD] product_pricelist_button_box
  product_pricelist_button_box/README.rst
  product_pricelist_button_box/__init__.py
  product_pricelist_button_box/__manifest__.py
  product_pricelist_button_box/readme/CONTRIBUTORS.rst
  product_pricelist_button_box/readme/DESCRIPTION.rst
  product_pricelist_button_box/static/description/icon.png
  product_pricelist_button_box/static/description/index.html
  product_pricelist_button_box/views/product_pricelist.xml
  setup/product_pricelist_button_box/odoo/addons/product_pricelist_button_box
  setup/product_pricelist_button_box/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#955 [14.0][MIG] product_model_viewer
  product_model_viewer/README.rst
  product_model_viewer/__init__.py
  product_model_viewer/__manifest__.py
  product_model_viewer/data/product_demo.xml
  product_model_viewer/i18n/ca.po
  product_model_viewer/i18n/es.po
  product_model_viewer/i18n/product_model_viewer.pot
  product_model_viewer/models/__init__.py
  product_model_viewer/models/product.py
  product_model_viewer/readme/CONTRIBUTORS.rst
  product_model_viewer/readme/DESCRIPTION.rst
  product_model_viewer/readme/HISTORY.rst
  product_model_viewer/readme/USAGE.rst
  product_model_viewer/static/description/icon.png
  product_model_viewer/static/description/index.html
  product_model_viewer/views/product_views.xml
  setup/product_model_viewer/odoo/addons/product_model_viewer
  setup/product_model_viewer/setup.py
Labels: approved, ready to merge, bot is merging ⏳
