Repository OCA/product-attribute, pull requests merged in 2021-02, with the labels that each got.

#773 [FIX] product_secondary_unit: Avoid to recompute secondary_uom_qty when secondary uom changes
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳, ready to merge

#788 [12.0] [IMP] product_pricelist_direct_print: xlsx and new option to print defined products
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/report/__init__.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.xml
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#779 [14.0][IMP] Use parent categories to determine the prefix if the category has no …
  product_sequence/__manifest__.py
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/readme/USAGE.rst
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#790 [12.0] [FIX] product_pricelist_direct_print: Fixed translations on xlsx generator
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
Labels: bot is merging ⏳

#794 [13.0][FIX] packaging_uom: Avoid packaging quantities with 0.0, improve tests
  packaging_uom/models/product_packaging.py
  packaging_uom/tests/test_product_packaging.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#796 [12.0][IMP] product_pricelist_revision: Add percent price column and current filter
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/views/pricelist_view.xml
Labels: approved, bot is merging ⏳

#563 [MIG][13.0] product_pricelist_revision: Migration to v13.0
  product_pricelist_revision/README.rst
  product_pricelist_revision/__init__.py
  product_pricelist_revision/__manifest__.py
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/models/__init__.py
  product_pricelist_revision/models/pricelist.py
  product_pricelist_revision/readme/CONFIGURE.rst
  product_pricelist_revision/readme/CONTRIBUTORS.rst
  product_pricelist_revision/readme/DESCRIPTION.rst
  product_pricelist_revision/readme/USAGE.rst
  product_pricelist_revision/static/description/icon.png
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/tests/__init__.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/views/pricelist_view.xml
  product_pricelist_revision/wizards/__init__.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard_view.xml
  setup/product_pricelist_revision/odoo/addons/product_pricelist_revision
  setup/product_pricelist_revision/setup.py
Labels: bot is merging ⏳

#797 [14.0][MIG] product_manufacturer
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_manufacturer.py
  product_manufacturer/readme/CONTRIBUTORS.rst
  product_manufacturer/readme/DESCRIPTION.rst
  product_manufacturer/static/description/icon.png
  product_manufacturer/static/description/index.html
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
  setup/product_manufacturer/odoo/addons/product_manufacturer
  setup/product_manufacturer/setup.py
Labels: approved, bot is merging ⏳, ready to merge
