Repository OCA/product-attribute, pull requests merged in 2021-09, with the labels that each got.

#907 [14.0][FIX] secondary_uom: independent behavior
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#897 [13.0][FIX] packaging_uom: inverse_qty ValueError
  packaging_uom/models/product_packaging.py
  packaging_uom/tests/test_product_packaging.py
Labels: approved, ready to merge, bot is merging ⏳

#908 [14.0][FIX] product_packaging_dimension: _compute_volume for multi records
  product_packaging_dimension/models/product_packaging.py
Labels: approved, bot is merging ⏳

#887 [13.0][IMP] product_pricelist_direct_print: Possibility of break by parent categories
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#912 product_packaging_type: split qty per type data
  product_packaging_type/models/product_packaging_type.py
Labels: enhancement, needs review, bot is merging ⏳

#856 [14.0] [NEW] product_tier_validation: New module to validate the product.
  oca_dependencies.txt
  product_tier_validation/README.rst
  product_tier_validation/__init__.py
  product_tier_validation/__manifest__.py
  product_tier_validation/data/product_state_data.xml
  product_tier_validation/data/tier_definition.xml
  product_tier_validation/models/__init__.py
  product_tier_validation/models/product_template.py
  product_tier_validation/models/tier_definition.py
  product_tier_validation/readme/CONFIGURATION.rst
  product_tier_validation/readme/CONTRIBUTORS.rst
  product_tier_validation/readme/DESCRIPTION.rst
  product_tier_validation/readme/INSTALL.rst
  product_tier_validation/readme/USAGE.rst
  product_tier_validation/static/description/icon.png
  product_tier_validation/tests/__init__.py
  product_tier_validation/tests/test_product_tier_validation.py
  product_tier_validation/views/product_template_view.xml
  setup/product_tier_validation/odoo/addons/product_tier_validation
  setup/product_tier_validation/setup.py
Labels: needs review, approved, bot is merging ⏳

#734 14.0 mig product profile
  product_profile/README.rst
  product_profile/__init__.py
  product_profile/__manifest__.py
  product_profile/i18n/ca.po
  product_profile/i18n/de.po
  product_profile/i18n/es.po
  product_profile/i18n/fr.po
  product_profile/i18n/hr.po
  product_profile/i18n/it.po
  product_profile/i18n/nl_NL.po
  product_profile/i18n/product_profile.pot
  product_profile/i18n/sl.po
  product_profile/models/__init__.py
  product_profile/models/config.py
  product_profile/models/product.py
  product_profile/models/product_profile.py
  product_profile/readme/CONFIGURE.rst
  product_profile/readme/CONTRIBUTORS.rst
  product_profile/readme/DESCRIPTION.rst
  product_profile/readme/ROADMAP.rst
  product_profile/readme/USAGE.rst
  product_profile/security/group.xml
  product_profile/security/ir.model.access.csv
  product_profile/static/description/icon.png
  product_profile/static/description/index.html
  product_profile/static/img/field.png
  product_profile/static/img/list.png
  product_profile/views/config_view.xml
  product_profile/views/product_view.xml
  setup/product_profile/odoo/addons/product_profile
  setup/product_profile/setup.py
Labels: work in progress, approved, bot is merging ⏳
