Repository OCA/product-attribute, pull requests merged in 2021-03, with the labels that each got.

#816 [12.0][FIX] product_weight: Adapting test to new constraint
  product_weight/README.rst
  product_weight/readme/CONTRIBUTORS.rst
  product_weight/static/description/index.html
  product_weight/tests/test_compute_bom_weight.py
Labels: approved, bot is merging ⏳

#756 [12.0] [ADD] product_pricelist_print_website_sale: New module that extend product_pricelist_direct_print
  product_pricelist_print_website_sale/README.rst
  product_pricelist_print_website_sale/__init__.py
  product_pricelist_print_website_sale/__manifest__.py
  product_pricelist_print_website_sale/i18n/es.po
  product_pricelist_print_website_sale/i18n/product_pricelist_print_website_sale.pot
  product_pricelist_print_website_sale/readme/CONTRIBUTORS.rst
  product_pricelist_print_website_sale/readme/DESCRIPTION.rst
  product_pricelist_print_website_sale/readme/USAGE.rst
  product_pricelist_print_website_sale/static/description/icon.png
  product_pricelist_print_website_sale/static/description/index.html
  product_pricelist_print_website_sale/wizards/__init__.py
  product_pricelist_print_website_sale/wizards/product_pricelist_print.py
  product_pricelist_print_website_sale/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳, needs review

#818 [13.0][FIX] product_pricelist_revision: Applied the new way for digits
  product_pricelist_revision/README.rst
  product_pricelist_revision/readme/CONFIGURE.rst
  product_pricelist_revision/readme/CONTRIBUTORS.rst
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
Labels: approved, bot is merging ⏳

#808 [13.0] [MIG] product_category_archive: Migration to v13.0
  product_category_active/README.rst
  product_category_active/__init__.py
  product_category_active/__manifest__.py
  product_category_active/i18n/ca.po
  product_category_active/i18n/es.po
  product_category_active/i18n/product_category_active.pot
  product_category_active/i18n/pt.po
  product_category_active/models/__init__.py
  product_category_active/models/product.py
  product_category_active/readme/CONTRIBUTORS.rst
  product_category_active/readme/DESCRIPTION.rst
  product_category_active/readme/ROADMAP.rst
  product_category_active/readme/USAGE.rst
  product_category_active/static/description/icon.png
  product_category_active/static/description/index.html
  product_category_active/tests/__init__.py
  product_category_active/tests/test_product_category_active.py
  product_category_active/views/product_views.xml
  setup/product_category_active/odoo/addons/product_category_active
  setup/product_category_active/setup.py
Labels: approved, bot is merging ⏳

#809 [ADD] pos_product_cost_security: glue module
  pos_product_cost_security/README.rst
  pos_product_cost_security/__init__.py
  pos_product_cost_security/__manifest__.py
  pos_product_cost_security/models/__init__.py
  pos_product_cost_security/models/product_product.py
  pos_product_cost_security/readme/CONTRIBUTORS.rst
  pos_product_cost_security/readme/DESCRIPTION.rst
  pos_product_cost_security/static/description/index.html
  pos_product_cost_security/static/src/js/models.js
  pos_product_cost_security/static/tests/tours/tour_pos_product_cost.js
  pos_product_cost_security/tests/__init__.py
  pos_product_cost_security/tests/test_pos_product_cost.py
  pos_product_cost_security/views/assets.xml
  setup/pos_product_cost_security/odoo/addons/pos_product_cost_security
  setup/pos_product_cost_security/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#791 [13.0][IMP] product_medical: Change in layout, add multiple docs
  product_medical/__manifest__.py
  product_medical/i18n/de.po
  product_medical/i18n/product_medical.pot
  product_medical/migrations/13.0.1.1.0/post-migration.py
  product_medical/models/product_template.py
  product_medical/views/product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#819 [13.0][IMP] product_medical: views for conformity categories
  product_medical/__manifest__.py
  product_medical/views/in_vitro_diagnostic.xml
  product_medical/views/medical_class.xml
  product_medical/views/medicine_category.xml
  product_medical/views/ppe_category.xml
Labels: approved, bot is merging ⏳

#813 [12.0] FIX product_pricelist_supplierinfo: _get_supplierinfo_pricelist_price when date is datetime
  product_pricelist_supplierinfo/models/product_template.py
Labels: bot is merging ⏳

#789 [13.0] [IMP] product_pricelist_direct_print: forward port of xlsx and just defined products
  oca_dependencies.txt
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/report/__init__.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.xml
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#833 [13.0][IMP] product_pricelist_direct_print: Date adjusted to the selected language
  product_pricelist_direct_print/views/report_product_pricelist.xml
Labels: approved, bot is merging ⏳

#787 [12.0] product_price_history
  product_price_history/__init__.py
  product_price_history/__manifest__.py
  product_price_history/i18n/it.po
  product_price_history/models/__init__.py
  product_price_history/models/product_price_history.py
  product_price_history/models/product_product.py
  product_price_history/models/product_template.py
  product_price_history/readme/CONTRIBUTORS.rst
  product_price_history/readme/DESCRIPTION.rst
  product_price_history/readme/HISTORY.rst
  product_price_history/readme/USAGE.rst
  product_price_history/views/product_price_history_view.xml
  setup/product_price_history/odoo/addons/product_price_history
  setup/product_price_history/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#262 [10.0] add new module to manage seasonal products
  product_life_period/README.rst
  product_life_period/__init__.py
  product_life_period/__manifest__.py
  product_life_period/i18n/fr.po
  product_life_period/i18n/product_life_period.pot
  product_life_period/models/__init__.py
  product_life_period/models/product_life_period.py
  product_life_period/models/product_template.py
  product_life_period/security/ir.model.access.csv
  product_life_period/tests/__init__.py
  product_life_period/tests/test_product_life_period.py
  product_life_period/views/product_life_period_views.xml
  product_life_period/views/product_template.xml
  setup/product_life_period/odoo/__init__.py
  setup/product_life_period/odoo/addons/__init__.py
  setup/product_life_period/odoo/addons/product_life_period
  setup/product_life_period/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#839 [13.0][FIX] product_packaging_unit_price_calculator: Tests broken when website_sale installed
  product_packaging_unit_price_calculator/tests/test_product_price_packaging_qty.py
Labels: approved, bot is merging ⏳

#817 [13.0] [MIG] product_pricelist_direct_print_website_sale: Migration to v13.0
  product_pricelist_direct_print_website_sale/README.rst
  product_pricelist_direct_print_website_sale/__init__.py
  product_pricelist_direct_print_website_sale/__manifest__.py
  product_pricelist_direct_print_website_sale/i18n/es.po
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_print_website_sale.pot
  product_pricelist_direct_print_website_sale/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_website_sale/readme/DESCRIPTION.rst
  product_pricelist_direct_print_website_sale/readme/USAGE.rst
  product_pricelist_direct_print_website_sale/static/description/icon.png
  product_pricelist_direct_print_website_sale/static/description/index.html
  product_pricelist_direct_print_website_sale/wizards/__init__.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print_website_sale/odoo/addons/product_pricelist_direct_print_website_sale
  setup/product_pricelist_direct_print_website_sale/setup.py
Labels: bot is merging ⏳

#659 [10.0][ADD] product_state_history
  product_state_history/README.rst
  product_state_history/__init__.py
  product_state_history/__manifest__.py
  product_state_history/models/__init__.py
  product_state_history/models/product_state_history.py
  product_state_history/models/product_template.py
  product_state_history/models/report_product_state_history.py
  product_state_history/readme/CONTRIBUTORS.rst
  product_state_history/readme/DESCRIPTION.rst
  product_state_history/readme/USAGE.rst
  product_state_history/report/report_product_state_history.xml
  product_state_history/security/product_state_history.xml
  product_state_history/static/description/icon.png
  product_state_history/static/description/index.html
  product_state_history/tests/__init__.py
  product_state_history/tests/common.py
  product_state_history/tests/test_product_state_history.py
  product_state_history/views/product_state_history.xml
  product_state_history/views/product_template.xml
  product_state_history/wizards/__init__.py
  product_state_history/wizards/product_state_history_wizard.py
  product_state_history/wizards/product_state_history_wizard.xml
  setup/product_state_history/.eggs/README.txt
  setup/product_state_history/odoo/__init__.py
  setup/product_state_history/odoo/addons/__init__.py
  setup/product_state_history/odoo/addons/product_state_history
  setup/product_state_history/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
