Repository OCA/product-attribute, pull requests merged in 2022-01, with the labels that each got.

#979 [14.0][MIG]product_net_weight
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/readme/CONTRIBUTORS.rst
  product_net_weight/readme/DESCRIPTION.rst
  product_net_weight/readme/ROADMAP.rst
  product_net_weight/readme/USAGE.rst
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
  setup/product_net_weight/odoo/addons/product_net_weight
  setup/product_net_weight/setup.py
Labels: approved, bot is merging ⏳

#964 [15.0] [MIG] product_cost_security
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_product.py
  product_cost_security/models/product_template.py
  product_cost_security/readme/CONFIGURE.rst
  product_cost_security/readme/CONTRIBUTORS.rst
  product_cost_security/readme/DESCRIPTION.rst
  product_cost_security/readme/USAGE.rst
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/views/product_views.xml
  setup/product_cost_security/odoo/addons/product_cost_security
  setup/product_cost_security/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#944 [14.0][FW] product_assortment: multiple ports from 13.0
  product_assortment/models/ir_filters.py
  product_assortment/static/description/icon.png
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
Labels: enhancement, needs review, bot is merging ⏳

#973 [14.0][MIG] product_variant_attribute_name_manager: Migration to 14.0
  product_variant_attribute_name_manager/README.rst
  product_variant_attribute_name_manager/__init__.py
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/i18n/product_variant_attribute_name_manager.pot
  product_variant_attribute_name_manager/models/__init__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/static/description/icon.png
  product_variant_attribute_name_manager/static/description/index.html
  product_variant_attribute_name_manager/tests/__init__.py
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
  setup/product_variant_attribute_name_manager/odoo/addons/product_variant_attribute_name_manager
  setup/product_variant_attribute_name_manager/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#982 [14.0][MIG] product category type
  product_category_type/README.rst
  product_category_type/__init__.py
  product_category_type/__manifest__.py
  product_category_type/demo/product_category.xml
  product_category_type/i18n/product_category_type.pot
  product_category_type/models/__init__.py
  product_category_type/models/product_category.py
  product_category_type/models/product_template.py
  product_category_type/readme/CONTRIBUTORS.rst
  product_category_type/readme/DESCRIPTION.rst
  product_category_type/static/description/icon.png
  product_category_type/static/description/index.html
  product_category_type/static/description/product_category_tree.png
  product_category_type/static/description/product_template_form.png
  product_category_type/views/product_category.xml
  setup/product_category_type/odoo/addons/product_category_type
  setup/product_category_type/setup.py
Labels: approved, bot is merging ⏳

#925 [14.0] Add product_status
  product_status/README.rst
  product_status/__init__.py
  product_status/__manifest__.py
  product_status/data/function_deactive_default_product_state_data.xml
  product_status/data/product_state_data.xml
  product_status/models/__init__.py
  product_status/models/product.py
  product_status/models/product_state.py
  product_status/models/product_template.py
  product_status/readme/CONTRIBUTORS.rst
  product_status/readme/CREDITS.rst
  product_status/readme/DESCRIPTION.rst
  product_status/readme/ROADMAP.rst
  product_status/static/description/index.html
  product_status/tests/__init__.py
  product_status/tests/test_product_status.py
  product_status/views/product_views.xml
  setup/product_status/odoo/addons/product_status
  setup/product_status/setup.py
Labels: bot is merging ⏳

#977 [FIX] product_pricelist_supplierinfo: override min quantity
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_template.py
Labels: approved, ready to merge, bot is merging ⏳

#989 [14.0] product_total_weight_from_packaging: manifest/readme fixes
  product_total_weight_from_packaging/__manifest__.py
  product_total_weight_from_packaging/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#957 [FIX] product_packaging_dimension: use integer instead of float
  product_packaging_dimension/migrations/14.0.1.0.0/pre-migrate.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/tests/test_packaging_volume.py
Labels: bug, bot is merging ⏳

#974 [13.0][ADD]product_supplierinfo_archive
  product_supplierinfo_archive/__init__.py
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/models/__init__.py
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/readme/CONTRIBUTORS.rst
  product_supplierinfo_archive/readme/DESCRIPTION.rst
  product_supplierinfo_archive/readme/USAGE.rst
  setup/product_supplierinfo_archive/odoo/addons/product_supplierinfo_archive
  setup/product_supplierinfo_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1000 [14.0][MIG] product_pricelist_supplierinfo: Migration to 14.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/CONFIGURE.rst
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.rst
  product_pricelist_supplierinfo/readme/DESCRIPTION.rst
  product_pricelist_supplierinfo/readme/INSTALL.rst
  product_pricelist_supplierinfo/readme/ROADMAP.rst
  product_pricelist_supplierinfo/readme/USAGE.rst
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
  setup/product_pricelist_supplierinfo/odoo/addons/product_pricelist_supplierinfo
  setup/product_pricelist_supplierinfo/setup.py
Labels: bot is merging ⏳

#985 [15.0] [MIG] product_code_mandatory
  product_code_mandatory/README.rst
  product_code_mandatory/__init__.py
  product_code_mandatory/__manifest__.py
  product_code_mandatory/data/product_code_seq.xml
  product_code_mandatory/i18n/fr.po
  product_code_mandatory/i18n/fr_FR.po
  product_code_mandatory/i18n/product_code_mandatory.pot
  product_code_mandatory/i18n/pt.po
  product_code_mandatory/models/__init__.py
  product_code_mandatory/models/product.py
  product_code_mandatory/readme/CONTRIBUTORS.rst
  product_code_mandatory/readme/DESCRIPTION.rst
  product_code_mandatory/readme/USAGE.rst
  product_code_mandatory/static/description/icon.png
  product_code_mandatory/static/description/index.html
  product_code_mandatory/tests/__init__.py
  product_code_mandatory/tests/test_product_code.py
  product_code_mandatory/views/product_view.xml
  setup/product_code_mandatory/odoo/addons/product_code_mandatory
  setup/product_code_mandatory/setup.py
Labels: approved, bot is merging ⏳

#995 [15.0] [MIG] product_code_unique
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/fr.po
  product_code_unique/i18n/fr_FR.po
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/readme/CONTRIBUTORS.rst
  product_code_unique/readme/DESCRIPTION.rst
  product_code_unique/readme/ROADMAP.rst
  product_code_unique/readme/USAGE.rst
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
  setup/product_code_unique/odoo/addons/product_code_unique
  setup/product_code_unique/setup.py
Labels: approved, bot is merging ⏳

#970 [13.0][MIG] product_pricelist_button_box
  product_pricelist_button_box/README.rst
  product_pricelist_button_box/__init__.py
  product_pricelist_button_box/__manifest__.py
  product_pricelist_button_box/i18n/product_pricelist_button_box.pot
  product_pricelist_button_box/readme/CONTRIBUTORS.rst
  product_pricelist_button_box/readme/DESCRIPTION.rst
  product_pricelist_button_box/static/description/icon.png
  product_pricelist_button_box/static/description/index.html
  product_pricelist_button_box/views/product_pricelist.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#991 [13.0][IMP] product_pricelist_direct_print: Improve inheritance at excel + add new fields
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#992 [13.0][IMP] product_pricelist_direct_print_website_sale: Added new field
  product_pricelist_direct_print_website_sale/__init__.py
  product_pricelist_direct_print_website_sale/i18n/es.po
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_direct_print_website_sale.pot
  product_pricelist_direct_print_website_sale/report/__init__.py
  product_pricelist_direct_print_website_sale/report/product_pricelist_xlsx.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1004 [14.0][FIX] Fix access right issues when using actions
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_packaging_unit_price_calculator/models/product.py
  product_packaging_unit_price_calculator/models/product_pricelist.py
  product_packaging_unit_price_calculator/models/product_supplierinfo.py
  product_packaging_unit_price_calculator/wizards/product_package_price.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_state_history/models/product_template.py
Labels: approved, bot is merging ⏳
