Repository OCA/product-attribute, pull requests merged in 2022-03, with the labels that each got.

#1021 [14.0][FIX] product_supplierinfo_for_customer: Fix display base name field in pricelist item view
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/views/product_pricelist_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1020 [13.0][FIX] product_supplierinfo_for_customer: Fix display base name field in pricelist item view
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/views/product_pricelist_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1027 [FIX] #1026
  product_supplierinfo_for_customer/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#1013 [13.0][IMP] product_abc_classification: Add posibility to create a profile with fixed prices
  product_abc_classification/models/abc_classification_level.py
  product_abc_classification/models/abc_classification_profile.py
  product_abc_classification/readme/CONTRIBUTORS.rst
  product_abc_classification/readme/USAGE.rst
  product_abc_classification/views/abc_classification_view.xml
  product_abc_classification/views/product_view.xml
Labels: approved, bot is merging ⏳

#1024 [15.0][FIX] product_state: solving problem from migration
  product_state/__manifest__.py
  product_state/data/product_state_data.xml
Labels: approved, bot is merging ⏳

#1028 [14.0][FIX] product_tier_validation: error on change stage for validated product
  product_tier_validation/models/product_template.py
Labels: bot is merging ⏳

#1015 [13.0][ADD] product_abc_classification_sale: New module to classify products from sale orders
  product_abc_classification_sale/README.rst
  product_abc_classification_sale/__init__.py
  product_abc_classification_sale/__manifest__.py
  product_abc_classification_sale/migrations/13.0.1.0.0/pre-migration.py
  product_abc_classification_sale/models/__init__.py
  product_abc_classification_sale/models/abc_classification_profile.py
  product_abc_classification_sale/models/product_product.py
  product_abc_classification_sale/models/product_template.py
  product_abc_classification_sale/readme/CONTRIBUTORS.rst
  product_abc_classification_sale/readme/DESCRIPTION.rst
  product_abc_classification_sale/readme/ROADMAP.rst
  product_abc_classification_sale/readme/USAGE.rst
  product_abc_classification_sale/static/description/index.html
  product_abc_classification_sale/tests/__init__.py
  product_abc_classification_sale/tests/test_sale_product_classification.py
  product_abc_classification_sale/tests/test_sale_product_classification_common.py
  product_abc_classification_sale/views/product_views.xml
  setup/product_abc_classification_sale/odoo/addons/product_abc_classification_sale
  setup/product_abc_classification_sale/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#1029 [MIG] product_template_tags: Migration to 15.0
  product_template_tags/README.rst
  product_template_tags/__init__.py
  product_template_tags/__manifest__.py
  product_template_tags/i18n/de.po
  product_template_tags/i18n/es.po
  product_template_tags/i18n/fr.po
  product_template_tags/i18n/hr.po
  product_template_tags/i18n/it.po
  product_template_tags/i18n/nl.po
  product_template_tags/i18n/nl_NL.po
  product_template_tags/i18n/product_template_tags.pot
  product_template_tags/i18n/sl.po
  product_template_tags/models/__init__.py
  product_template_tags/models/product_template.py
  product_template_tags/models/product_template_tag.py
  product_template_tags/readme/CONFIGURE.rst
  product_template_tags/readme/CONTRIBUTORS.rst
  product_template_tags/readme/DESCRIPTION.rst
  product_template_tags/readme/USAGE.rst
  product_template_tags/security/product_template_rule.xml
  product_template_tags/security/product_template_tag.xml
  product_template_tags/static/description/icon.png
  product_template_tags/static/description/index.html
  product_template_tags/tests/__init__.py
  product_template_tags/tests/test_product_template_tags.py
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
  product_template_tags/views/product_template_tag.xml
  setup/product_template_tags/odoo/addons/product_template_tags
  setup/product_template_tags/setup.py
Labels: approved, migration, bot is merging ⏳

#1031 [MIG] sale_product_template_tags: Migration to 15.0
  sale_product_template_tags/README.rst
  sale_product_template_tags/__init__.py
  sale_product_template_tags/__manifest__.py
  sale_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/sale_product_template_tags.pot
  sale_product_template_tags/readme/CONTRIBUTORS.rst
  sale_product_template_tags/readme/DESCRIPTION.rst
  sale_product_template_tags/static/description/icon.png
  sale_product_template_tags/static/description/index.html
  sale_product_template_tags/views/product_template_tag.xml
  setup/sale_product_template_tags/odoo/addons/sale_product_template_tags
  setup/sale_product_template_tags/setup.py
Labels: approved, bot is merging ⏳

#1034 [FIX] fix missing dependency
  product_supplierinfo_for_customer/__manifest__.py
Labels: approved, bot is merging ⏳

#1035 [13.0][OU-FIX] product_abc_classification_sale: migration script
  product_abc_classification_sale/migrations/13.0.1.0.0/post-migration.py
  product_abc_classification_sale/migrations/13.0.1.0.0/pre-migration.py
  product_abc_classification_sale/models/abc_classification_profile.py
Labels: approved, bot is merging ⏳

#1023 [ADD] product_pricelist_direct_print_company_group: New module
  oca_dependencies.txt
  product_pricelist_direct_print_company_group/README.rst
  product_pricelist_direct_print_company_group/__init__.py
  product_pricelist_direct_print_company_group/__manifest__.py
  product_pricelist_direct_print_company_group/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_company_group/readme/DESCRIPTION.rst
  product_pricelist_direct_print_company_group/readme/USAGE.rst
  product_pricelist_direct_print_company_group/static/description/index.html
  product_pricelist_direct_print_company_group/wizards/__init__.py
  product_pricelist_direct_print_company_group/wizards/product_pricelist_print.py
  setup/product_pricelist_direct_print_company_group/odoo/addons/product_pricelist_direct_print_company_group
  setup/product_pricelist_direct_print_company_group/setup.py
Labels: approved, bot is merging ⏳

#1025 [13.0][IMP]product_attribute_value_menu: Products related
  product_attribute_value_menu/__init__.py
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/models/__init__.py
  product_attribute_value_menu/models/product_attribute_value.py
  product_attribute_value_menu/views/product_attribute_value.xml
Labels: enhancement, approved, bot is merging ⏳

#960 [15.0][MIG] product_packaging_type
  product_packaging_type/README.rst
  product_packaging_type/__init__.py
  product_packaging_type/__manifest__.py
  product_packaging_type/data/product_packaging_type.xml
  product_packaging_type/i18n/es.po
  product_packaging_type/i18n/nl.po
  product_packaging_type/i18n/product_packaging_type.pot
  product_packaging_type/models/__init__.py
  product_packaging_type/models/product_packaging_type.py
  product_packaging_type/readme/CONTRIBUTORS.rst
  product_packaging_type/readme/CREDITS.rst
  product_packaging_type/readme/DESCRIPTION.rst
  product_packaging_type/readme/USAGE.rst
  product_packaging_type/security/ir.model.access.csv
  product_packaging_type/static/description/icon.png
  product_packaging_type/static/description/index.html
  product_packaging_type/views/product_packaging_type_view.xml
  product_packaging_type/views/product_packaging_view.xml
  setup/product_packaging_type/odoo/addons/product_packaging_type
  setup/product_packaging_type/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1040 [14.0][IMP] product_pricelist_direct_print: Improve inheritance on get_last_ordered_products_to_print
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: approved, bot is merging ⏳
