Repository OCA/product-attribute, pull requests merged in 2022-09, with the labels that each got.

#1128 [15.0][MIG] product_attribute_value_menu
  product_attribute_value_menu/README.rst
  product_attribute_value_menu/__init__.py
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/i18n/it.po
  product_attribute_value_menu/i18n/product_attribute_value_menu.pot
  product_attribute_value_menu/models/__init__.py
  product_attribute_value_menu/models/product_attribute_value.py
  product_attribute_value_menu/readme/CONFIGURE.rst
  product_attribute_value_menu/readme/CONTRIBUTORS.rst
  product_attribute_value_menu/readme/DESCRIPTION.rst
  product_attribute_value_menu/readme/USAGE.rst
  product_attribute_value_menu/static/description/icon.png
  product_attribute_value_menu/static/description/index.html
  product_attribute_value_menu/views/product_attribute_value_views.xml
  product_attribute_value_menu/views/product_template_attribute_value_views.xml
  setup/product_attribute_value_menu/odoo/addons/product_attribute_value_menu
  setup/product_attribute_value_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1138 [14.0][FIX] product_supplierinfo_for_customer: fix #986
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/views/product_view.xml
Labels: approved, bot is merging ⏳

#1051 Updated from template - Switch to Github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  product_video_link/__manifest__.py
Labels: enhancement, bot is merging ⏳

#949 [14.0][MIG]product_restricted_type: Migration to 14.0
  product_restricted_type/README.rst
  product_restricted_type/__init__.py
  product_restricted_type/__manifest__.py
  product_restricted_type/i18n/ca.po
  product_restricted_type/i18n/es.po
  product_restricted_type/i18n/product_restricted_type.pot
  product_restricted_type/models/__init__.py
  product_restricted_type/models/product.py
  product_restricted_type/models/product_template.py
  product_restricted_type/readme/CONTRIBUTORS.rst
  product_restricted_type/readme/DESCRIPTION.rst
  product_restricted_type/readme/USAGE.rst
  product_restricted_type/static/description/icon.png
  product_restricted_type/static/description/index.html
  product_restricted_type/tests/__init__.py
  product_restricted_type/tests/test_product_restricted_type.py
  product_restricted_type/views/product_views.xml
  setup/product_restricted_type/odoo/addons/product_restricted_type
  setup/product_restricted_type/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, stale

#1142 [14.0][ADD] product_supplierinfo_stock_picking_type: New addon.
  product_supplierinfo_stock_picking_type/README.rst
  product_supplierinfo_stock_picking_type/__init__.py
  product_supplierinfo_stock_picking_type/__manifest__.py
  product_supplierinfo_stock_picking_type/i18n/es.po
  product_supplierinfo_stock_picking_type/i18n/product_supplierinfo_stock_picking_type.pot
  product_supplierinfo_stock_picking_type/models/__init__.py
  product_supplierinfo_stock_picking_type/models/product_product.py
  product_supplierinfo_stock_picking_type/models/product_supplierinfo.py
  product_supplierinfo_stock_picking_type/models/purchase_order.py
  product_supplierinfo_stock_picking_type/readme/CONFIGURE.rst
  product_supplierinfo_stock_picking_type/readme/CONTRIBUTORS.rst
  product_supplierinfo_stock_picking_type/readme/DESCRIPTION.rst
  product_supplierinfo_stock_picking_type/readme/USAGE.rst
  product_supplierinfo_stock_picking_type/static/description/icon.png
  product_supplierinfo_stock_picking_type/static/description/index.html
  product_supplierinfo_stock_picking_type/tests/__init__.py
  product_supplierinfo_stock_picking_type/tests/test_product_supplierinfo_stock_picking_type.py
  product_supplierinfo_stock_picking_type/views/product_supplierinfo_view.xml
  setup/product_supplierinfo_stock_picking_type/odoo/addons/product_supplierinfo_stock_picking_type
  setup/product_supplierinfo_stock_picking_type/setup.py
Labels: needs review, approved, bot is merging ⏳

#1144 [15.0][FIX] product_attribute_value_menu: deprecated use of <act_window>
  product_attribute_value_menu/views/product_attribute_value_views.xml
Labels: bot is merging ⏳

#1041 [14.0][MIG] product_pricelist_direct_print_company_group: Migration to 14.0
  product_pricelist_direct_print_company_group/README.rst
  product_pricelist_direct_print_company_group/__init__.py
  product_pricelist_direct_print_company_group/__manifest__.py
  product_pricelist_direct_print_company_group/i18n/product_pricelist_direct_print_company_group.pot
  product_pricelist_direct_print_company_group/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_company_group/readme/DESCRIPTION.rst
  product_pricelist_direct_print_company_group/readme/USAGE.rst
  product_pricelist_direct_print_company_group/static/description/icon.png
  product_pricelist_direct_print_company_group/static/description/index.html
  product_pricelist_direct_print_company_group/wizards/__init__.py
  product_pricelist_direct_print_company_group/wizards/product_pricelist_print.py
  setup/product_pricelist_direct_print_company_group/odoo/addons/product_pricelist_direct_print_company_group
  setup/product_pricelist_direct_print_company_group/setup.py
Labels: bot is merging ⏳

#1140 [15.0][MIG] product_restricted_type: Migration to 15.0
  product_restricted_type/README.rst
  product_restricted_type/__init__.py
  product_restricted_type/__manifest__.py
  product_restricted_type/i18n/ca.po
  product_restricted_type/i18n/es.po
  product_restricted_type/i18n/product_restricted_type.pot
  product_restricted_type/models/__init__.py
  product_restricted_type/models/product.py
  product_restricted_type/models/product_template.py
  product_restricted_type/readme/CONTRIBUTORS.rst
  product_restricted_type/readme/DESCRIPTION.rst
  product_restricted_type/readme/USAGE.rst
  product_restricted_type/static/description/icon.png
  product_restricted_type/static/description/index.html
  product_restricted_type/tests/__init__.py
  product_restricted_type/tests/test_product_restricted_type.py
  product_restricted_type/views/product_views.xml
  setup/product_restricted_type/odoo/addons/product_restricted_type
  setup/product_restricted_type/setup.py
Labels: bot is merging ⏳

#1150 [13.0][IMP] product_template_tags: Show tags in tree view (templates and variants)
  product_template_tags/README.rst
  product_template_tags/__manifest__.py
  product_template_tags/readme/USAGE.rst
  product_template_tags/static/description/index.html
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
Labels: approved, bot is merging ⏳
