Repository OCA/product-attribute, pull requests merged in 2022-04, with the labels that each got.

#935 [14.0][IMP] product_profile: refactor to improve inheritance
  product_profile/models/product_profile.py
Labels: needs fixing, approved, bot is merging ⏳

#980 [MIG] product_manufacturer: Migration to 15.0
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_product.py
  product_manufacturer/models/product_template.py
  product_manufacturer/readme/CONTRIBUTORS.rst
  product_manufacturer/readme/DESCRIPTION.rst
  product_manufacturer/static/description/icon.png
  product_manufacturer/static/description/index.html
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
  setup/product_manufacturer/odoo/addons/product_manufacturer
  setup/product_manufacturer/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1056 [IMP] product_supplier_info_for_customer: Promote to stable
  product_supplierinfo_for_customer/__manifest__.py
Labels: approved, bot is merging ⏳

#1060 [14.0][IMP] product_supplier_info_for_customer: Promote to stable
  product_supplierinfo_for_customer/__manifest__.py
Labels: approved, bot is merging ⏳

#857 [14.0][MIG] product_multi_image
  product_multi_image/README.rst
  product_multi_image/__init__.py
  product_multi_image/__manifest__.py
  product_multi_image/hooks.py
  product_multi_image/i18n/es.po
  product_multi_image/i18n/product_multi_image.pot
  product_multi_image/images/db.png
  product_multi_image/images/file.png
  product_multi_image/images/product.png
  product_multi_image/images/url.png
  product_multi_image/models/__init__.py
  product_multi_image/models/image.py
  product_multi_image/models/product_product.py
  product_multi_image/models/product_template.py
  product_multi_image/readme/CONFIGURE.rst
  product_multi_image/readme/CONTRIBUTORS.rst
  product_multi_image/readme/CREDITS.rst
  product_multi_image/readme/DESCRIPTION.rst
  product_multi_image/readme/INSTALL.rst
  product_multi_image/readme/ROADMAP.rst
  product_multi_image/static/description/icon.png
  product_multi_image/static/description/icon.svg
  product_multi_image/static/description/index.html
  product_multi_image/tests/__init__.py
  product_multi_image/tests/test_product_multi_image.py
  product_multi_image/views/image_view.xml
  product_multi_image/views/product_template_view.xml
  setup/product_multi_image/odoo/addons/product_multi_image
  setup/product_multi_image/setup.py
Labels: needs review, needs fixing, approved, migration, ready to merge, bot is merging ⏳

#1068 [14.0][FIX] product_weight typo error
  product_weight/wizard/product_weight_update.py
Labels: approved, bot is merging ⏳
