Repository OCA/product-attribute, pull requests merged in 2022-05, with the labels that each got.

#1072 [14.0] [IMP] product_pricelist_direct_print: fw-port of changes applied on 13.0 to 14.0
  oca_dependencies.txt
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/report/__init__.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.xml
  product_pricelist_direct_print/security/ir.model.access.csv
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1075 [13.0][FIX] product_secondary_unit: Don't alter previous quantity
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#1054 14.0 mig product custom info
  product_custom_info/README.rst
  product_custom_info/__init__.py
  product_custom_info/__manifest__.py
  product_custom_info/i18n/ca.po
  product_custom_info/i18n/es.po
  product_custom_info/i18n/product_custom_info.pot
  product_custom_info/i18n/pt.po
  product_custom_info/models/__init__.py
  product_custom_info/models/product_product.py
  product_custom_info/models/product_template.py
  product_custom_info/readme/CONFIGURE.rst
  product_custom_info/readme/CONTRIBUTORS.rst
  product_custom_info/readme/DESCRIPTION.rst
  product_custom_info/readme/INSTALL.rst
  product_custom_info/readme/USAGE.rst
  product_custom_info/static/description/icon.png
  product_custom_info/tests/__init__.py
  product_custom_info/tests/test_product_custom_info.py
  product_custom_info/views/product_product_view.xml
  product_custom_info/views/product_template_view.xml
  setup/product_custom_info/odoo/addons/product_custom_info
  setup/product_custom_info/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#841 [14.0][MIG]product pricelist assortment
  product_pricelist_assortment/README.rst
  product_pricelist_assortment/__init__.py
  product_pricelist_assortment/__manifest__.py
  product_pricelist_assortment/data/ir_cron.xml
  product_pricelist_assortment/i18n/ca.po
  product_pricelist_assortment/i18n/es.po
  product_pricelist_assortment/i18n/product_pricelist_assortment.pot
  product_pricelist_assortment/models/__init__.py
  product_pricelist_assortment/models/product_pricelist.py
  product_pricelist_assortment/models/product_pricelist_assortment_item.py
  product_pricelist_assortment/models/product_pricelist_item.py
  product_pricelist_assortment/readme/CONTRIBUTORS.rst
  product_pricelist_assortment/readme/DESCRIPTION.rst
  product_pricelist_assortment/security/product_pricelist_assortment_item.xml
  product_pricelist_assortment/static/description/icon.png
  product_pricelist_assortment/static/description/index.html
  product_pricelist_assortment/tests/__init__.py
  product_pricelist_assortment/tests/test_pricelist_assortment.py
  product_pricelist_assortment/views/product_pricelist.xml
  product_pricelist_assortment/views/product_pricelist_assortment_item.xml
  product_pricelist_assortment/views/product_pricelist_item.xml
  setup/product_pricelist_assortment/odoo/addons/product_pricelist_assortment
  setup/product_pricelist_assortment/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#971 [15.0][MIG] product_secondary_unit
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/es_MX.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
  setup/product_secondary_unit/odoo/addons/product_secondary_unit
  setup/product_secondary_unit/setup.py
Labels: needs review, migration, bot is merging ⏳

#1055 [13.0][IMP] product_restricted_type: apply onchanges on product variant
  product_restricted_type/models/product.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1077 product_main_supplierinfo: fix default sellers for variant
  product_main_supplierinfo/models/product_product.py
  product_main_supplierinfo/tests/test_product_main_supplier.py
Labels: approved, ready to merge, bot is merging ⏳

#1083 [15.0][MIG] product_net_weight
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/readme/CONTRIBUTORS.rst
  product_net_weight/readme/DESCRIPTION.rst
  product_net_weight/readme/ROADMAP.rst
  product_net_weight/readme/USAGE.rst
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
  setup/product_net_weight/odoo/addons/product_net_weight
  setup/product_net_weight/setup.py
Labels: bot is merging ⏳

#1074 [IMP] product_state (copy=False)
  product_state/models/product_template.py
  product_state/tests/test_product_state.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
