Repository OCA/product-attribute, pull requests merged in 2022-08, with the labels that each got.

#981 [15.0][MIG] product_variant_attribute_name_manager: Migration to 15.0
  product_variant_attribute_name_manager/README.rst
  product_variant_attribute_name_manager/__init__.py
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/i18n/product_variant_attribute_name_manager.pot
  product_variant_attribute_name_manager/models/__init__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/static/description/icon.png
  product_variant_attribute_name_manager/static/description/index.html
  product_variant_attribute_name_manager/tests/__init__.py
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
  setup/product_variant_attribute_name_manager/odoo/addons/product_variant_attribute_name_manager
  setup/product_variant_attribute_name_manager/setup.py
Labels: approved, bot is merging ⏳

#1106 [15.0] [MIG] product_supplierinfo_archive
  product_supplierinfo_archive/README.rst
  product_supplierinfo_archive/__init__.py
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/i18n/product_supplierinfo_archive.pot
  product_supplierinfo_archive/models/__init__.py
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/readme/CONTRIBUTORS.rst
  product_supplierinfo_archive/readme/DESCRIPTION.rst
  product_supplierinfo_archive/readme/USAGE.rst
  product_supplierinfo_archive/static/description/icon.png
  product_supplierinfo_archive/static/description/index.html
  product_supplierinfo_archive/views/product_views.xml
  setup/product_supplierinfo_archive/odoo/addons/product_supplierinfo_archive
  setup/product_supplierinfo_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1112 [13.0] [ADD] product_category_description
  product_category_description/README.rst
  product_category_description/__init__.py
  product_category_description/__manifest__.py
  product_category_description/models/__init__.py
  product_category_description/models/product_category.py
  product_category_description/readme/CONTRIBUTORS.rst
  product_category_description/readme/DESCRIPTION.rst
  product_category_description/static/description/icon.png
  product_category_description/static/description/index.html
  product_category_description/views/product_category.xml
  setup/product_category_description/odoo/addons/product_category_description
  setup/product_category_description/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1131 [13.0][IMP] product_dimension_volumetric_weight + product_dimension: Add development_status to Production/Stable
  product_dimension/__manifest__.py
  product_dimension_volumetric_weight/__manifest__.py
Labels: approved, bot is merging ⏳

#1070 [15.0][MIG] product_multi_image
  product_multi_image/README.rst
  product_multi_image/__init__.py
  product_multi_image/__manifest__.py
  product_multi_image/hooks.py
  product_multi_image/i18n/es.po
  product_multi_image/i18n/product_multi_image.pot
  product_multi_image/images/db.png
  product_multi_image/images/file.png
  product_multi_image/images/product.png
  product_multi_image/images/url.png
  product_multi_image/models/__init__.py
  product_multi_image/models/image.py
  product_multi_image/models/product_product.py
  product_multi_image/models/product_template.py
  product_multi_image/readme/CONFIGURE.rst
  product_multi_image/readme/CONTRIBUTORS.rst
  product_multi_image/readme/CREDITS.rst
  product_multi_image/readme/DESCRIPTION.rst
  product_multi_image/readme/INSTALL.rst
  product_multi_image/readme/ROADMAP.rst
  product_multi_image/static/description/icon.png
  product_multi_image/static/description/icon.svg
  product_multi_image/static/description/index.html
  product_multi_image/tests/__init__.py
  product_multi_image/tests/test_product_multi_image.py
  product_multi_image/views/image_view.xml
  product_multi_image/views/product_template_view.xml
  setup/product_multi_image/odoo/addons/product_multi_image
  setup/product_multi_image/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1132 [14.0][IMP] product_attribute_value_menu: merge module product_attribute_value_menu from V13
  product_attribute_value_menu/README.rst
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/models/__init__.py
  product_attribute_value_menu/models/product_attribute_value.py
  product_attribute_value_menu/readme/CONTRIBUTORS.rst
  product_attribute_value_menu/readme/DESCRIPTION.rst
  product_attribute_value_menu/readme/USAGE.rst
  product_attribute_value_menu/views/product_attribute_value_views.xml
  product_attribute_value_menu/views/product_template_attribute_value_views.xml
Labels: approved, bot is merging ⏳
