Repository OCA/product-attribute, pull requests merged in 2022-02, with the labels that each got.

#1006 [13.0][FIX] product_abc_classfication: fix _compute_abc_classification method using the accumulated value
  product_abc_classification/models/abc_classification_profile.py
Labels: approved, bot is merging ⏳

#965 [15.0] [MIG] product_dimension
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/readme/CONTRIBUTORS.rst
  product_dimension/readme/DESCRIPTION.rst
  product_dimension/readme/HISTORY.rst
  product_dimension/readme/USAGE.rst
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/views/product_view.xml
  setup/product_dimension/odoo/addons/product_dimension
  setup/product_dimension/setup.py
Labels: needs review, migration

#1010 [13.0][IMP] product_abc_classification: several improvements
  product_abc_classification/i18n/product_abc_classification.pot
  product_abc_classification/models/abc_classification_level.py
  product_abc_classification/models/abc_classification_profile.py
  product_abc_classification/views/abc_classification_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#956 [FIX] product_category_type : add maintainers and fix image reference in description.
  product_category_type/__manifest__.py
  product_category_type/readme/DESCRIPTION.rst
Labels: approved, ready to merge, bot is merging ⏳

#999 [13.0][IMP] stock_account_product_cost_security: improved security
  stock_account_product_cost_security/__init__.py
  stock_account_product_cost_security/models/__init__.py
  stock_account_product_cost_security/models/product_template.py
  stock_account_product_cost_security/views/product_views.xml
Labels: approved, bot is merging ⏳

#996 [13.0][MIG]product_category_code: backport from 14.0
  product_category_code/README.rst
  product_category_code/__init__.py
  product_category_code/__manifest__.py
  product_category_code/i18n/product_category_code.pot
  product_category_code/models/__init__.py
  product_category_code/models/product_category.py
  product_category_code/readme/CONTRIBUTORS.rst
  product_category_code/readme/DESCRIPTION.rst
  product_category_code/static/description/icon.png
  product_category_code/static/description/index.html
  product_category_code/tests/__init__.py
  product_category_code/tests/test_category_code.py
  product_category_code/views/product_category.xml
  setup/product_category_code/odoo/addons/product_category_code
  setup/product_category_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1012 [13.0][FIX]product_supplierinfo_archive
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/views/product_views.xml
Labels: approved, bot is merging ⏳

#978 [MIG][15.0]: product_category_product_link
  product_category_product_link/README.rst
  product_category_product_link/__init__.py
  product_category_product_link/__manifest__.py
  product_category_product_link/i18n/product_category_product_link.pot
  product_category_product_link/models/__init__.py
  product_category_product_link/models/product_category.py
  product_category_product_link/models/product_template.py
  product_category_product_link/readme/CONTRIBUTORS.rst
  product_category_product_link/readme/DESCRIPTION.rst
  product_category_product_link/static/description/icon.png
  product_category_product_link/static/description/index.html
  setup/product_category_product_link/odoo/addons/product_category_product_link
  setup/product_category_product_link/setup.py
Labels: approved, bot is merging ⏳

#969 [14.0][MIG] product_category_active
  product_category_active/README.rst
  product_category_active/__init__.py
  product_category_active/__manifest__.py
  product_category_active/i18n/ca.po
  product_category_active/i18n/es.po
  product_category_active/i18n/product_category_active.pot
  product_category_active/i18n/pt.po
  product_category_active/models/__init__.py
  product_category_active/models/product_category.py
  product_category_active/readme/CONTRIBUTORS.rst
  product_category_active/readme/DESCRIPTION.rst
  product_category_active/readme/ROADMAP.rst
  product_category_active/readme/USAGE.rst
  product_category_active/static/description/icon.png
  product_category_active/static/description/index.html
  product_category_active/tests/__init__.py
  product_category_active/tests/test_product_category_active.py
  product_category_active/views/product_views.xml
  setup/product_category_active/odoo/addons/product_category_active
  setup/product_category_active/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#997 [13.0][ADD]product_attribute_value_menu
  product_attribute_value_menu/__init__.py
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/readme/CONTRIBUTORS.rst
  product_attribute_value_menu/readme/DESCRIPTION.rst
  product_attribute_value_menu/readme/USAGE.rst
  product_attribute_value_menu/views/product_attribute_value.xml
  setup/product_attribute_value_menu/odoo/addons/product_attribute_value_menu
  setup/product_attribute_value_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1022 [IMP] product_pricelist_direct_print: Improve inheritance on get_last_ordered_products_to_print
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: approved, bot is merging ⏳

#1019 [14.0][FIX] product_status: status bar not clickable
  product_status/__manifest__.py
  product_status/data/ir_cron.xml
  product_status/models/product_state.py
  product_status/tests/test_product_status.py
  product_status/views/product_views.xml
Labels: approved, bot is merging ⏳
