Repository OCA/product-attribute, pull requests merged in 2022-10, with the labels that each got.

#1155 [14.0][FIX] Some fixes for copier / tests
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
Labels: bot is merging ⏳

#1156 [13.0][IMP] stock_account_product_cost_security: additional permission
  stock_account_product_cost_security/README.rst
  stock_account_product_cost_security/__manifest__.py
  stock_account_product_cost_security/data/product_cost_security.xml
  stock_account_product_cost_security/migrations/13.0.3.0.0/post-migrate.py
  stock_account_product_cost_security/readme/CONFIGURE.rst
  stock_account_product_cost_security/readme/CONTRIBUTORS.rst
  stock_account_product_cost_security/readme/DESCRIPTION.rst
  stock_account_product_cost_security/readme/INSTALL.rst
  stock_account_product_cost_security/static/description/index.html
  stock_account_product_cost_security/views/product_views.xml
  stock_account_product_cost_security/wizard/stock_change_standard_price_views.xml
Labels: approved, bot is merging ⏳

#1167 [16.0] [MIG] product_multi_category: Migration to 16.0
  product_multi_category/README.rst
  product_multi_category/__init__.py
  product_multi_category/__manifest__.py
  product_multi_category/i18n/ca.po
  product_multi_category/i18n/de.po
  product_multi_category/i18n/es.po
  product_multi_category/i18n/fr.po
  product_multi_category/i18n/fr_BE.po
  product_multi_category/i18n/hr.po
  product_multi_category/i18n/nl_NL.po
  product_multi_category/i18n/product_multi_category.pot
  product_multi_category/i18n/sv.po
  product_multi_category/i18n/tr.po
  product_multi_category/models/__init__.py
  product_multi_category/models/product.py
  product_multi_category/readme/CONTRIBUTORS.rst
  product_multi_category/readme/DESCRIPTION.rst
  product_multi_category/static/description/icon.png
  product_multi_category/static/description/index.html
  product_multi_category/views/product_view.xml
  setup/product_multi_category/odoo/addons/product_multi_category
  setup/product_multi_category/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1105 [14.0] [MIG] product_supplierinfo_archive
  product_supplierinfo_archive/README.rst
  product_supplierinfo_archive/__init__.py
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/i18n/product_supplierinfo_archive.pot
  product_supplierinfo_archive/models/__init__.py
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/readme/CONTRIBUTORS.rst
  product_supplierinfo_archive/readme/DESCRIPTION.rst
  product_supplierinfo_archive/readme/USAGE.rst
  product_supplierinfo_archive/static/description/icon.png
  product_supplierinfo_archive/static/description/index.html
  product_supplierinfo_archive/views/product_views.xml
  setup/product_supplierinfo_archive/odoo/addons/product_supplierinfo_archive
  setup/product_supplierinfo_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1159 [16.0] [MIG] product_code_unique
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/ca.po
  product_code_unique/i18n/de.po
  product_code_unique/i18n/fr.po
  product_code_unique/i18n/fr_FR.po
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/readme/CONTRIBUTORS.rst
  product_code_unique/readme/DESCRIPTION.rst
  product_code_unique/readme/ROADMAP.rst
  product_code_unique/readme/USAGE.rst
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
  setup/product_code_unique/odoo/addons/product_code_unique
  setup/product_code_unique/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1170 [14.0][FIX] product_logistics_uom: config settings view adjustment
  product_logistics_uom/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1158 [16.0] [MIG] product_assortment
  product_assortment/README.rst
  product_assortment/__init__.py
  product_assortment/__manifest__.py
  product_assortment/i18n/ca.po
  product_assortment/i18n/es.po
  product_assortment/i18n/it.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/readme/CONTRIBUTORS.rst
  product_assortment/readme/DESCRIPTION.rst
  product_assortment/readme/HISTORY.rst
  product_assortment/readme/USAGE.rst
  product_assortment/static/description/icon.png
  product_assortment/static/description/index.html
  product_assortment/tests/__init__.py
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
  setup/product_assortment/odoo/addons/product_assortment
  setup/product_assortment/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1162 [16.0] [MIG] product_sequence
  product_sequence/README.rst
  product_sequence/__init__.py
  product_sequence/__manifest__.py
  product_sequence/data/product_sequence.xml
  product_sequence/hooks.py
  product_sequence/i18n/ar.po
  product_sequence/i18n/bg.po
  product_sequence/i18n/bs.po
  product_sequence/i18n/ca.po
  product_sequence/i18n/cs.po
  product_sequence/i18n/da.po
  product_sequence/i18n/de.po
  product_sequence/i18n/el.po
  product_sequence/i18n/es.po
  product_sequence/i18n/es_AR.po
  product_sequence/i18n/es_CR.po
  product_sequence/i18n/es_EC.po
  product_sequence/i18n/es_MX.po
  product_sequence/i18n/es_VE.po
  product_sequence/i18n/et.po
  product_sequence/i18n/fi.po
  product_sequence/i18n/fr.po
  product_sequence/i18n/gl.po
  product_sequence/i18n/hr.po
  product_sequence/i18n/hu.po
  product_sequence/i18n/it.po
  product_sequence/i18n/ja.po
  product_sequence/i18n/lt.po
  product_sequence/i18n/mk.po
  product_sequence/i18n/mn.po
  product_sequence/i18n/nb.po
  product_sequence/i18n/nl.po
  product_sequence/i18n/pl.po
  product_sequence/i18n/product_sequence.pot
  product_sequence/i18n/pt.po
  product_sequence/i18n/pt_BR.po
  product_sequence/i18n/ro.po
  product_sequence/i18n/ru.po
  product_sequence/i18n/sl.po
  product_sequence/i18n/sr.po
  product_sequence/i18n/sv.po
  product_sequence/i18n/tr.po
  product_sequence/i18n/zh_CN.po
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_category.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/readme/CONTRIBUTORS.rst
  product_sequence/readme/DESCRIPTION.rst
  product_sequence/readme/USAGE.rst
  product_sequence/static/description/icon.png
  product_sequence/static/description/index.html
  product_sequence/tests/__init__.py
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/product_category.xml
  product_sequence/views/res_config_settings_views.xml
  setup/product_sequence/odoo/addons/product_sequence
  setup/product_sequence/setup.py
Labels: migration, bot is merging ⏳

#1151 [15.0][MIG] product_logistics_uom
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/readme/CONFIGURE.rst
  product_logistics_uom/readme/CONTRIBUTORS.rst
  product_logistics_uom/readme/CREDITS.rst
  product_logistics_uom/readme/DESCRIPTION.rst
  product_logistics_uom/readme/INSTALL.rst
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
  setup/product_logistics_uom/odoo/addons/product_logistics_uom
  setup/product_logistics_uom/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1017 [13.0][ADD] product_expiry_configurable
  product_expiry_configurable/README.rst
  product_expiry_configurable/__init__.py
  product_expiry_configurable/__manifest__.py
  product_expiry_configurable/data/product_expiry_data.xml
  product_expiry_configurable/models/__init__.py
  product_expiry_configurable/models/product_category.py
  product_expiry_configurable/models/product_template.py
  product_expiry_configurable/models/stock_production_lot.py
  product_expiry_configurable/readme/CONTRIBUTORS.rst
  product_expiry_configurable/readme/DESCRIPTION.rst
  product_expiry_configurable/static/description/icon.png
  product_expiry_configurable/static/description/index.html
  product_expiry_configurable/tests/__init__.py
  product_expiry_configurable/tests/test_product_category.py
  product_expiry_configurable/tests/test_product_template.py
  product_expiry_configurable/tests/test_stock_production_lot.py
  product_expiry_configurable/views/product_category.xml
  product_expiry_configurable/views/product_template.xml
  product_expiry_configurable/views/stock_production_lot.xml
  requirements.txt
  setup/product_expiry_configurable/odoo/addons/product_expiry_configurable
  setup/product_expiry_configurable/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1117 [15.0][MIG] product_pricelist_direct_print: Migration to 15.0
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/data/mail_template_data.xml
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONFIGURE.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/readme/DESCRIPTION.rst
  product_pricelist_direct_print/readme/USAGE.rst
  product_pricelist_direct_print/report/__init__.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/report/product_pricelist_xlsx.xml
  product_pricelist_direct_print/security/ir.model.access.csv
  product_pricelist_direct_print/static/description/icon.png
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/tests/__init__.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/__init__.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print/odoo/addons/product_pricelist_direct_print
  setup/product_pricelist_direct_print/setup.py
Labels: approved, bot is merging ⏳

#1160 [16.0] [MIG] product_logistics_uom
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/readme/CONFIGURE.rst
  product_logistics_uom/readme/CONTRIBUTORS.rst
  product_logistics_uom/readme/CREDITS.rst
  product_logistics_uom/readme/DESCRIPTION.rst
  product_logistics_uom/readme/INSTALL.rst
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
  setup/product_logistics_uom/odoo/addons/product_logistics_uom
  setup/product_logistics_uom/setup.py
Labels: needs review, migration, bot is merging ⏳

#1161 [16.0] [MIG] product_packaging_dimension
  product_packaging_dimension/README.rst
  product_packaging_dimension/__init__.py
  product_packaging_dimension/__manifest__.py
  product_packaging_dimension/i18n/ca.po
  product_packaging_dimension/i18n/es.po
  product_packaging_dimension/i18n/product_packaging_dimension.pot
  product_packaging_dimension/models/__init__.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/readme/CONTRIBUTORS.rst
  product_packaging_dimension/readme/DESCRIPTION.rst
  product_packaging_dimension/readme/ROADMAP.rst
  product_packaging_dimension/static/description/icon.png
  product_packaging_dimension/static/description/index.html
  product_packaging_dimension/tests/__init__.py
  product_packaging_dimension/tests/test_packaging_volume.py
  product_packaging_dimension/views/product_packaging.xml
  setup/product_packaging_dimension/odoo/addons/product_packaging_dimension
  setup/product_packaging_dimension/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
