Repository OCA/product-attribute, pull requests merged in 2022-11, with the labels that each got.

#1111 [14.0][FIX] product_lot_sequence: Avoid generate extra sequences on duplicates
  product_lot_sequence/models/product.py
Labels: approved, ready to merge, bot is merging ⏳

#1042 [12.0][FIX] product_lot_sequence: Avoid generate extra sequences on duplicates
  product_lot_sequence/models/product.py
Labels: approved, bot is merging ⏳

#1098 [MIG] product_net_weight: Migration to 13.0
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/readme/CONTRIBUTORS.rst
  product_net_weight/readme/DESCRIPTION.rst
  product_net_weight/readme/ROADMAP.rst
  product_net_weight/readme/USAGE.rst
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
  setup/product_net_weight/odoo/addons/product_net_weight
  setup/product_net_weight/setup.py
Labels: approved, bot is merging ⏳

#1048 [IMP] product_variant_attribute_name_manager: Add flag to allow no variant attributes to be displayed
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
Labels: approved, bot is merging ⏳

#1190 [15.0][MIG] product_pricelist_revision: Migration to 15.0
  product_pricelist_revision/README.rst
  product_pricelist_revision/__init__.py
  product_pricelist_revision/__manifest__.py
  product_pricelist_revision/i18n/ca.po
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/it.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/models/__init__.py
  product_pricelist_revision/models/pricelist.py
  product_pricelist_revision/readme/CONFIGURE.rst
  product_pricelist_revision/readme/CONTRIBUTORS.rst
  product_pricelist_revision/readme/DESCRIPTION.rst
  product_pricelist_revision/readme/USAGE.rst
  product_pricelist_revision/security/ir.model.access.csv
  product_pricelist_revision/static/description/icon.png
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/tests/__init__.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/views/pricelist_view.xml
  product_pricelist_revision/wizards/__init__.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard_view.xml
  setup/product_pricelist_revision/odoo/addons/product_pricelist_revision
  setup/product_pricelist_revision/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1195 [15.0][MIG] product_supplierinfo_revision: Migration to 15.0
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/ca.po
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/readme/CONTRIBUTORS.rst
  product_supplierinfo_revision/readme/DESCRIPTION.rst
  product_supplierinfo_revision/readme/USAGE.rst
  product_supplierinfo_revision/security/ir.model.access.csv
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
  setup/product_supplierinfo_revision/odoo/addons/product_supplierinfo_revision
  setup/product_supplierinfo_revision/setup.py
Labels: approved, bot is merging ⏳

#1201 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1197 [16.0][FIX] product_assortment unit tests: invalidate_cache() is deprecated
  product_assortment/tests/test_product_assortment.py
  product_sequence/models/product_category.py
  product_sequence/models/product_product.py
  product_sequence/tests/test_product_sequence.py
Labels: approved, bot is merging ⏳

#1202 [UPD] Copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1207 [15.0][FIX] product_secondary_unit: Change SavepointCase to TransactionCase
  product_secondary_unit/tests/test_secondary_unit_mixin.py
Labels: bot is merging ⏳

#1198 [15.0][FIX] product_manufacturer: Change SavepointCase to TransactionCase
  product_manufacturer/tests/test_product_manufacturer.py
Labels: bot is merging ⏳

#1203 [14.0] [IMP] `product_seasonality`: add indexes to speed up `find_for_product`
  product_seasonality/models/seasonal_config_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1171 [16.0] [MIG] product_category_code
  product_category_code/README.rst
  product_category_code/__init__.py
  product_category_code/__manifest__.py
  product_category_code/i18n/product_category_code.pot
  product_category_code/models/__init__.py
  product_category_code/models/product_category.py
  product_category_code/readme/CONTRIBUTORS.rst
  product_category_code/readme/DESCRIPTION.rst
  product_category_code/static/description/icon.png
  product_category_code/static/description/index.html
  product_category_code/tests/__init__.py
  product_category_code/tests/test_category_code.py
  product_category_code/views/product_category.xml
  setup/product_category_code/odoo/addons/product_category_code
  setup/product_category_code/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1210 [14.0][FIX] product_attribute_value_menu: deprecated use of <act_window>
  product_attribute_value_menu/views/product_attribute_value_views.xml
Labels: bot is merging ⏳

#1209 [14.0][FIX] product_net_weight: Fix digits parameter.
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
Labels: approved, bot is merging ⏳

#1211 [15.0][FIX] product_net_weight: Fix digits parameter.
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
Labels: bot is merging ⏳

#1168 [16.0] [MIG] product_dimension
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/readme/CONTRIBUTORS.rst
  product_dimension/readme/DESCRIPTION.rst
  product_dimension/readme/HISTORY.rst
  product_dimension/readme/USAGE.rst
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/views/product_view.xml
  setup/product_dimension/odoo/addons/product_dimension
  setup/product_dimension/setup.py
Labels: approved, migration, bot is merging ⏳

#1206 [15.0][MIG] product_pricelist_supplierinfo: Migration to 15.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/CONFIGURE.rst
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.rst
  product_pricelist_supplierinfo/readme/DESCRIPTION.rst
  product_pricelist_supplierinfo/readme/INSTALL.rst
  product_pricelist_supplierinfo/readme/ROADMAP.rst
  product_pricelist_supplierinfo/readme/USAGE.rst
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  setup/product_pricelist_supplierinfo/odoo/addons/product_pricelist_supplierinfo
  setup/product_pricelist_supplierinfo/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1212 [16.0][IMP] product_dimension: Remove onchange method to computed readonly False one / Allow to create product template with dimensions
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/tests/test_template.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳
