Repository OCA/product-attribute, pull requests merged in 2022-12, with the labels that each got.

#1219 [MIG] product_state: Migration to 16.0
  product_state/README.rst
  product_state/__init__.py
  product_state/__manifest__.py
  product_state/data/product_state_data.xml
  product_state/i18n/ca.po
  product_state/i18n/de.po
  product_state/i18n/es.po
  product_state/i18n/fr.po
  product_state/i18n/hr.po
  product_state/i18n/nl.po
  product_state/i18n/nl_NL.po
  product_state/i18n/product_state.pot
  product_state/i18n/pt.po
  product_state/i18n/sl.po
  product_state/models/__init__.py
  product_state/models/product_state.py
  product_state/models/product_template.py
  product_state/readme/CONTRIBUTORS.rst
  product_state/readme/DESCRIPTION.rst
  product_state/readme/USAGE.rst
  product_state/security/ir.model.access.csv
  product_state/static/description/icon.png
  product_state/static/description/index.html
  product_state/tests/__init__.py
  product_state/tests/test_product_state.py
  product_state/views/product_state_views.xml
  product_state/views/product_template_views.xml
  setup/product_state/odoo/addons/product_state
  setup/product_state/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1166 [16.0][MIG] product_manufacturer: Migration to 16.0
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/migrations/16.0.1.0.0/pre-migration.py
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_product.py
  product_manufacturer/models/product_template.py
  product_manufacturer/readme/CONTRIBUTORS.rst
  product_manufacturer/readme/DESCRIPTION.rst
  product_manufacturer/static/description/icon.png
  product_manufacturer/static/description/index.html
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
  requirements.txt
  setup/product_manufacturer/odoo/addons/product_manufacturer
  setup/product_manufacturer/setup.py
Labels: needs fixing, migration, bot is merging ⏳

#1066 [14.0][FIX] product_stock_state : product_template_view
  product_stock_state/views/product_template_view.xml
Labels: bot is merging ⏳

#1164 [13.0][FIX] product_supplierinfo_for_customer: Crash when the price is computed for a template instead of variant
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo_mixin.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
Labels: bot is merging ⏳

#1177 [12.0][IMP] product_pricelist_direct_print
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1130 [13.0][FIX] product_pricelist_direct_print: filter products
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: approved, bot is merging ⏳

#1146 [15.0][FIX] product_code_mandatory: align code with Odoo way to set default code
  product_code_mandatory/__init__.py
Labels: approved, bot is merging ⏳

#1145 [15.0][MIG] product_lot_sequence
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/stock_production_lot.py
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/DESCRIPTION.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  setup/product_lot_sequence/odoo/addons/product_lot_sequence
  setup/product_lot_sequence/setup.py
Labels: bot is merging ⏳

#1046 [13.0][IMP] product_pricelist_assortment: add index on assortment_item_id
  product_assortment/demo/assortments.xml
  product_pricelist_assortment/README.rst
  product_pricelist_assortment/models/product_pricelist_item.py
  product_pricelist_assortment/readme/DESCRIPTION.rst
  product_pricelist_assortment/static/description/index.html
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1044 [MIG] product_order_noname: Migration to 15.0
  product_order_noname/README.rst
  product_order_noname/__init__.py
  product_order_noname/__manifest__.py
  product_order_noname/i18n/fr.po
  product_order_noname/i18n/product_order_noname.pot
  product_order_noname/models/__init__.py
  product_order_noname/models/product.py
  product_order_noname/models/product_template.py
  product_order_noname/readme/CONTRIBUTORS.rst
  product_order_noname/readme/CREDITS.rst
  product_order_noname/readme/DESCRIPTION.rst
  product_order_noname/readme/USAGE.rst
  product_order_noname/static/description/icon.png
  product_order_noname/static/description/index.html
  setup/product_order_noname/odoo/addons/product_order_noname
  setup/product_order_noname/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1076 [FIX]product_sequence: remove dependence
  product_sequence/README.rst
  product_sequence/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1189 16.0 mig product_uom_measure_type (from V12)
  product_uom_measure_type/README.rst
  product_uom_measure_type/__init__.py
  product_uom_measure_type/__manifest__.py
  product_uom_measure_type/hooks.py
  product_uom_measure_type/i18n/fr.po
  product_uom_measure_type/i18n/product_uom_measure_type.pot
  product_uom_measure_type/models/__init__.py
  product_uom_measure_type/models/product_template.py
  product_uom_measure_type/models/uom_category.py
  product_uom_measure_type/models/uom_uom.py
  product_uom_measure_type/readme/CONTRIBUTORS.rst
  product_uom_measure_type/readme/DESCRIPTION.rst
  product_uom_measure_type/static/description/icon.png
  product_uom_measure_type/static/description/index.html
  product_uom_measure_type/views/view_product_template.xml
  product_uom_measure_type/views/view_uom_category.xml
  product_uom_measure_type/views/view_uom_uom.xml
  setup/product_uom_measure_type/odoo/addons/product_uom_measure_type
  setup/product_uom_measure_type/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1188 [15.0][IMP] product_lot_sequence: Add sequence policies
  product_lot_sequence/__manifest__.py
  product_lot_sequence/data/ir_config_parameter.xml
  product_lot_sequence/models/product.py
  product_lot_sequence/models/stock_production_lot.py
  product_lot_sequence/readme/CONFIGURATION.rst
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳
