Repository OCA/product-attribute, pull requests merged in 2022-07, with the labels that each got.

#1037 [MIG] product_sequence: Migration to 15.0
  product_sequence/README.rst
  product_sequence/__init__.py
  product_sequence/__manifest__.py
  product_sequence/data/product_sequence.xml
  product_sequence/hooks.py
  product_sequence/i18n/ar.po
  product_sequence/i18n/bg.po
  product_sequence/i18n/bs.po
  product_sequence/i18n/ca.po
  product_sequence/i18n/cs.po
  product_sequence/i18n/da.po
  product_sequence/i18n/de.po
  product_sequence/i18n/el.po
  product_sequence/i18n/es.po
  product_sequence/i18n/es_AR.po
  product_sequence/i18n/es_CR.po
  product_sequence/i18n/es_EC.po
  product_sequence/i18n/es_MX.po
  product_sequence/i18n/es_VE.po
  product_sequence/i18n/et.po
  product_sequence/i18n/fi.po
  product_sequence/i18n/fr.po
  product_sequence/i18n/gl.po
  product_sequence/i18n/hr.po
  product_sequence/i18n/hu.po
  product_sequence/i18n/it.po
  product_sequence/i18n/ja.po
  product_sequence/i18n/lt.po
  product_sequence/i18n/mk.po
  product_sequence/i18n/mn.po
  product_sequence/i18n/nb.po
  product_sequence/i18n/nl.po
  product_sequence/i18n/pl.po
  product_sequence/i18n/product_sequence.pot
  product_sequence/i18n/pt.po
  product_sequence/i18n/pt_BR.po
  product_sequence/i18n/ro.po
  product_sequence/i18n/ru.po
  product_sequence/i18n/sl.po
  product_sequence/i18n/sr.po
  product_sequence/i18n/sv.po
  product_sequence/i18n/tr.po
  product_sequence/i18n/zh_CN.po
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_category.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/readme/CONTRIBUTORS.rst
  product_sequence/readme/DESCRIPTION.rst
  product_sequence/readme/USAGE.rst
  product_sequence/static/description/icon.png
  product_sequence/static/description/index.html
  product_sequence/tests/__init__.py
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/product_category.xml
  product_sequence/views/res_config_settings_views.xml
  setup/product_sequence/odoo/addons/product_sequence
  setup/product_sequence/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1081 [13.0][IMP] product_assortment: Add blacklist product domain to exclude some products
  product_assortment/README.rst
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/ir_filters.py
  product_assortment/readme/CONTRIBUTORS.rst
  product_assortment/static/description/index.html
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
Labels: approved, bot is merging ⏳

#1103 [15.0][MIG] product_pricelist_by_contact: Migration to 15.0
  product_pricelist_by_contact/README.rst
  product_pricelist_by_contact/__init__.py
  product_pricelist_by_contact/__manifest__.py
  product_pricelist_by_contact/i18n/product_pricelist_by_contact.pot
  product_pricelist_by_contact/readme/CONTRIBUTORS.rst
  product_pricelist_by_contact/readme/DESCRIPTION.rst
  product_pricelist_by_contact/readme/ROADMAP.rst
  product_pricelist_by_contact/readme/USAGE.rst
  product_pricelist_by_contact/static/description/icon.png
  product_pricelist_by_contact/static/description/index.html
  product_pricelist_by_contact/views/res_partner_views.xml
  setup/product_pricelist_by_contact/odoo/addons/product_pricelist_by_contact
  setup/product_pricelist_by_contact/setup.py
Labels: approved, bot is merging ⏳

#1104 [FIX] product_model_viewer: Change recordset to record
  product_model_viewer/models/product.py
  product_model_viewer/readme/CONTRIBUTORS.rst
  product_model_viewer/tests/__init__.py
  product_model_viewer/tests/test_model_viewer.py
Labels: approved, bot is merging ⏳

#479 [12.0] [MIG] product_end_of_life
  product_end_of_life/README.rst
  product_end_of_life/__init__.py
  product_end_of_life/__manifest__.py
  product_end_of_life/data/ir_cron.xml
  product_end_of_life/data/mail_channel_data.xml
  product_end_of_life/i18n/product_end_of_life.pot
  product_end_of_life/models/__init__.py
  product_end_of_life/models/product.py
  product_end_of_life/models/res_config_settings.py
  product_end_of_life/readme/CONFIGURE.rst
  product_end_of_life/readme/CONTRIBUTORS.rst
  product_end_of_life/readme/DESCRIPTION.rst
  product_end_of_life/readme/USAGE.rst
  product_end_of_life/static/description/icon.png
  product_end_of_life/static/description/index.html
  product_end_of_life/tests/__init__.py
  product_end_of_life/tests/test_product_eol.py
  product_end_of_life/views/mail_templates.xml
  product_end_of_life/views/product_view.xml
  product_end_of_life/views/purchase_view.xml
  product_end_of_life/views/res_config_settings_view.xml
Labels: needs review, needs fixing, bot is merging ⏳

#831 [FIX] product_standard_price_tax_included: handle case where pricelist items has discount (and surcharge, ...)
  product_standard_price_tax_included/models/__init__.py
  product_standard_price_tax_included/models/product_pricelist.py
  product_standard_price_tax_included/tests/test_module.py
Labels: bot is merging ⏳, stale

#1110 [14.0] product_pricelist_revision: fix date_end/date_start are datetime
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
Labels: approved, bot is merging ⏳

#1116 [14.0][IMP] product_pricelist_direct_print: Give formats to add_extra_info method
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
Labels: bot is merging ⏳

#1100 [13.0][IMP] product_sequence: Check for subsequent duplicates
  product_sequence/models/product_product.py
  product_sequence/tests/test_product_sequence.py
Labels: approved, bot is merging ⏳

#1114 [13.0][MIG] product_pricelist_simulation: Migration to 13.0
  product_pricelist_simulation/README.rst
  product_pricelist_simulation/__init__.py
  product_pricelist_simulation/__manifest__.py
  product_pricelist_simulation/i18n/es.po
  product_pricelist_simulation/i18n/product_pricelist_simulation.pot
  product_pricelist_simulation/models/__init__.py
  product_pricelist_simulation/models/pricelist.py
  product_pricelist_simulation/readme/CONTRIBUTORS.rst
  product_pricelist_simulation/readme/DESCRIPTION.rst
  product_pricelist_simulation/readme/USAGE.rst
  product_pricelist_simulation/static/description/icon.png
  product_pricelist_simulation/static/description/index.html
  product_pricelist_simulation/tests/__init__.py
  product_pricelist_simulation/tests/test_product_pricelist_simulation.py
  product_pricelist_simulation/views/pricelist_views.xml
  product_pricelist_simulation/views/product_views.xml
  product_pricelist_simulation/wizards/__init__.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist_views.xml
  setup/product_pricelist_simulation/odoo/addons/product_pricelist_simulation
  setup/product_pricelist_simulation/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1080 [15.0] [MIG] product_assortment: Migration to 15.0
  product_assortment/README.rst
  product_assortment/__init__.py
  product_assortment/__manifest__.py
  product_assortment/i18n/ca.po
  product_assortment/i18n/es.po
  product_assortment/i18n/it.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/readme/CONTRIBUTORS.rst
  product_assortment/readme/DESCRIPTION.rst
  product_assortment/readme/HISTORY.rst
  product_assortment/readme/USAGE.rst
  product_assortment/static/description/icon.png
  product_assortment/static/description/index.html
  product_assortment/tests/__init__.py
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
  setup/product_assortment/odoo/addons/product_assortment
  setup/product_assortment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#862 [14.0][MIG] product_categ_image
  product_categ_image/README.rst
  product_categ_image/__init__.py
  product_categ_image/__manifest__.py
  product_categ_image/i18n/product_categ_image.pot
  product_categ_image/models/__init__.py
  product_categ_image/models/product_category.py
  product_categ_image/static/description/icon.png
  product_categ_image/views/product_view.xml
  setup/product_categ_image/odoo/addons/product_categ_image
  setup/product_categ_image/setup.py
Labels: needs review, migration, bot is merging ⏳

#998 [IMP]product_attribute_archive: Add active field on the Attribute Values tree view
  product_attribute_archive/__manifest__.py
  product_attribute_archive/readme/CONTRIBUTORS.rst
  product_attribute_archive/views/product_attribute_value.xml
Labels: approved, ready to merge, bot is merging ⏳
