Repository OCA/product-attribute, pull requests merged in 2023-01, with the labels that each got.

#1243 [15.0][MIG] product_pricelist_direct_print_website_sale: Migration to version 15.0
  product_pricelist_direct_print_website_sale/README.rst
  product_pricelist_direct_print_website_sale/__init__.py
  product_pricelist_direct_print_website_sale/__manifest__.py
  product_pricelist_direct_print_website_sale/i18n/es.po
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_direct_print_website_sale.pot
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_print_website_sale.pot
  product_pricelist_direct_print_website_sale/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_website_sale/readme/DESCRIPTION.rst
  product_pricelist_direct_print_website_sale/readme/USAGE.rst
  product_pricelist_direct_print_website_sale/report/__init__.py
  product_pricelist_direct_print_website_sale/report/product_pricelist_xlsx.py
  product_pricelist_direct_print_website_sale/static/description/icon.png
  product_pricelist_direct_print_website_sale/static/description/index.html
  product_pricelist_direct_print_website_sale/wizards/__init__.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print_website_sale/odoo/addons/product_pricelist_direct_print_website_sale
  setup/product_pricelist_direct_print_website_sale/setup.py
Labels: approved, bot is merging ⏳

#1247 [15.0][MIG] product_pricelist_direct_print_company_group: Migration to version 15.0
  product_pricelist_direct_print_company_group/README.rst
  product_pricelist_direct_print_company_group/__init__.py
  product_pricelist_direct_print_company_group/__manifest__.py
  product_pricelist_direct_print_company_group/i18n/product_pricelist_direct_print_company_group.pot
  product_pricelist_direct_print_company_group/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_company_group/readme/DESCRIPTION.rst
  product_pricelist_direct_print_company_group/readme/USAGE.rst
  product_pricelist_direct_print_company_group/static/description/icon.png
  product_pricelist_direct_print_company_group/static/description/index.html
  product_pricelist_direct_print_company_group/wizards/__init__.py
  product_pricelist_direct_print_company_group/wizards/product_pricelist_print.py
  setup/product_pricelist_direct_print_company_group/odoo/addons/product_pricelist_direct_print_company_group
  setup/product_pricelist_direct_print_company_group/setup.py
Labels: approved, bot is merging ⏳

#1241 [15.0][ADD] product_drained_weight
  product_drained_weight/README.rst
  product_drained_weight/__init__.py
  product_drained_weight/__manifest__.py
  product_drained_weight/i18n/es.po
  product_drained_weight/i18n/product_drained_weight.pot
  product_drained_weight/models/__init__.py
  product_drained_weight/models/product_product.py
  product_drained_weight/models/product_template.py
  product_drained_weight/readme/CONTRIBUTORS.rst
  product_drained_weight/readme/DESCRIPTION.rst
  product_drained_weight/readme/USAGE.rst
  product_drained_weight/static/description/icon.png
  product_drained_weight/static/description/index.html
  product_drained_weight/tests/__init__.py
  product_drained_weight/tests/test_product_drained_weight.py
  product_drained_weight/views/view_product_product.xml
  product_drained_weight/views/view_product_template.xml
  setup/product_drained_weight/odoo/addons/product_drained_weight
  setup/product_drained_weight/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1249 [15.0][IMP] product_code_unique: Tests more resilient
  product_code_unique/models/product.py
  product_code_unique/tests/test_code_unique.py
Labels: approved, bot is merging ⏳

#1119 [15.0][MIG] purchase_product_template_tags: Migration to 15.0
  purchase_product_template_tags/README.rst
  purchase_product_template_tags/__init__.py
  purchase_product_template_tags/__manifest__.py
  purchase_product_template_tags/i18n/it.po
  purchase_product_template_tags/i18n/purchase_product_template_tags.pot
  purchase_product_template_tags/readme/CONTRIBUTORS.rst
  purchase_product_template_tags/readme/DESCRIPTION.rst
  purchase_product_template_tags/static/description/icon.png
  purchase_product_template_tags/static/description/index.html
  purchase_product_template_tags/views/product_template_tag.xml
  setup/purchase_product_template_tags/odoo/addons/purchase_product_template_tags
  setup/purchase_product_template_tags/setup.py
Labels: bot is merging ⏳

#1118 [15.0][MIG] stock_product_template_tags: Migration to 15.0
  setup/stock_product_template_tags/odoo/addons/stock_product_template_tags
  setup/stock_product_template_tags/setup.py
  stock_product_template_tags/README.rst
  stock_product_template_tags/__init__.py
  stock_product_template_tags/__manifest__.py
  stock_product_template_tags/i18n/it.po
  stock_product_template_tags/i18n/stock_product_template_tags.pot
  stock_product_template_tags/readme/CONTRIBUTORS.rst
  stock_product_template_tags/readme/DESCRIPTION.rst
  stock_product_template_tags/static/description/icon.png
  stock_product_template_tags/static/description/index.html
  stock_product_template_tags/views/product_template_tag.xml
Labels: approved, bot is merging ⏳, stale

#1242 [13.0][FIX] product_pricelist_supplierinfo: Seller got from other company
  product_pricelist_supplierinfo/models/product_pricelist.py
Labels: approved, ready to merge, bot is merging ⏳

#1245 [MIG] product_expiry_configurable: Migration to 14.0
  product_expiry_configurable/README.rst
  product_expiry_configurable/__init__.py
  product_expiry_configurable/__manifest__.py
  product_expiry_configurable/data/product_expiry_data.xml
  product_expiry_configurable/i18n/product_expiry_configurable.pot
  product_expiry_configurable/migrations/14.0.1.0.0/noupdate_changes.xml
  product_expiry_configurable/migrations/14.0.1.0.0/post-migration.py
  product_expiry_configurable/migrations/14.0.1.0.0/pre-migration.py
  product_expiry_configurable/models/__init__.py
  product_expiry_configurable/models/product_category.py
  product_expiry_configurable/models/product_template.py
  product_expiry_configurable/models/stock_production_lot.py
  product_expiry_configurable/readme/CONTRIBUTORS.rst
  product_expiry_configurable/readme/DESCRIPTION.rst
  product_expiry_configurable/static/description/icon.png
  product_expiry_configurable/static/description/index.html
  product_expiry_configurable/tests/__init__.py
  product_expiry_configurable/tests/test_product_category.py
  product_expiry_configurable/tests/test_product_template.py
  product_expiry_configurable/tests/test_stock_production_lot.py
  product_expiry_configurable/views/product_category.xml
  product_expiry_configurable/views/product_template.xml
  product_expiry_configurable/views/stock_production_lot.xml
  setup/product_expiry_configurable/odoo/addons/product_expiry_configurable
  setup/product_expiry_configurable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1235 [15.0][MIG] product_abc_classification: Migration to version 15.0
  product_abc_classification/README.rst
  product_abc_classification/__init__.py
  product_abc_classification/__manifest__.py
  product_abc_classification/data/ir_cron.xml
  product_abc_classification/i18n/product_abc_classification.pot
  product_abc_classification/models/__init__.py
  product_abc_classification/models/abc_classification_level.py
  product_abc_classification/models/abc_classification_profile.py
  product_abc_classification/models/product_category.py
  product_abc_classification/models/product_product.py
  product_abc_classification/readme/CONTRIBUTORS.rst
  product_abc_classification/readme/DESCRIPTION.rst
  product_abc_classification/readme/USAGE.rst
  product_abc_classification/security/ir.model.access.csv
  product_abc_classification/static/description/icon.png
  product_abc_classification/static/description/index.html
  product_abc_classification/views/abc_classification_view.xml
  product_abc_classification/views/product_view.xml
  setup/product_abc_classification/odoo/addons/product_abc_classification
  setup/product_abc_classification/setup.py
Labels: approved, bot is merging ⏳
