Repository OCA/product-attribute, pull requests merged in 2023-10, with the labels that each got.

#1426 [16.0][FIX] product_packaging_dimension: post-migrate script should only apply query if column max_weight exists
  product_packaging_dimension/migrations/16.0.1.1.0/post-migrate.py
Labels: approved, bot is merging ⏳

#1429 [15.0][IMP] product_pricelist_direct_print, allow field breakage_per_category works on pdf printing
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: approved, bot is merging ⏳

#1404 [16.0][MIG] product_total_weight_from_packaging: Migrate to 16.0
  product_total_weight_from_packaging/README.rst
  product_total_weight_from_packaging/__init__.py
  product_total_weight_from_packaging/__manifest__.py
  product_total_weight_from_packaging/i18n/es.po
  product_total_weight_from_packaging/i18n/product_total_weight_from_packaging.pot
  product_total_weight_from_packaging/models/__init__.py
  product_total_weight_from_packaging/models/product.py
  product_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  product_total_weight_from_packaging/readme/CREDITS.rst
  product_total_weight_from_packaging/readme/DESCRIPTION.rst
  product_total_weight_from_packaging/static/description/icon.png
  product_total_weight_from_packaging/static/description/index.html
  product_total_weight_from_packaging/tests/__init__.py
  product_total_weight_from_packaging/tests/test_product_total_weight_from_packaging.py
  setup/product_total_weight_from_packaging/odoo/addons/product_total_weight_from_packaging
  setup/product_total_weight_from_packaging/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1308 [14.0][FW][IMP] product_variant_attribute_name_manager: option to display/hide attribute value in product name
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
Labels: approved, bot is merging ⏳, stale

#1395 [16.0][ADD] product_packaging_level_salable
  product_packaging_level_salable/README.rst
  product_packaging_level_salable/__init__.py
  product_packaging_level_salable/__manifest__.py
  product_packaging_level_salable/migrations/16.0.1.0.0/post-migrate.py
  product_packaging_level_salable/models/__init__.py
  product_packaging_level_salable/models/product_packaging.py
  product_packaging_level_salable/models/product_packaging_level.py
  product_packaging_level_salable/models/sale_order_line.py
  product_packaging_level_salable/readme/CONFIGURE.rst
  product_packaging_level_salable/readme/CONTRIBUTORS.rst
  product_packaging_level_salable/readme/CREDITS.rst
  product_packaging_level_salable/readme/DESCRIPTION.rst
  product_packaging_level_salable/static/description/icon.png
  product_packaging_level_salable/static/description/index.html
  product_packaging_level_salable/tests/__init__.py
  product_packaging_level_salable/tests/common.py
  product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
  product_packaging_level_salable/views/product_packaging_level.xml
  setup/product_packaging_level_salable/odoo/addons/product_packaging_level_salable
  setup/product_packaging_level_salable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1309 [15.0][FW][IMP] product_variant_attribute_name_manager: option to display/hide attribute value in product name
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1427 [16.0][IMP] product_packaging_level: configure product packaging name
  product_packaging_level/__manifest__.py
  product_packaging_level/models/__init__.py
  product_packaging_level/models/product_packaging.py
  product_packaging_level/models/product_packaging_level.py
  product_packaging_level/models/stock_package_type.py
  product_packaging_level/readme/CONTRIBUTORS.rst
  product_packaging_level/tests/test_product_packaging_level.py
  product_packaging_level/views/product_packaging_level_view.xml
  product_packaging_level/views/product_packaging_view.xml
  product_packaging_level/views/stock_package_type_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1437 [15.0][IMP] product-attribute : test performance improvement
  product_category_active/tests/test_product_category_active.py
  product_code_unique/tests/test_code_unique.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_sequence/tests/test_product_sequence.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
Labels: bot is merging ⏳

#1433 [16.0][MIG] product_pricelist_item_list_view
  product_pricelist_item_list_view/README.rst
  product_pricelist_item_list_view/__init__.py
  product_pricelist_item_list_view/__manifest__.py
  product_pricelist_item_list_view/i18n/ca.po
  product_pricelist_item_list_view/i18n/de.po
  product_pricelist_item_list_view/i18n/es.po
  product_pricelist_item_list_view/i18n/fr.po
  product_pricelist_item_list_view/i18n/product_pricelist_item_list_view.pot
  product_pricelist_item_list_view/static/description/icon.png
  product_pricelist_item_list_view/views/pricelist_view.xml
  setup/product_pricelist_item_list_view/odoo/addons/product_pricelist_item_list_view
  setup/product_pricelist_item_list_view/setup.py
Labels: bot is merging ⏳

#1439 [16.0][FIX] product_pricelist_simulation: switch tests to TransactionCase
  product_pricelist_simulation/tests/test_product_pricelist_simulation.py
Labels: bot is merging ⏳

#1339 [16.0][MIG] - product_stock_state
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/data/data.xml
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/nl.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/res_config_settings.py
  product_stock_state/readme/CONFIGURE.rst
  product_stock_state/readme/CONTRIBUTORS.rst
  product_stock_state/readme/CREDITS.rst
  product_stock_state/readme/DESCRIPTION.rst
  product_stock_state/readme/USAGE.rst
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/icon.png
  product_stock_state/static/description/index.html
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/res_company_view.xml
  product_stock_state/views/res_config_settings_view.xml
  setup/product_stock_state/odoo/addons/product_stock_state
  setup/product_stock_state/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1442 [16.0][IMP] product-attribute : test performance improvement
  product_category_active/tests/test_product_category_active.py
  product_code_unique/tests/test_code_unique.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_sequence/tests/test_product_sequence.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
Labels: bot is merging ⏳

#1441 [16.0][mig] product_template_tags
  product_template_tags/README.rst
  product_template_tags/__init__.py
  product_template_tags/__manifest__.py
  product_template_tags/i18n/ca_ES.po
  product_template_tags/i18n/de.po
  product_template_tags/i18n/es.po
  product_template_tags/i18n/fr.po
  product_template_tags/i18n/hr.po
  product_template_tags/i18n/it.po
  product_template_tags/i18n/nl.po
  product_template_tags/i18n/product_template_tags.pot
  product_template_tags/i18n/pt.po
  product_template_tags/i18n/sl_SI.po
  product_template_tags/models/__init__.py
  product_template_tags/models/product_template.py
  product_template_tags/models/product_template_tag.py
  product_template_tags/readme/CONFIGURE.rst
  product_template_tags/readme/CONTRIBUTORS.rst
  product_template_tags/readme/DESCRIPTION.rst
  product_template_tags/readme/USAGE.rst
  product_template_tags/security/product_template_rule.xml
  product_template_tags/security/product_template_tag.xml
  product_template_tags/static/description/icon.png
  product_template_tags/static/description/index.html
  product_template_tags/tests/__init__.py
  product_template_tags/tests/test_product_template_tags.py
  product_template_tags/views/product_product.xml
  product_template_tags/views/product_template.xml
  product_template_tags/views/product_template_tag.xml
  setup/product_template_tags/odoo/addons/product_template_tags
  setup/product_template_tags/setup.py
Labels: approved, bot is merging ⏳

#1444 [16.0][FIX] product_template_tags: Keep depends on 'product' module
  product_template_tags/__manifest__.py
Labels: approved, bot is merging ⏳
