Repository OCA/product-attribute, pull requests merged in 2023-09, with the labels that each got.

#1403 [14.0] product_supplierinfo_archive: add a cron task to disable expired vendor pricelists
  product_supplierinfo_archive/README.rst
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/data/ir_cron.xml
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/readme/USAGE.rst
  product_supplierinfo_archive/tests/__init__.py
  product_supplierinfo_archive/tests/test_ir_cron.py
Labels: approved, ready to merge, bot is merging ⏳

#1400 [14.0] product_sale_manufactured_for: move rel to variant
  product_sale_manufactured_for/__manifest__.py
  product_sale_manufactured_for/migrations/14.0.1.1.0/post-migrate.py
  product_sale_manufactured_for/migrations/14.0.1.1.0/pre-migrate.py
  product_sale_manufactured_for/models/__init__.py
  product_sale_manufactured_for/models/product_product.py
  product_sale_manufactured_for/readme/CONTRIBUTORS.rst
  product_sale_manufactured_for/views/product_product.xml
  product_sale_manufactured_for/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1413 [15.0][FIX] product_secondary_unit: Don't reassign old value
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#1414 [15.0][FIX] product_secondary_unit: wrong factor computation for uom's equal between secondary uom and product uom
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#1415 [16.0][FIX] product_secondary_unit: wrong factor computation for uom's equal between secondary uom and product uom
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#1192 [MIG][16.0] product_abc_classification
  product_abc_classification/README.rst
  product_abc_classification/__init__.py
  product_abc_classification/__manifest__.py
  product_abc_classification/data/ir_cron.xml
  product_abc_classification/i18n/fr.po
  product_abc_classification/models/__init__.py
  product_abc_classification/models/abc_classification_level.py
  product_abc_classification/models/abc_classification_product_level.py
  product_abc_classification/models/abc_classification_profile.py
  product_abc_classification/models/product_product.py
  product_abc_classification/models/product_template.py
  product_abc_classification/readme/CONTRIBUTORS.rst
  product_abc_classification/readme/DESCRIPTION.rst
  product_abc_classification/readme/USAGE.rst
  product_abc_classification/security/ir.model.access.csv
  product_abc_classification/static/description/icon.png
  product_abc_classification/static/description/index.html
  product_abc_classification/tests/__init__.py
  product_abc_classification/tests/common.py
  product_abc_classification/tests/test_abc_classification_product_level.py
  product_abc_classification/tests/test_abc_classification_profile.py
  product_abc_classification/tests/test_product.py
  product_abc_classification/views/abc_classification_product_level.xml
  product_abc_classification/views/abc_classification_profile.xml
  product_abc_classification/views/product_product.xml
  product_abc_classification/views/product_template.xml
  setup/product_abc_classification/odoo/addons/product_abc_classification
  setup/product_abc_classification/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1215 [MIG][16.0] product_packaging_type + renaming to product_packaging_level
  product_packaging_level/README.rst
  product_packaging_level/__init__.py
  product_packaging_level/__manifest__.py
  product_packaging_level/data/product_packaging_level.xml
  product_packaging_level/hooks.py
  product_packaging_level/i18n/ca.po
  product_packaging_level/i18n/es.po
  product_packaging_level/i18n/nl.po
  product_packaging_level/i18n/product_packaging_level.pot
  product_packaging_level/models/__init__.py
  product_packaging_level/models/product_packaging.py
  product_packaging_level/models/product_packaging_level.py
  product_packaging_level/readme/CONTRIBUTORS.rst
  product_packaging_level/readme/CREDITS.rst
  product_packaging_level/readme/DESCRIPTION.rst
  product_packaging_level/readme/USAGE.rst
  product_packaging_level/security/ir.model.access.csv
  product_packaging_level/static/description/icon.png
  product_packaging_level/static/description/index.html
  product_packaging_level/tests/__init__.py
  product_packaging_level/tests/test_product_packaging_level.py
  product_packaging_level/views/product_packaging_level_view.xml
  product_packaging_level/views/product_packaging_view.xml
  setup/product_packaging_level/odoo/addons/product_packaging_level
  setup/product_packaging_level/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1416 [FIX] product_packaging_level: Use correct field in hook
  product_packaging_level/hooks.py
Labels: bot is merging ⏳

#1361 [16.0][mig] product_supplierinfo_archive: Migration to 16.0
  product_supplierinfo_archive/README.rst
  product_supplierinfo_archive/__init__.py
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/i18n/product_supplierinfo_archive.pot
  product_supplierinfo_archive/models/__init__.py
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/readme/CONTRIBUTORS.rst
  product_supplierinfo_archive/readme/DESCRIPTION.rst
  product_supplierinfo_archive/readme/USAGE.rst
  product_supplierinfo_archive/static/description/icon.png
  product_supplierinfo_archive/static/description/index.html
  product_supplierinfo_archive/views/product_views.xml
  setup/product_supplierinfo_archive/odoo/addons/product_supplierinfo_archive
  setup/product_supplierinfo_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1342 [14.0][FIX] pos_product_cost_security: missing flag on `_loadMissingProducts`
  pos_product_cost_security/static/src/js/models.js
Labels: approved, ready to merge, bot is merging ⏳

#1411 [ADD] product_category_hr_department
  product_category_hr_department/README.rst
  product_category_hr_department/__init__.py
  product_category_hr_department/__manifest__.py
  product_category_hr_department/models/__init__.py
  product_category_hr_department/models/product_category.py
  product_category_hr_department/readme/CONTRIBUTORS.rst
  product_category_hr_department/readme/DESCRIPTION.rst
  product_category_hr_department/views/product_category_views.xml
  setup/product_category_hr_department/odoo/addons/product_category_hr_department
  setup/product_category_hr_department/setup.py
Labels: enhancement, needs review, bot is merging ⏳

#1091 [15.0][MIG] product_custom_info
  product_custom_info/README.rst
  product_custom_info/__init__.py
  product_custom_info/__manifest__.py
  product_custom_info/i18n/ca.po
  product_custom_info/i18n/es.po
  product_custom_info/i18n/it.po
  product_custom_info/i18n/product_custom_info.pot
  product_custom_info/i18n/pt.po
  product_custom_info/models/__init__.py
  product_custom_info/models/product_product.py
  product_custom_info/models/product_template.py
  product_custom_info/readme/CONFIGURE.rst
  product_custom_info/readme/CONTRIBUTORS.rst
  product_custom_info/readme/DESCRIPTION.rst
  product_custom_info/readme/INSTALL.rst
  product_custom_info/readme/USAGE.rst
  product_custom_info/static/description/icon.png
  product_custom_info/static/description/index.html
  product_custom_info/tests/__init__.py
  product_custom_info/tests/test_product_custom_info.py
  product_custom_info/views/product_product_view.xml
  product_custom_info/views/product_template_view.xml
  setup/product_custom_info/odoo/addons/product_custom_info
  setup/product_custom_info/setup.py
Labels: bot is merging ⏳, stale

#1303 product_supplierinfo_group: fix deleting product_supplierinfo_group
  product_supplierinfo_group/models/product_supplierinfo.py
Labels: bot is merging ⏳, stale

#1417 [16.0][MIG] product_pricelist_direct_print_website_sale: Migration to version 16.0
  product_pricelist_direct_print_website_sale/README.rst
  product_pricelist_direct_print_website_sale/__init__.py
  product_pricelist_direct_print_website_sale/__manifest__.py
  product_pricelist_direct_print_website_sale/i18n/es.po
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_direct_print_website_sale.pot
  product_pricelist_direct_print_website_sale/i18n/product_pricelist_print_website_sale.pot
  product_pricelist_direct_print_website_sale/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_website_sale/readme/DESCRIPTION.rst
  product_pricelist_direct_print_website_sale/readme/USAGE.rst
  product_pricelist_direct_print_website_sale/report/__init__.py
  product_pricelist_direct_print_website_sale/report/product_pricelist_xlsx.py
  product_pricelist_direct_print_website_sale/static/description/icon.png
  product_pricelist_direct_print_website_sale/static/description/index.html
  product_pricelist_direct_print_website_sale/wizards/__init__.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print.py
  product_pricelist_direct_print_website_sale/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print_website_sale/odoo/addons/product_pricelist_direct_print_website_sale
  setup/product_pricelist_direct_print_website_sale/setup.py
Labels: approved, bot is merging ⏳

#1386 [IMP] product_packaging_dimension: Don't use max_weight anymore
  product_packaging_dimension/__manifest__.py
  product_packaging_dimension/migrations/16.0.1.1.0/post-migrate.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/views/product_packaging.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1422 [16.0][FIX] product_pricelist_direct_print: add missing dependency in compute
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: bot is merging ⏳

#1424 [16.0][FIX] product_manufacturer - Fix missing migration method
  product_manufacturer/models/product_template.py
Labels: approved, bot is merging ⏳

#1425 [16.0][FIX] product_secondary_unit: precompute secondary_uom_qty
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳
