Repository OCA/product-attribute, pull requests merged in 2023-04, with the labels that each got.

#1230 [16.0][MIG] product_supplierinfo_for_customer: Migration to 16.0
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__init__.py
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/demo/product_demo.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/sl.po
  product_supplierinfo_for_customer/migrations/16.0.1.0.0/pre-migration.py
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_pricelist.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/models/res_partner.py
  product_supplierinfo_for_customer/readme/CONFIGURE.rst
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.rst
  product_supplierinfo_for_customer/readme/DESCRIPTION.rst
  product_supplierinfo_for_customer/readme/ROADMAP.rst
  product_supplierinfo_for_customer/readme/USAGE.rst
  product_supplierinfo_for_customer/security/ir.model.access.csv
  product_supplierinfo_for_customer/static/description/icon.png
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/static/xls/product_customerinfo.xls
  product_supplierinfo_for_customer/tests/__init__.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_views.xml
  setup/product_supplierinfo_for_customer/odoo/addons/product_supplierinfo_for_customer
  setup/product_supplierinfo_for_customer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1316 [13.0][FIX] product_pricelist_direct_print: Users with low permissions can not select products in wizard
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1283 15.0 [MIG] base_product_mass_addition
  base_product_mass_addition/README.rst
  base_product_mass_addition/__init__.py
  base_product_mass_addition/__manifest__.py
  base_product_mass_addition/i18n/base_product_mass_addition.pot
  base_product_mass_addition/i18n/fr.po
  base_product_mass_addition/models/__init__.py
  base_product_mass_addition/models/product_mass_addition.py
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
  base_product_mass_addition/readme/DESCRIPTION.rst
  base_product_mass_addition/readme/ROADMAP.rst
  base_product_mass_addition/static/description/filter.png
  base_product_mass_addition/static/description/icon.png
  base_product_mass_addition/static/description/index.html
  base_product_mass_addition/static/description/po-product.png
  base_product_mass_addition/static/description/po.png
  base_product_mass_addition/tests/__init__.py
  base_product_mass_addition/tests/models/order.py
  base_product_mass_addition/tests/test_product_mass_addition.py
  base_product_mass_addition/views/product_view.xml
  setup/base_product_mass_addition/odoo/addons/base_product_mass_addition
  setup/base_product_mass_addition/setup.py
Labels: approved, bot is merging ⏳

#1310 [15.0][MIG] product_multi_price: Migration to version 15.0
  product_multi_price/README.rst
  product_multi_price/__init__.py
  product_multi_price/__manifest__.py
  product_multi_price/demo/multi_price_demo_data.xml
  product_multi_price/hooks.py
  product_multi_price/i18n/ca.po
  product_multi_price/i18n/es.po
  product_multi_price/i18n/it.po
  product_multi_price/i18n/product_multi_price.pot
  product_multi_price/models/__init__.py
  product_multi_price/models/product_multi_price.py
  product_multi_price/models/product_pricelist.py
  product_multi_price/models/product_product.py
  product_multi_price/models/product_template.py
  product_multi_price/readme/CONFIGURE.rst
  product_multi_price/readme/CONTRIBUTORS.rst
  product_multi_price/readme/DESCRIPTION.rst
  product_multi_price/readme/ROADMAP.rst
  product_multi_price/readme/USAGE.rst
  product_multi_price/security/ir.model.access.csv
  product_multi_price/security/multi_price_security.xml
  product_multi_price/static/description/icon.png
  product_multi_price/static/description/index.html
  product_multi_price/tests/__init__.py
  product_multi_price/tests/test_product_multi_price.py
  product_multi_price/views/multi_price_views.xml
  product_multi_price/views/product_pricelist_views.xml
  product_multi_price/views/product_views.xml
  setup/product_multi_price/odoo/addons/product_multi_price
  setup/product_multi_price/setup.py
Labels: approved, bot is merging ⏳

#1178 [FIX][12.0] product_standard_price_tax_included : make the price computation working with product variants AND product templates
  product_standard_price_tax_included/models/__init__.py
  product_standard_price_tax_included/models/product_template.py
  product_standard_price_tax_included/tests/test_module.py
Labels: bot is merging ⏳

#1227 [16.0][ADD] product_route_mto
  product_route_mto/README.rst
  product_route_mto/__init__.py
  product_route_mto/__manifest__.py
  product_route_mto/i18n/fr_BE.po
  product_route_mto/i18n/product_route_mto.pot
  product_route_mto/models/__init__.py
  product_route_mto/models/product_template.py
  product_route_mto/readme/CONTRIBUTORS.rst
  product_route_mto/readme/DESCRIPTION.rst
  product_route_mto/static/description/icon.png
  product_route_mto/static/description/index.html
  product_route_mto/tests/__init__.py
  product_route_mto/tests/test_product_route_mto.py
  product_route_mto/views/product_template.xml
  setup/product_route_mto/odoo/addons/product_route_mto
  setup/product_route_mto/setup.py
Labels: needs review, approved, bot is merging ⏳

#1318 [MIG][16.0] product_expiry_configurable
  product_expiry_configurable/README.rst
  product_expiry_configurable/__init__.py
  product_expiry_configurable/__manifest__.py
  product_expiry_configurable/data/product_expiry_data.xml
  product_expiry_configurable/i18n/product_expiry_configurable.pot
  product_expiry_configurable/migrations/16.0.1.0.0/post-migrate.py
  product_expiry_configurable/migrations/16.0.1.0.0/pre-migrate.py
  product_expiry_configurable/models/__init__.py
  product_expiry_configurable/models/product_category.py
  product_expiry_configurable/models/product_template.py
  product_expiry_configurable/models/stock_lot.py
  product_expiry_configurable/readme/CONFIGURE.rst
  product_expiry_configurable/readme/CONTRIBUTORS.rst
  product_expiry_configurable/readme/DESCRIPTION.rst
  product_expiry_configurable/static/description/icon.png
  product_expiry_configurable/static/description/index.html
  product_expiry_configurable/static/images/category.png
  product_expiry_configurable/static/images/crons.png
  product_expiry_configurable/tests/__init__.py
  product_expiry_configurable/tests/common.py
  product_expiry_configurable/tests/test_product_category.py
  product_expiry_configurable/tests/test_product_template.py
  product_expiry_configurable/tests/test_stock_production_lot.py
  product_expiry_configurable/views/product_category.xml
  product_expiry_configurable/views/stock_lot.xml
  setup/product_expiry_configurable/odoo/addons/product_expiry_configurable
  setup/product_expiry_configurable/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1286 [16.0][MIG] product_uom_updatable
  product_uom_updatable/README.rst
  product_uom_updatable/__init__.py
  product_uom_updatable/__manifest__.py
  product_uom_updatable/i18n/product_uom_updatable.pot
  product_uom_updatable/models/__init__.py
  product_uom_updatable/models/product_template.py
  product_uom_updatable/readme/CONTRIBUTORS.rst
  product_uom_updatable/readme/CREDITS.rst
  product_uom_updatable/readme/DESCRIPTION.rst
  product_uom_updatable/static/description/icon.png
  product_uom_updatable/static/description/index.html
  product_uom_updatable/tests/__init__.py
  product_uom_updatable/tests/test_product_uom_update.py
  setup/product_uom_updatable/odoo/addons/product_uom_updatable
  setup/product_uom_updatable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1240 [16.0][MIG] product_cost_security: Migration to 16.0
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/ca.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_product.py
  product_cost_security/models/product_template.py
  product_cost_security/readme/CONFIGURE.rst
  product_cost_security/readme/CONTRIBUTORS.rst
  product_cost_security/readme/DESCRIPTION.rst
  product_cost_security/readme/USAGE.rst
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/tests/__init__.py
  product_cost_security/tests/test_product_cost_security.py
  product_cost_security/views/product_views.xml
  setup/product_cost_security/odoo/addons/product_cost_security
  setup/product_cost_security/setup.py
Labels: approved, bot is merging ⏳
