Repository OCA/product-attribute, pull requests merged in 2023-11, with the labels that each got.

#1335 [16.0][IMP] Product State
  product_state/views/product_state_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1222 [15.0][MIG] product_stock_state
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/data/data.xml
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/nl.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/res_config_settings.py
  product_stock_state/readme/CONFIGURE.rst
  product_stock_state/readme/CONTRIBUTORS.rst
  product_stock_state/readme/CREDITS.rst
  product_stock_state/readme/DESCRIPTION.rst
  product_stock_state/readme/USAGE.rst
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/icon.png
  product_stock_state/static/description/index.html
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/res_company_view.xml
  product_stock_state/views/res_config_settings_view.xml
  setup/product_stock_state/odoo/addons/product_stock_state
  setup/product_stock_state/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1337 [16.0] [ADD] New module: uom_category_active
  setup/uom_category_active/odoo/addons/uom_category_active
  setup/uom_category_active/setup.py
  uom_category_active/README.rst
  uom_category_active/__init__.py
  uom_category_active/__manifest__.py
  uom_category_active/models/__init__.py
  uom_category_active/models/uom_category.py
  uom_category_active/readme/CONTRIBUTORS.rst
  uom_category_active/readme/DESCRIPTION.rst
  uom_category_active/readme/USAGE.rst
  uom_category_active/static/description/index.html
  uom_category_active/tests/__init__.py
  uom_category_active/tests/test_uom_category_active.py
  uom_category_active/views/uom_category_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1412 [16.0][ADD] product_company_default
  product_company_default/README.rst
  product_company_default/__init__.py
  product_company_default/__manifest__.py
  product_company_default/data/ir_config_parameter.xml
  product_company_default/demo/demo_ir_config_parameter.xml
  product_company_default/models/__init__.py
  product_company_default/models/product_template.py
  product_company_default/readme/DESCRIPTION.rst
  product_company_default/static/description/icon.png
  product_company_default/static/description/index.html
  product_company_default/tests/__init__.py
  product_company_default/tests/test_product_company_default.py
  setup/product_company_default/odoo/addons/product_company_default
  setup/product_company_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1176 [ADD][16.0] product_print_category
  product_print_category/README.rst
  product_print_category/__init__.py
  product_print_category/__manifest__.py
  product_print_category/data/report_paperformat.xml
  product_print_category/demo/product_print_category.xml
  product_print_category/demo/product_print_category_rule.xml
  product_print_category/demo/product_product.xml
  product_print_category/demo/qweb_template.xml
  product_print_category/demo/res_groups.xml
  product_print_category/i18n/fr.po
  product_print_category/migrations/16.0.1.0.2/post-migration.py
  product_print_category/migrations/16.0.1.0.2/pre-migration.py
  product_print_category/models/__init__.py
  product_print_category/models/product_print_category.py
  product_print_category/models/product_print_category_mixin.py
  product_print_category/models/product_print_category_rule.py
  product_print_category/models/product_product.py
  product_print_category/models/product_template.py
  product_print_category/readme/CONFIGURE.rst
  product_print_category/readme/CONTRIBUTORS.rst
  product_print_category/readme/DESCRIPTION.rst
  product_print_category/readme/USAGE.rst
  product_print_category/report/__init__.py
  product_print_category/report/ir_actions_report.xml
  product_print_category/report/report_pricetag.py
  product_print_category/report/report_pricetag.xml
  product_print_category/security/ir.model.access.csv
  product_print_category/security/ir_rule.xml
  product_print_category/security/res_groups.xml
  product_print_category/static/description/index.html
  product_print_category/static/description/index.png
  product_print_category/static/description/product_print_category_form.png
  product_print_category/static/description/product_print_category_rule_tree.png
  product_print_category/static/description/product_print_wizard_form.png
  product_print_category/static/description/product_product_form.png
  product_print_category/tests/__init__.py
  product_print_category/tests/test_product_print_category.py
  product_print_category/views/view_product_print_category.xml
  product_print_category/views/view_product_print_category_rule.xml
  product_print_category/views/view_product_product.xml
  product_print_category/views/view_product_template.xml
  product_print_category/wizard/__init__.py
  product_print_category/wizard/product_print_wizard.py
  product_print_category/wizard/product_print_wizard_line.py
  product_print_category/wizard/view_product_print_wizard.xml
  setup/product_print_category/odoo/addons/product_print_category
  setup/product_print_category/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1438 [16.0][ADD] product_pricelist_fixed_currency_rate
  product_pricelist_fixed_currency_rate/README.rst
  product_pricelist_fixed_currency_rate/__init__.py
  product_pricelist_fixed_currency_rate/__manifest__.py
  product_pricelist_fixed_currency_rate/models/__init__.py
  product_pricelist_fixed_currency_rate/models/product_pricelist_item.py
  product_pricelist_fixed_currency_rate/models/res_currency.py
  product_pricelist_fixed_currency_rate/readme/CONTRIBUTORS.rst
  product_pricelist_fixed_currency_rate/readme/DESCRIPTION.rst
  product_pricelist_fixed_currency_rate/readme/USAGE.rst
  product_pricelist_fixed_currency_rate/static/description/icon.png
  product_pricelist_fixed_currency_rate/static/description/index.html
  product_pricelist_fixed_currency_rate/tests/__init__.py
  product_pricelist_fixed_currency_rate/tests/test_product_pricelist_fixed_currency_rate.py
  product_pricelist_fixed_currency_rate/views/pricelist_views.xml
  setup/product_pricelist_fixed_currency_rate/odoo/addons/product_pricelist_fixed_currency_rate
  setup/product_pricelist_fixed_currency_rate/setup.py
Labels: approved, bot is merging ⏳

#1449 16.0 [IMP] product_pricelist_item_list filters
  product_pricelist_item_list_view/views/pricelist_view.xml
Labels: approved, bot is merging ⏳

#1418 [ADD] product_packaging_container_deposit
  product_packaging_container_deposit/README.rst
  product_packaging_container_deposit/__init__.py
  product_packaging_container_deposit/__manifest__.py
  product_packaging_container_deposit/models/__init__.py
  product_packaging_container_deposit/models/container_deposit_order_line_mixin.py
  product_packaging_container_deposit/models/container_deposit_order_mixin.py
  product_packaging_container_deposit/models/product_product.py
  product_packaging_container_deposit/models/stock_package_type.py
  product_packaging_container_deposit/readme/CONTRIBUTORS.rst
  product_packaging_container_deposit/readme/DESCRIPTION.rst
  product_packaging_container_deposit/static/description/index.html
  product_packaging_container_deposit/tests/__init__.py
  product_packaging_container_deposit/tests/common.py
  product_packaging_container_deposit/tests/fake_models.py
  product_packaging_container_deposit/tests/test_container_deposit_order_mixin.py
  product_packaging_container_deposit/tests/test_product_packaging_container_deposit.py
  product_packaging_container_deposit/views/stock_package_type_views.xml
  setup/product_packaging_container_deposit/odoo/addons/product_packaging_container_deposit
  setup/product_packaging_container_deposit/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1436 [16.0][ADD] product_packaging_level_purchasable
  product_packaging_level_purchasable/README.rst
  product_packaging_level_purchasable/__init__.py
  product_packaging_level_purchasable/__manifest__.py
  product_packaging_level_purchasable/models/__init__.py
  product_packaging_level_purchasable/models/product_packaging.py
  product_packaging_level_purchasable/models/product_packaging_level.py
  product_packaging_level_purchasable/models/purchase_order_line.py
  product_packaging_level_purchasable/readme/CONFIGURE.rst
  product_packaging_level_purchasable/readme/CONTRIBUTORS.rst
  product_packaging_level_purchasable/readme/DESCRIPTION.rst
  product_packaging_level_purchasable/static/description/icon.png
  product_packaging_level_purchasable/static/description/index.html
  product_packaging_level_purchasable/tests/__init__.py
  product_packaging_level_purchasable/tests/common.py
  product_packaging_level_purchasable/tests/test_packaging_level_can_be_purchased.py
  product_packaging_level_purchasable/views/product_packaging_level.xml
  setup/product_packaging_level_purchasable/odoo/addons/product_packaging_level_purchasable
  setup/product_packaging_level_purchasable/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1440 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .oca_hooks.cfg
  .pre-commit-config.yaml
  product_assortment_description/i18n/product_assortment_description.pot
  product_state/migrations/13.0.1.0.0/post-migration.py
Labels: help wanted, needs review, bot is merging ⏳

#1457 [REF] copier update v1.17.2 -> v1.19.2
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
Labels: approved

#1347 [16.0][MIG] product_attribute_value_menu: Migration to 16.0
  product_attribute_value_menu/README.rst
  product_attribute_value_menu/__init__.py
  product_attribute_value_menu/__manifest__.py
  product_attribute_value_menu/i18n/it.po
  product_attribute_value_menu/i18n/product_attribute_value_menu.pot
  product_attribute_value_menu/models/__init__.py
  product_attribute_value_menu/models/product_attribute_value.py
  product_attribute_value_menu/readme/CONFIGURE.rst
  product_attribute_value_menu/readme/CONTRIBUTORS.rst
  product_attribute_value_menu/readme/DESCRIPTION.rst
  product_attribute_value_menu/readme/USAGE.rst
  product_attribute_value_menu/static/description/icon.png
  product_attribute_value_menu/static/description/index.html
  product_attribute_value_menu/views/product_attribute_value_views.xml
  product_attribute_value_menu/views/product_template_attribute_value_views.xml
  setup/product_attribute_value_menu/odoo/addons/product_attribute_value_menu
  setup/product_attribute_value_menu/setup.py
Labels: bot is merging ⏳

#1236 [16.0] [MIG] product_variant_attribute_name_manager
  product_variant_attribute_name_manager/README.rst
  product_variant_attribute_name_manager/__init__.py
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/i18n/product_variant_attribute_name_manager.pot
  product_variant_attribute_name_manager/models/__init__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/static/description/icon.png
  product_variant_attribute_name_manager/static/description/index.html
  product_variant_attribute_name_manager/tests/__init__.py
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
  setup/product_variant_attribute_name_manager/odoo/addons/product_variant_attribute_name_manager
  setup/product_variant_attribute_name_manager/setup.py
Labels: bot is merging ⏳, stale

#1465 [16.0][IMP] product_variant_attribute_name_manager: add missing forwardports
  product_variant_attribute_name_manager/README.rst
  product_variant_attribute_name_manager/__manifest__.py
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
  product_variant_attribute_name_manager/static/description/index.html
  product_variant_attribute_name_manager/tests/test_product_variant_attribute_name_manager.py
  product_variant_attribute_name_manager/views/product_variant_attribute_name_manager_view.xml
Labels: approved, bot is merging ⏳

#1453 [ADD] product_internal_reference_generator
  .copier-answers.yml
  .github/workflows/test.yml
  product_internal_reference_generator/README.rst
  product_internal_reference_generator/__init__.py
  product_internal_reference_generator/__manifest__.py
  product_internal_reference_generator/demo/product_code_seq_demo.xml
  product_internal_reference_generator/models/__init__.py
  product_internal_reference_generator/models/product_code_sequence.py
  product_internal_reference_generator/models/product_product.py
  product_internal_reference_generator/models/product_template.py
  product_internal_reference_generator/readme/CONTRIBUTORS.rst
  product_internal_reference_generator/readme/DESCRIPTION.rst
  product_internal_reference_generator/readme/ROADMAP.rst
  product_internal_reference_generator/readme/USAGE.rst
  product_internal_reference_generator/security/groups.xml
  product_internal_reference_generator/security/ir.model.access.csv
  product_internal_reference_generator/static/description/index.html
  product_internal_reference_generator/tests/__init__.py
  product_internal_reference_generator/tests/test_product_internal_reference_generator.py
  product_internal_reference_generator/views/product.xml
  setup/product_internal_reference_generator/odoo/addons/product_internal_reference_generator
  setup/product_internal_reference_generator/setup.py
Labels: approved, bot is merging ⏳

#1406 [MIG][16.0] product_country_restriction
  product_country_restriction/README.rst
  product_country_restriction/__init__.py
  product_country_restriction/__manifest__.py
  product_country_restriction/data/product_country_restriction_rule.xml
  product_country_restriction/demo/product_country_restriction.xml
  product_country_restriction/i18n/product_country_restriction.pot
  product_country_restriction/models/__init__.py
  product_country_restriction/models/country_restriction_mixin.py
  product_country_restriction/models/product_country_restriction.py
  product_country_restriction/models/product_country_restriction_item.py
  product_country_restriction/models/product_country_restriction_rule.py
  product_country_restriction/models/product_product.py
  product_country_restriction/models/product_template.py
  product_country_restriction/models/res_company.py
  product_country_restriction/models/res_country.py
  product_country_restriction/models/res_partner.py
  product_country_restriction/readme/CONTRIBUTORS.rst
  product_country_restriction/readme/DESCRIPTION.rst
  product_country_restriction/readme/HISTORY.rst
  product_country_restriction/readme/USAGE.rst
  product_country_restriction/security/product_country_restriction.xml
  product_country_restriction/static/description/icon.png
  product_country_restriction/static/description/index.html
  product_country_restriction/tests/__init__.py
  product_country_restriction/tests/common.py
  product_country_restriction/tests/test_country_restriction.py
  product_country_restriction/views/product_country_restriction.xml
  product_country_restriction/views/product_country_restriction_item.xml
  product_country_restriction/views/product_country_restriction_rule.xml
  product_country_restriction/views/res_country.xml
  product_country_restriction/views/res_partner.xml
  setup/product_country_restriction/odoo/addons/product_country_restriction
  setup/product_country_restriction/setup.py
Labels: approved, bot is merging ⏳

#1467 [15.0][IMP] product_pricelist_direct_print: Get product from dictionary inside of product iteration
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
Labels: approved, bot is merging ⏳

#1469 [15.0][IMP] product_secondary_unit: Add helper method to secondary units to get secondary qty computed
  product_secondary_unit/models/product_second_unit.py
Labels: approved, bot is merging ⏳
