Repository OCA/product-attribute, pull requests merged in 2023-03, with the labels that each got.

#1282 [ADD] [15.0] product_sticker
  product_sticker/README.rst
  product_sticker/__init__.py
  product_sticker/__manifest__.py
  product_sticker/data/menus.xml
  product_sticker/models/__init__.py
  product_sticker/models/product_attribute.py
  product_sticker/models/product_attribute_value.py
  product_sticker/models/product_product.py
  product_sticker/models/product_sticker.py
  product_sticker/models/product_sticker_mixin.py
  product_sticker/models/product_template.py
  product_sticker/readme/CONTRIBUTORS.rst
  product_sticker/readme/DESCRIPTION.rst
  product_sticker/readme/USAGE.rst
  product_sticker/security/ir.model.access.csv
  product_sticker/static/description/icon.png
  product_sticker/static/description/index.html
  product_sticker/tests/__init__.py
  product_sticker/tests/common.py
  product_sticker/tests/test_product.py
  product_sticker/views/product_attribute_views.xml
  product_sticker/views/product_sticker_views.xml
  product_sticker/views/product_template_views.xml
  setup/product_sticker/odoo/addons/product_sticker
  setup/product_sticker/setup.py
Labels: approved, bot is merging ⏳

#1298 [15.0][IMP] product_pricelist_supplierinfo: New context force_filter_supplier_id
  product_pricelist_supplierinfo/models/product_template.py
Labels: approved, bot is merging ⏳

#1300 [15.0][FIX] product_abc_classification_sale: Flush data in tests
  product_abc_classification_sale/tests/test_sale_product_classification.py
  product_abc_classification_sale/tests/test_sale_product_classification_common.py
Labels: approved, bot is merging ⏳

#1225 [ADD] product_template_has_one_variant
  product_template_has_one_variant/README.rst
  product_template_has_one_variant/__init__.py
  product_template_has_one_variant/__manifest__.py
  product_template_has_one_variant/models/__init__.py
  product_template_has_one_variant/models/product_template.py
  product_template_has_one_variant/readme/CONTRIBUTORS.rst
  product_template_has_one_variant/readme/DESCRIPTION.rst
  product_template_has_one_variant/readme/USAGE.rst
  product_template_has_one_variant/static/description/icon.png
  product_template_has_one_variant/static/description/index.html
  product_template_has_one_variant/tests/__init__.py
  product_template_has_one_variant/tests/test_product_template.py
  product_template_has_one_variant/views/product_template.xml
  setup/product_template_has_one_variant/odoo/addons/product_template_has_one_variant
  setup/product_template_has_one_variant/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1306 [15.0][FIX] product_sticker: Remove get_html_sanitized_note function
  product_sticker/models/product_sticker.py
Labels: bot is merging ⏳

#1272 [13.0][FIX] product_assortment: Product black_list_domain invalidates whitelist_product_ids. New cache methods to performance
  product_assortment/__manifest__.py
  product_assortment/data/ir_cron.xml
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1246 [15.0][IMP] product_secondary_unit: Compatibility with product variants
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_product.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
Labels: approved, bot is merging ⏳

#1223 [MIG] sale_product_template_tags: Migration to 16.0
  sale_product_template_tags/README.rst
  sale_product_template_tags/__init__.py
  sale_product_template_tags/__manifest__.py
  sale_product_template_tags/i18n/ca.po
  sale_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/pt.po
  sale_product_template_tags/i18n/sale_product_template_tags.pot
  sale_product_template_tags/readme/CONTRIBUTORS.rst
  sale_product_template_tags/readme/DESCRIPTION.rst
  sale_product_template_tags/static/description/icon.png
  sale_product_template_tags/static/description/index.html
  sale_product_template_tags/views/product_template_tag.xml
  setup/sale_product_template_tags/odoo/addons/sale_product_template_tags
  setup/sale_product_template_tags/setup.py
Labels: approved, bot is merging ⏳
