Repository OCA/product-attribute, pull requests merged in 2023-02, with the labels that each got.

#1248 [15.0][MIG] product_abc_classification_sale: Migration to version 15.0
  product_abc_classification_sale/README.rst
  product_abc_classification_sale/__init__.py
  product_abc_classification_sale/__manifest__.py
  product_abc_classification_sale/i18n/product_abc_classification_sale.pot
  product_abc_classification_sale/models/__init__.py
  product_abc_classification_sale/models/abc_classification_profile.py
  product_abc_classification_sale/models/product_product.py
  product_abc_classification_sale/models/product_template.py
  product_abc_classification_sale/readme/CONTRIBUTORS.rst
  product_abc_classification_sale/readme/DESCRIPTION.rst
  product_abc_classification_sale/readme/ROADMAP.rst
  product_abc_classification_sale/readme/USAGE.rst
  product_abc_classification_sale/static/description/icon.png
  product_abc_classification_sale/static/description/index.html
  product_abc_classification_sale/tests/__init__.py
  product_abc_classification_sale/tests/test_sale_product_classification.py
  product_abc_classification_sale/tests/test_sale_product_classification_common.py
  product_abc_classification_sale/views/product_views.xml
  setup/product_abc_classification_sale/odoo/addons/product_abc_classification_sale
  setup/product_abc_classification_sale/setup.py
Labels: approved, bot is merging ⏳

#1268 [UPD] Copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1217 [16.0][ADD] stock_production_lot_expired_date
  setup/stock_production_lot_expired_date/odoo/addons/stock_production_lot_expired_date
  setup/stock_production_lot_expired_date/setup.py
  stock_production_lot_expired_date/README.rst
  stock_production_lot_expired_date/__init__.py
  stock_production_lot_expired_date/__manifest__.py
  stock_production_lot_expired_date/i18n/stock_production_lot_expired_date.pot
  stock_production_lot_expired_date/models/__init__.py
  stock_production_lot_expired_date/models/res_config_settings.py
  stock_production_lot_expired_date/models/stock_lot.py
  stock_production_lot_expired_date/readme/CONTRIBUTORS.rst
  stock_production_lot_expired_date/readme/DESCRIPTION.rst
  stock_production_lot_expired_date/readme/USAGE.rst
  stock_production_lot_expired_date/tests/__init__.py
  stock_production_lot_expired_date/tests/test_stock_production_lot_expired_date.py
  stock_production_lot_expired_date/views/res_config_settings.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1261 [FW][FIX]product_sequence: remove dependence
  product_sequence/README.rst
  product_sequence/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#1260 [FW][FIX]product_sequence: remove dependence
  product_sequence/README.rst
  product_sequence/__manifest__.py
Labels: enhancement, approved, bot is merging ⏳

#1258 [15.0][FIX+IMP] product_sequence
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_category.py
  product_sequence/tests/test_product_sequence.py
Labels: approved, ready to merge, bot is merging ⏳

#1232 [15.0][MIG] product_attribute_archive
  product_attribute_archive/README.rst
  product_attribute_archive/__init__.py
  product_attribute_archive/__manifest__.py
  product_attribute_archive/i18n/product_attribute_archive.pot
  product_attribute_archive/models/__init__.py
  product_attribute_archive/models/product_attribute.py
  product_attribute_archive/models/product_attribute_value.py
  product_attribute_archive/readme/CONTRIBUTORS.rst
  product_attribute_archive/readme/DESCRIPTION.rst
  product_attribute_archive/readme/USAGE.rst
  product_attribute_archive/static/description/icon.png
  product_attribute_archive/static/description/index.html
  product_attribute_archive/views/product_attribute.xml
  setup/product_attribute_archive/odoo/addons/product_attribute_archive
  setup/product_attribute_archive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1065 [14.0] [IMP] `base_product_mass_addition`: avoid writing on product's metadata + add tests
  base_product_mass_addition/models/product_product.py
  base_product_mass_addition/readme/CONTRIBUTORS.rst
  base_product_mass_addition/tests/__init__.py
  base_product_mass_addition/tests/models/order.py
  base_product_mass_addition/tests/test_product_mass_addition.py
Labels: approved, bot is merging ⏳, stale

#1274 [13.0][FIX] product_pricelist_direct_print: Invalid field 'message_ids' on model 'product.pricelist.print' when opening notification from odoo
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: bot is merging ⏳
