Repository OCA/product-attribute, pull requests merged in 2023-12, with the labels that each got.

#1296 [16.0][MIG] product_lot_sequence: Migration to 16.0
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/data/ir_config_parameter.xml
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/res_company.py
  product_lot_sequence/models/res_config_settings.py
  product_lot_sequence/models/stock_lot.py
  product_lot_sequence/readme/CONFIGURE.rst
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/DESCRIPTION.rst
  product_lot_sequence/readme/USAGE.rst
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  product_lot_sequence/views/res_config_settings_views.xml
  setup/product_lot_sequence/odoo/addons/product_lot_sequence
  setup/product_lot_sequence/setup.py
Labels: approved, bot is merging ⏳

#1474 [IMP] product_internal_reference_generator: stock manager access
  product_internal_reference_generator/security/ir.model.access.csv
  product_internal_reference_generator/views/product.xml
Labels: bot is merging ⏳

#1473 [17.0][MIG] product_dimension: Migration to 17.0
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/it.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/pyproject.toml
  product_dimension/readme/CONTRIBUTORS.md
  product_dimension/readme/CREDITS.md
  product_dimension/readme/DESCRIPTION.md
  product_dimension/readme/HISTORY.md
  product_dimension/readme/USAGE.md
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/tests/test_template.py
  product_dimension/views/product_view.xml
Labels: approved, bot is merging ⏳

#1480 [16.0][FIX] product_print_category fix a security issue
  product_print_category/models/product_print_category_mixin.py
Labels: bot is merging ⏳

#1475 [16.0] product_packaging_container_deposit: fix deletion of lines
  product_packaging_container_deposit/models/container_deposit_order_mixin.py
  product_packaging_container_deposit/readme/CONTRIBUTORS.rst
  product_packaging_container_deposit/tests/__init__.py
  product_packaging_container_deposit/tests/common.py
  product_packaging_container_deposit/tests/fake_models.py
  product_packaging_container_deposit/tests/test_container_deposit_order_mixin.py
Labels: bot is merging ⏳

#1452 [16.0][IMP] product_set: Merge with sale_product_set_layout
  product_set/demo/product_set_line.xml
  product_set/models/product_set_line.py
  product_set/views/product_set.xml
Labels: approved, bot is merging ⏳

#1221 [MIG][16.0] product total weight from packaging
  product_total_weight_from_packaging/i18n/product_total_weight_from_packaging.pot
  product_total_weight_from_packaging/readme/CONTRIBUTORS.rst
  product_total_weight_from_packaging/readme/DESCRIPTION.rst
  product_total_weight_from_packaging/tests/test_product_total_weight_from_packaging.py
Labels: approved, bot is merging ⏳

#1299 [14.0][ADD] product_search_by_display_name
  product_search_by_display_name/README.rst
  product_search_by_display_name/__init__.py
  product_search_by_display_name/__manifest__.py
  product_search_by_display_name/models/__init__.py
  product_search_by_display_name/models/product_product.py
  product_search_by_display_name/models/product_template.py
  product_search_by_display_name/readme/CONTRIBUTORS.rst
  product_search_by_display_name/readme/CREDITS.rst
  product_search_by_display_name/readme/DESCRIPTION.rst
  product_search_by_display_name/static/description/index.html
  product_search_by_display_name/tests/__init__.py
  product_search_by_display_name/tests/test_product_search_by_display_name.py
  product_search_by_display_name/views/product_template.xml
  setup/product_search_by_display_name/odoo/addons/product_search_by_display_name
  setup/product_search_by_display_name/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1366 [16.0][MIG] product_profile
  product_profile/README.rst
  product_profile/__init__.py
  product_profile/__manifest__.py
  product_profile/demo/profile_demo.xml
  product_profile/i18n/ca.po
  product_profile/i18n/de.po
  product_profile/i18n/es.po
  product_profile/i18n/fr.po
  product_profile/i18n/hr.po
  product_profile/i18n/it.po
  product_profile/i18n/nl_NL.po
  product_profile/i18n/product_profile.pot
  product_profile/i18n/sl.po
  product_profile/models/__init__.py
  product_profile/models/config.py
  product_profile/models/product.py
  product_profile/models/product_profile.py
  product_profile/readme/CONFIGURE.rst
  product_profile/readme/CONTRIBUTORS.rst
  product_profile/readme/DESCRIPTION.rst
  product_profile/readme/ROADMAP.rst
  product_profile/readme/USAGE.rst
  product_profile/security/group.xml
  product_profile/security/ir.model.access.csv
  product_profile/static/description/icon.png
  product_profile/static/description/index.html
  product_profile/static/img/create.png
  product_profile/static/img/field.png
  product_profile/static/img/list.png
  product_profile/views/config_view.xml
  product_profile/views/product_view.xml
  setup/product_profile/odoo/addons/product_profile
  setup/product_profile/setup.py
Labels: approved, bot is merging ⏳

#1358 [14.0][MIG] product_category_description: Migration to 14.0
  product_category_description/README.rst
  product_category_description/__init__.py
  product_category_description/__manifest__.py
  product_category_description/i18n/product_category_description.pot
  product_category_description/models/__init__.py
  product_category_description/models/product_category.py
  product_category_description/readme/CONTRIBUTORS.rst
  product_category_description/readme/DESCRIPTION.rst
  product_category_description/static/description/icon.png
  product_category_description/static/description/index.html
  product_category_description/views/product_category.xml
  setup/product_category_description/odoo/addons/product_category_description
  setup/product_category_description/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1456 [16.0] [MIG] product_product_template_navigation
  product_product_template_link/README.rst
  product_product_template_link/__init__.py
  product_product_template_link/__manifest__.py
  product_product_template_link/i18n/ca.po
  product_product_template_link/i18n/es.po
  product_product_template_link/i18n/it.po
  product_product_template_link/i18n/product_product_template_navigation.pot
  product_product_template_link/models/__init__.py
  product_product_template_link/models/product_product.py
  product_product_template_link/readme/CONTRIBUTORS.rst
  product_product_template_link/readme/DESCRIPTION.rst
  product_product_template_link/static/description/icon.png
  product_product_template_link/static/description/index.html
  product_product_template_link/static/img/template_navigation.gif
  product_product_template_link/tests/__init__.py
  product_product_template_link/tests/test_product_product_template_link.py
  product_product_template_link/views/product_product_views.xml
  setup/product_product_template_link/odoo/addons/product_product_template_link
  setup/product_product_template_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳
