Repository OCA/product-attribute, pull requests merged in 2023-06, with the labels that each got.

#1336 [IMP] product_secondary_unit: Allow skip set default value for secondary_uom_qty
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#1331 [16.0][MIG] product_pricelist_revision: Migration to version 16.0
  product_pricelist_revision/README.rst
  product_pricelist_revision/__init__.py
  product_pricelist_revision/__manifest__.py
  product_pricelist_revision/i18n/ca.po
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/it.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/models/__init__.py
  product_pricelist_revision/models/pricelist.py
  product_pricelist_revision/readme/CONFIGURE.rst
  product_pricelist_revision/readme/CONTRIBUTORS.rst
  product_pricelist_revision/readme/DESCRIPTION.rst
  product_pricelist_revision/readme/USAGE.rst
  product_pricelist_revision/security/ir.model.access.csv
  product_pricelist_revision/static/description/icon.png
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/tests/__init__.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/views/pricelist_view.xml
  product_pricelist_revision/wizards/__init__.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard_view.xml
  setup/product_pricelist_revision/odoo/addons/product_pricelist_revision
  setup/product_pricelist_revision/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1314 [16.0][FIX] product_logistics_uom: Store value in system UOM
  .copier-answers.yml
  .github/workflows/test.yml
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/hooks.py
  product_logistics_uom/migrations/16.0.2.0.0/post-migrate.py
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_product.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/readme/CONTRIBUTORS.rst
  product_logistics_uom/readme/DESCRIPTION.rst
  product_logistics_uom/readme/USAGE.rst
  product_logistics_uom/static/description/index.html
  product_logistics_uom/tests/__init__.py
  product_logistics_uom/tests/test_product_logistics_uom.py
  product_logistics_uom/views/product.xml
Labels: bot is merging ⏳

#1325 [16.0][MIG] product_secondary_unit #2
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/es_MX.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_product.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/readme/CONTRIBUTORS.rst
  product_secondary_unit/readme/DESCRIPTION.rst
  product_secondary_unit/readme/USAGE.rst
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
  setup/product_secondary_unit/odoo/addons/product_secondary_unit
  setup/product_secondary_unit/setup.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1137 [13.0][FIX]product_attribute_value_menu: Add depends on compute
  product_attribute_value_menu/models/product_attribute_value.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: approved, bot is merging ⏳, stale

#1351 [15.0][FW]product_attribute_value_menu: Add depends on compute
  product_attribute_value_menu/models/product_attribute_value.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: bot is merging ⏳

#1350 [14.0][FW]product_attribute_value_menu: Add depends on compute
  product_attribute_value_menu/models/product_attribute_value.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
Labels: bot is merging ⏳

#1348 [16.0][MIG] product_pricelist_simulation: Migration to 16.0
  product_pricelist_simulation/README.rst
  product_pricelist_simulation/__init__.py
  product_pricelist_simulation/__manifest__.py
  product_pricelist_simulation/i18n/es.po
  product_pricelist_simulation/i18n/product_pricelist_simulation.pot
  product_pricelist_simulation/models/__init__.py
  product_pricelist_simulation/models/pricelist.py
  product_pricelist_simulation/readme/CONTRIBUTORS.rst
  product_pricelist_simulation/readme/DESCRIPTION.rst
  product_pricelist_simulation/readme/USAGE.rst
  product_pricelist_simulation/security/ir.model.access.csv
  product_pricelist_simulation/static/description/icon.png
  product_pricelist_simulation/static/description/index.html
  product_pricelist_simulation/tests/__init__.py
  product_pricelist_simulation/tests/test_product_pricelist_simulation.py
  product_pricelist_simulation/views/pricelist_views.xml
  product_pricelist_simulation/views/product_views.xml
  product_pricelist_simulation/wizards/__init__.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist_views.xml
  setup/product_pricelist_simulation/odoo/addons/product_pricelist_simulation
  setup/product_pricelist_simulation/setup.py
Labels: approved, bot is merging ⏳

#1346 [15.0][IMP] product_pricelist_direct_print: Allow select the language when printing
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1343 [15.0][FIX] product_assortment: Product black_list_domain invalidates whitelist_product_ids. New cache methods to performance
  product_assortment/__manifest__.py
  product_assortment/data/ir_cron.xml
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
Labels: approved, bot is merging ⏳

#1362 [14.0][IMP] product_pricelist_assortment: sales administrator access
  product_pricelist_assortment/__manifest__.py
  product_pricelist_assortment/security/product_pricelist_assortment_item.xml
Labels: approved, bot is merging ⏳

#1038 [13.0][MIG]product exception: Migration to 13.0
  product_exception/README.rst
  product_exception/__init__.py
  product_exception/__manifest__.py
  product_exception/data/data.xml
  product_exception/demo/product_exception.xml
  product_exception/i18n/product_exception.pot
  product_exception/models/__init__.py
  product_exception/models/exception_rule.py
  product_exception/models/product_product.py
  product_exception/models/product_template.py
  product_exception/readme/CONFIGURE.rst
  product_exception/readme/CONTRIBUTORS.rst
  product_exception/readme/DESCRIPTION.rst
  product_exception/readme/ROADMAP.rst
  product_exception/readme/USAGE.rst
  product_exception/static/description/icon.png
  product_exception/static/description/index.html
  product_exception/tests/__init__.py
  product_exception/tests/test_product_exception.py
  product_exception/views/product.xml
  setup/product_exception/odoo/addons/product_exception
  setup/product_exception/setup.py
Labels: needs review, migration, bot is merging ⏳

#1354 [MIG] product_pricelist_simulation_margin: Migration to 16.0
  product_pricelist_simulation_margin/README.rst
  product_pricelist_simulation_margin/__init__.py
  product_pricelist_simulation_margin/__manifest__.py
  product_pricelist_simulation_margin/i18n/es.po
  product_pricelist_simulation_margin/i18n/product_pricelist_simulation_margin.pot
  product_pricelist_simulation_margin/readme/CONTRIBUTORS.rst
  product_pricelist_simulation_margin/readme/DESCRIPTION.rst
  product_pricelist_simulation_margin/readme/USAGE.rst
  product_pricelist_simulation_margin/static/description/product_template_form.png
  product_pricelist_simulation_margin/static/description/wizard_preview_pricelist_margin_form.png
  product_pricelist_simulation_margin/tests/__init__.py
  product_pricelist_simulation_margin/tests/test_module.py
  product_pricelist_simulation_margin/wizards/__init__.py
  product_pricelist_simulation_margin/wizards/wizard_preview_pricelist.py
  product_pricelist_simulation_margin/wizards/wizard_preview_pricelist_views.xml
  setup/product_pricelist_simulation_margin/odoo/addons/product_pricelist_simulation_margin
  setup/product_pricelist_simulation_margin/setup.py
Labels: approved, bot is merging ⏳

#1363 [14.0][FIX] product_pricelist_assortment: change id of an access rule
  product_pricelist_assortment/__manifest__.py
  product_pricelist_assortment/readme/CONTRIBUTORS.rst
  product_pricelist_assortment/security/ir.model.access.csv
  product_pricelist_assortment/security/product_pricelist_assortment_item.xml
Labels: approved, bot is merging ⏳

#1180 [15.0][MIG] product_profile
  product_profile/README.rst
  product_profile/__init__.py
  product_profile/__manifest__.py
  product_profile/demo/profile_demo.xml
  product_profile/i18n/ca.po
  product_profile/i18n/de.po
  product_profile/i18n/es.po
  product_profile/i18n/fr.po
  product_profile/i18n/hr.po
  product_profile/i18n/it.po
  product_profile/i18n/nl_NL.po
  product_profile/i18n/product_profile.pot
  product_profile/i18n/sl.po
  product_profile/migrations/15.0.1.0.0/pre-migration.py
  product_profile/models/__init__.py
  product_profile/models/config.py
  product_profile/models/product.py
  product_profile/models/product_profile.py
  product_profile/readme/CONFIGURE.rst
  product_profile/readme/CONTRIBUTORS.rst
  product_profile/readme/DESCRIPTION.rst
  product_profile/readme/ROADMAP.rst
  product_profile/readme/USAGE.rst
  product_profile/security/group.xml
  product_profile/security/ir.model.access.csv
  product_profile/static/description/icon.png
  product_profile/static/description/index.html
  product_profile/static/img/create.png
  product_profile/static/img/field.png
  product_profile/static/img/list.png
  product_profile/views/config_view.xml
  product_profile/views/product_view.xml
  setup/product_profile/odoo/addons/product_profile
  setup/product_profile/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1231 [14.0][IMP] product_pricelist_direct_print: allow export product images
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1365 [16.0] MIG product_pricelist_direct_print
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/__init__.py
  product_pricelist_direct_print/__manifest__.py
  product_pricelist_direct_print/data/mail_template_data.xml
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/fr.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONFIGURE.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/readme/DESCRIPTION.rst
  product_pricelist_direct_print/readme/USAGE.rst
  product_pricelist_direct_print/reports/report_product_pricelist.xml
  product_pricelist_direct_print/security/ir.model.access.csv
  product_pricelist_direct_print/static/description/icon.png
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/static/description/wizard_form.png
  product_pricelist_direct_print/tests/__init__.py
  product_pricelist_direct_print/tests/test_product_pricelist_direct_print.py
  product_pricelist_direct_print/wizards/__init__.py
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
  product_pricelist_direct_print_xlsx/README.rst
  product_pricelist_direct_print_xlsx/__init__.py
  product_pricelist_direct_print_xlsx/__manifest__.py
  product_pricelist_direct_print_xlsx/i18n/product_pricelist_direct_print_xlsx.pot
  product_pricelist_direct_print_xlsx/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_xlsx/readme/DESCRIPTION.rst
  product_pricelist_direct_print_xlsx/report/__init__.py
  product_pricelist_direct_print_xlsx/report/product_pricelist_xlsx.py
  product_pricelist_direct_print_xlsx/report/product_pricelist_xlsx.xml
  product_pricelist_direct_print_xlsx/security/ir.model.access.csv
  product_pricelist_direct_print_xlsx/static/description/icon.png
  product_pricelist_direct_print_xlsx/tests/__init__.py
  product_pricelist_direct_print_xlsx/tests/test_product_pricelist_direct_print_xlsx.py
  product_pricelist_direct_print_xlsx/wizards/__init__.py
  product_pricelist_direct_print_xlsx/wizards/product_pricelist_print.py
  product_pricelist_direct_print_xlsx/wizards/product_pricelist_print_view.xml
  setup/product_pricelist_direct_print/odoo/addons/product_pricelist_direct_print
  setup/product_pricelist_direct_print/setup.py
  setup/product_pricelist_direct_print_xlsx/odoo/addons/product_pricelist_direct_print_xlsx
  setup/product_pricelist_direct_print_xlsx/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1276 [MIG] 16.0: product_category_type
  product_category_type/README.rst
  product_category_type/__init__.py
  product_category_type/__manifest__.py
  product_category_type/demo/product_category.xml
  product_category_type/i18n/de.po
  product_category_type/i18n/fr.po
  product_category_type/i18n/product_category_type.pot
  product_category_type/models/__init__.py
  product_category_type/models/product_category.py
  product_category_type/models/product_template.py
  product_category_type/readme/CONTRIBUTORS.rst
  product_category_type/readme/DESCRIPTION.rst
  product_category_type/static/description/icon.png
  product_category_type/static/description/index.html
  product_category_type/static/description/product_category_tree.png
  product_category_type/static/description/product_template_form.png
  product_category_type/views/product_category.xml
  setup/product_category_type/odoo/addons/product_category_type
  setup/product_category_type/setup.py
Labels: bot is merging ⏳, stale

#1373 [MIG] product_pricelist_supplierinfo: Migration to 16.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/readme/CONFIGURE.rst
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.rst
  product_pricelist_supplierinfo/readme/DESCRIPTION.rst
  product_pricelist_supplierinfo/readme/INSTALL.rst
  product_pricelist_supplierinfo/readme/ROADMAP.rst
  product_pricelist_supplierinfo/readme/USAGE.rst
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
  setup/product_pricelist_supplierinfo/odoo/addons/product_pricelist_supplierinfo
  setup/product_pricelist_supplierinfo/setup.py
Labels: bot is merging ⏳
