Repository OCA/product-attribute, pull requests merged in 2023-07, with the labels that each got.

#1369 [FIX] product_pricelist_assortment: fix item form
  product_pricelist_assortment/views/product_pricelist_assortment_item.xml
Labels: bot is merging ⏳

#1377 [FIX] product_pricelist_supplierinfo: inherit the _compute_price method in product_pricelist model
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist.py
  product_pricelist_supplierinfo/models/product_pricelist_item.py
Labels: bot is merging ⏳

#1271 [15.0][FIX] product_supplierinfo_for_customer: Use supplierinfo also for child contacts
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
Labels: approved, bot is merging ⏳

#1099 [FIX][14.0]product_multi_image decode variant image
  product_multi_image/models/product_product.py
  product_multi_image/readme/CONFIGURE.rst
Labels: approved, ready to merge, bot is merging ⏳

#1284 [13.0][FIX] product_lot_sequence: Avoid generate extra sequences on duplicates
  product_lot_sequence/models/product.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#1382 [16.0][MIG] product_pricelist_direct_print_company_group: Migration to version 16.0
  product_pricelist_direct_print_company_group/README.rst
  product_pricelist_direct_print_company_group/__init__.py
  product_pricelist_direct_print_company_group/__manifest__.py
  product_pricelist_direct_print_company_group/i18n/es.po
  product_pricelist_direct_print_company_group/i18n/product_pricelist_direct_print_company_group.pot
  product_pricelist_direct_print_company_group/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print_company_group/readme/DESCRIPTION.rst
  product_pricelist_direct_print_company_group/readme/USAGE.rst
  product_pricelist_direct_print_company_group/static/description/icon.png
  product_pricelist_direct_print_company_group/static/description/index.html
  product_pricelist_direct_print_company_group/wizards/__init__.py
  product_pricelist_direct_print_company_group/wizards/product_pricelist_print.py
  setup/product_pricelist_direct_print_company_group/odoo/addons/product_pricelist_direct_print_company_group
  setup/product_pricelist_direct_print_company_group/setup.py
Labels: approved, bot is merging ⏳

#1220 [IMP] product_packaging_dimension: Improve view in order to easy inhe…
  product_packaging_dimension/README.rst
  product_packaging_dimension/readme/CONTRIBUTORS.rst
  product_packaging_dimension/static/description/index.html
  product_packaging_dimension/views/product_packaging.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1092 [12.0][ADD] product_dimension_compute_volume
  product_dimension/tests/test_compute_volume.py
  product_dimension_compute_volume/__init__.py
  product_dimension_compute_volume/__manifest__.py
  product_dimension_compute_volume/models/__init__.py
  product_dimension_compute_volume/models/product.py
  product_dimension_compute_volume/readme/CONTRIBUTORS.rst
  product_dimension_compute_volume/readme/DESCRIPTION.rst
  product_dimension_compute_volume/readme/ROADMAP.rst
  product_dimension_compute_volume/tests/__init__.py
  product_dimension_compute_volume/tests/test_product.py
  setup/product_dimension_compute_volume/odoo/addons/product_dimension_compute_volume
  setup/product_dimension_compute_volume/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1385 [IMP] product_price_history : add new graph view
  product_price_history/__manifest__.py
  product_price_history/i18n/fr.po
  product_price_history/models/product_price_history.py
  product_price_history/readme/CONTRIBUTORS.rst
  product_price_history/readme/USAGE.rst
  product_price_history/static/description/product_price_history_graph.png
  product_price_history/views/product_price_history_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1388 [IMP] product_secondary_unit: Allow to archive secondary units
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_template.py
Labels: bot is merging ⏳
