Repository OCA/product-attribute, pull requests merged in 2024-11, with the labels that each got.

#1657 [16.0][ADD] product_usability
  product_usability/README.rst
  product_usability/__init__.py
  product_usability/__manifest__.py
  product_usability/i18n/fr.po
  product_usability/readme/CONTRIBUTORS.rst
  product_usability/readme/DESCRIPTION.rst
  product_usability/readme/ROADMAP.rst
  product_usability/security/ir.model.access.csv
  product_usability/security/res_groups.xml
  product_usability/static/description/index.html
  product_usability/static/description/main_menu.png
  product_usability/static/description/product_menu_icon.png
  product_usability/static/description/product_menu_icon.svg
  product_usability/views/menu.xml
  setup/product_usability/odoo/addons/product_usability
  setup/product_usability/setup.py
Labels: bot is merging ⏳

#1764 [17.0][FW][FIX] uom_category_active: CI is broken. because onchange doesn't raise an error
  uom_category_active/models/uom_category.py
  uom_category_active/tests/test_uom_category_active.py
Labels: bot is merging ⏳

#1755 [17.0][FW] product_state: multiple ports from 14.0
  product_state/models/product_template.py
  product_state/security/ir.model.access.csv
  product_state/tests/test_product_state.py
  product_status/tests/test_product_status.py
Labels: approved, ready to merge, bot is merging ⏳

#1706 [17.0][MIG] product_pricelist_fixed_currency_rate: Migration to 17.0
  product_pricelist_fixed_currency_rate/README.rst
  product_pricelist_fixed_currency_rate/__init__.py
  product_pricelist_fixed_currency_rate/__manifest__.py
  product_pricelist_fixed_currency_rate/i18n/es.po
  product_pricelist_fixed_currency_rate/i18n/it.po
  product_pricelist_fixed_currency_rate/i18n/product_pricelist_fixed_currency_rate.pot
  product_pricelist_fixed_currency_rate/models/__init__.py
  product_pricelist_fixed_currency_rate/models/product_pricelist_item.py
  product_pricelist_fixed_currency_rate/models/res_currency.py
  product_pricelist_fixed_currency_rate/pyproject.toml
  product_pricelist_fixed_currency_rate/readme/CONTRIBUTORS.md
  product_pricelist_fixed_currency_rate/readme/DESCRIPTION.md
  product_pricelist_fixed_currency_rate/readme/USAGE.md
  product_pricelist_fixed_currency_rate/static/description/icon.png
  product_pricelist_fixed_currency_rate/static/description/index.html
  product_pricelist_fixed_currency_rate/tests/__init__.py
  product_pricelist_fixed_currency_rate/tests/test_product_pricelist_fixed_currency_rate.py
  product_pricelist_fixed_currency_rate/views/pricelist_views.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1580 [17.0][MIG] stock_production_lot_expired_date
  stock_production_lot_expired_date/README.rst
  stock_production_lot_expired_date/__init__.py
  stock_production_lot_expired_date/__manifest__.py
  stock_production_lot_expired_date/i18n/es.po
  stock_production_lot_expired_date/i18n/it.po
  stock_production_lot_expired_date/i18n/stock_production_lot_expired_date.pot
  stock_production_lot_expired_date/models/__init__.py
  stock_production_lot_expired_date/models/res_config_settings.py
  stock_production_lot_expired_date/models/stock_lot.py
  stock_production_lot_expired_date/pyproject.toml
  stock_production_lot_expired_date/readme/CONTRIBUTORS.md
  stock_production_lot_expired_date/readme/DESCRIPTION.md
  stock_production_lot_expired_date/readme/USAGE.md
  stock_production_lot_expired_date/static/description/icon.png
  stock_production_lot_expired_date/static/description/index.html
  stock_production_lot_expired_date/tests/__init__.py
  stock_production_lot_expired_date/tests/test_stock_production_lot_expired_date.py
  stock_production_lot_expired_date/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#1485 [16.0][MIG] product_internal_reference_generator
  product_internal_reference_generator/README.rst
  product_internal_reference_generator/__init__.py
  product_internal_reference_generator/__manifest__.py
  product_internal_reference_generator/demo/product_code_seq_demo.xml
  product_internal_reference_generator/i18n/it.po
  product_internal_reference_generator/i18n/product_internal_reference_generator.pot
  product_internal_reference_generator/models/__init__.py
  product_internal_reference_generator/models/product_code_sequence.py
  product_internal_reference_generator/models/product_product.py
  product_internal_reference_generator/models/product_template.py
  product_internal_reference_generator/readme/CONTRIBUTORS.rst
  product_internal_reference_generator/readme/DESCRIPTION.rst
  product_internal_reference_generator/readme/ROADMAP.rst
  product_internal_reference_generator/readme/USAGE.rst
  product_internal_reference_generator/security/groups.xml
  product_internal_reference_generator/security/ir.model.access.csv
  product_internal_reference_generator/static/description/icon.png
  product_internal_reference_generator/static/description/index.html
  product_internal_reference_generator/tests/__init__.py
  product_internal_reference_generator/tests/test_product_internal_reference_generator.py
  product_internal_reference_generator/views/product.xml
  setup/product_internal_reference_generator/odoo/addons/product_internal_reference_generator
  setup/product_internal_reference_generator/setup.py
Labels: approved, bot is merging ⏳

#1786 [MIG][16.0] mig product_main_supplierinfo
  product_main_supplierinfo/README.rst
  product_main_supplierinfo/__init__.py
  product_main_supplierinfo/__manifest__.py
  product_main_supplierinfo/i18n/es.po
  product_main_supplierinfo/i18n/fr.po
  product_main_supplierinfo/i18n/it.po
  product_main_supplierinfo/i18n/product_main_supplierinfo.pot
  product_main_supplierinfo/models/__init__.py
  product_main_supplierinfo/models/product_product.py
  product_main_supplierinfo/readme/CONTRIBUTORS.rst
  product_main_supplierinfo/readme/DESCRIPTION.rst
  product_main_supplierinfo/static/description/icon.png
  product_main_supplierinfo/static/description/index.html
  product_main_supplierinfo/tests/__init__.py
  product_main_supplierinfo/tests/test_product_main_supplier.py
  product_main_supplierinfo/views/product_product.xml
  setup/product_main_supplierinfo/odoo/addons/product_main_supplierinfo
  setup/product_main_supplierinfo/setup.py
Labels: approved, bot is merging ⏳
