Repository OCA/product-attribute, pull requests merged in 2024-10, with the labels that each got.

#1737 [17.0][FIX] product_print_category: Fix user has no group
  product_print_category/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#1739 [16.0][FIX] product_cost_security: apply the same logic on the label
  product_cost_security/views/product_views.xml
Labels: approved, bot is merging ⏳

#1734 [15.0][IMP] product_assortment: Add security group to only show assortments to managers
  product_assortment/__manifest__.py
  product_assortment/models/__init__.py
  product_assortment/models/ir_rule.py
  product_assortment/security/product_assortment_security.xml
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1740 [17.0] mig product_net_weight
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/es.po
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/it.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/pyproject.toml
  product_net_weight/readme/CONTRIBUTORS.md
  product_net_weight/readme/DESCRIPTION.md
  product_net_weight/readme/ROADMAP.md
  product_net_weight/readme/USAGE.md
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/tests/__init__.py
  product_net_weight/tests/test_product_net_weight.py
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
Labels: approved, bot is merging ⏳

#1576 [16.0][IMP] product_pricelist_alternative: validate alternative pricelist with based formula pricelist
  product_pricelist_alternative/i18n/fr.po
  product_pricelist_alternative/i18n/product_pricelist_alternative.pot
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/models/product_pricelist_item.py
  product_pricelist_alternative/tests/test_pricelist_alternative.py
Labels: bot is merging ⏳

#1743 [15.0][IMP] nutritional_info_stock_lot: Compute nutritional_value_ids to get initial values from product
  nutritional_info_stock_lot/models/stock_production_lot.py
Labels: approved, bot is merging ⏳

#1742 [15.0][ADD] product_ingredient: New module
  product_ingredient/README.rst
  product_ingredient/__init__.py
  product_ingredient/__manifest__.py
  product_ingredient/data/product_allergen_data.xml
  product_ingredient/hooks.py
  product_ingredient/models/__init__.py
  product_ingredient/models/product_attribute.py
  product_ingredient/models/product_attribute_value.py
  product_ingredient/models/product_ingredient.py
  product_ingredient/models/product_ingredient_value.py
  product_ingredient/models/product_product.py
  product_ingredient/models/product_template.py
  product_ingredient/models/production_lot_ingredient_value.py
  product_ingredient/models/stock_production_lot.py
  product_ingredient/readme/CONTRIBUTORS.rst
  product_ingredient/readme/DESCRIPTION.rst
  product_ingredient/readme/USAGE.rst
  product_ingredient/security/ir.model.access.csv
  product_ingredient/static/description/index.html
  product_ingredient/views/product_attribute_value_views.xml
  product_ingredient/views/product_ingredient_views.xml
  product_ingredient/views/product_views.xml
  product_ingredient/views/stock_production_lot_view.xml
  requirements.txt
  setup/product_ingredient/odoo/addons/product_ingredient
  setup/product_ingredient/setup.py
Labels: approved, bot is merging ⏳

#1732 [16.0][ADD] product_english_name module
  product_english_name/README.rst
  product_english_name/__init__.py
  product_english_name/__manifest__.py
  product_english_name/models/__init__.py
  product_english_name/models/product_template.py
  product_english_name/readme/CONFIGURE.rst
  product_english_name/readme/CONTRIBUTORS.rst
  product_english_name/readme/DESCRIPTION.rst
  product_english_name/security/groups.xml
  product_english_name/static/description/index.html
  product_english_name/static/description/screen_english.png
  product_english_name/static/description/screen_french.png
  product_english_name/views/product_template.xml
  setup/product_english_name/odoo/addons/product_english_name
  setup/product_english_name/setup.py
Labels: approved, bot is merging ⏳

#1746 [18.0][MIG] product_dimension: Migration to 18.0
  product_dimension/README.rst
  product_dimension/__init__.py
  product_dimension/__manifest__.py
  product_dimension/i18n/ca.po
  product_dimension/i18n/de.po
  product_dimension/i18n/es.po
  product_dimension/i18n/fr.po
  product_dimension/i18n/fr_FR.po
  product_dimension/i18n/it.po
  product_dimension/i18n/product_dimension.pot
  product_dimension/i18n/pt.po
  product_dimension/models/__init__.py
  product_dimension/models/product_product.py
  product_dimension/models/product_template.py
  product_dimension/pyproject.toml
  product_dimension/readme/CONTRIBUTORS.md
  product_dimension/readme/CREDITS.md
  product_dimension/readme/DESCRIPTION.md
  product_dimension/readme/HISTORY.md
  product_dimension/readme/USAGE.md
  product_dimension/static/description/icon.png
  product_dimension/static/description/index.html
  product_dimension/tests/__init__.py
  product_dimension/tests/test_compute_volume.py
  product_dimension/tests/test_template.py
  product_dimension/views/product_view.xml
Labels: approved, ready to merge, bot is merging ⏳
