Repository OCA/product-attribute, pull requests merged in 2024-09, with the labels that each got.

#1430 [16.0][ADD] product_code_regex_validation
  product_code_regex_validation/README.rst
  product_code_regex_validation/__init__.py
  product_code_regex_validation/__manifest__.py
  product_code_regex_validation/models/__init__.py
  product_code_regex_validation/models/product.py
  product_code_regex_validation/models/product_category.py
  product_code_regex_validation/readme/CONTRIBUTORS.rst
  product_code_regex_validation/readme/DESCRIPTION.rst
  product_code_regex_validation/readme/USAGE.rst
  product_code_regex_validation/static/description/icon.png
  product_code_regex_validation/static/description/index.html
  product_code_regex_validation/tests/__init__.py
  product_code_regex_validation/tests/test_product_code_regex_validation.py
  product_code_regex_validation/views/product_category.xml
  setup/product_code_regex_validation/odoo/addons/product_code_regex_validation
  setup/product_code_regex_validation/setup.py
Labels: approved, bot is merging ⏳, stale

#1602 [17.0][MIG] product_pricelist_revision
  product_pricelist_revision/README.rst
  product_pricelist_revision/__init__.py
  product_pricelist_revision/__manifest__.py
  product_pricelist_revision/i18n/ca.po
  product_pricelist_revision/i18n/es.po
  product_pricelist_revision/i18n/fr.po
  product_pricelist_revision/i18n/it.po
  product_pricelist_revision/i18n/product_pricelist_revision.pot
  product_pricelist_revision/models/__init__.py
  product_pricelist_revision/models/pricelist.py
  product_pricelist_revision/pyproject.toml
  product_pricelist_revision/readme/CONFIGURE.md
  product_pricelist_revision/readme/CONTRIBUTORS.md
  product_pricelist_revision/readme/DESCRIPTION.md
  product_pricelist_revision/readme/USAGE.md
  product_pricelist_revision/security/ir.model.access.csv
  product_pricelist_revision/static/description/icon.png
  product_pricelist_revision/static/description/index.html
  product_pricelist_revision/tests/__init__.py
  product_pricelist_revision/tests/test_product_pricelist_revision.py
  product_pricelist_revision/views/pricelist_view.xml
  product_pricelist_revision/wizards/__init__.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard.py
  product_pricelist_revision/wizards/pricelist_duplicate_wizard_view.xml
Labels: approved, bot is merging ⏳

#1723 [16.0][IMP] product_abc_classification_sale_stock: prevent ambiguous column name
  product_abc_classification_sale_stock/models/abc_classification_profile.py
Labels: approved, bot is merging ⏳

#1716 [FIX] Fixing error External ID not found on country from on click button
  product_country_restriction/models/res_country.py
Labels: approved, bot is merging ⏳

#1603 [17.0] [MIG] product_category_code: Migration to 17.0
  product_category_code/README.rst
  product_category_code/__init__.py
  product_category_code/__manifest__.py
  product_category_code/i18n/es.po
  product_category_code/i18n/it.po
  product_category_code/i18n/product_category_code.pot
  product_category_code/models/__init__.py
  product_category_code/models/product_category.py
  product_category_code/pyproject.toml
  product_category_code/readme/CONTRIBUTORS.md
  product_category_code/readme/DESCRIPTION.md
  product_category_code/static/description/icon.png
  product_category_code/static/description/index.html
  product_category_code/tests/__init__.py
  product_category_code/tests/test_category_code.py
  product_category_code/views/product_category.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1519 [15.0][IMP]product_variant_attribute_name_manager defaults depending on config_parameters
  product_variant_attribute_name_manager/models/product_attribute.py
  product_variant_attribute_name_manager/readme/CONTRIBUTORS.rst
  product_variant_attribute_name_manager/readme/DESCRIPTION.rst
Labels: enhancement, needs review, approved, bot is merging ⏳

#1532 [15.0][MIG] product_pricelist_item_list_view: backport from v16
  product_pricelist_item_list_view/README.rst
  product_pricelist_item_list_view/__init__.py
  product_pricelist_item_list_view/__manifest__.py
  product_pricelist_item_list_view/i18n/ca.po
  product_pricelist_item_list_view/i18n/de.po
  product_pricelist_item_list_view/i18n/es.po
  product_pricelist_item_list_view/i18n/fr.po
  product_pricelist_item_list_view/i18n/it.po
  product_pricelist_item_list_view/i18n/product_pricelist_item_list_view.pot
  product_pricelist_item_list_view/static/description/icon.png
  product_pricelist_item_list_view/views/pricelist_view.xml
  setup/product_pricelist_item_list_view/odoo/addons/product_pricelist_item_list_view
  setup/product_pricelist_item_list_view/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1725 [17.0][FIX] product_supplierinfo_for_customer: fix missing products in comodel search
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/models/product_product.py
Labels: approved, bot is merging ⏳

#1724 [14.0][MIG] product_route_mto: backport from v16
  product_route_mto/README.rst
  product_route_mto/__init__.py
  product_route_mto/__manifest__.py
  product_route_mto/i18n/es.po
  product_route_mto/i18n/fr_BE.po
  product_route_mto/i18n/it.po
  product_route_mto/i18n/product_route_mto.pot
  product_route_mto/models/__init__.py
  product_route_mto/models/product_template.py
  product_route_mto/readme/CONTRIBUTORS.rst
  product_route_mto/readme/DESCRIPTION.rst
  product_route_mto/static/description/icon.png
  product_route_mto/static/description/index.html
  product_route_mto/tests/__init__.py
  product_route_mto/tests/test_product_route_mto.py
  product_route_mto/views/product_template.xml
  setup/product_route_mto/odoo/addons/product_route_mto
  setup/product_route_mto/setup.py
Labels: approved, bot is merging ⏳

#1729 [FIX] product_pricelist_simulation: provide default access rule, to avoid warning in odoo log
  product_pricelist_simulation/security/ir.model.access.csv
Labels: approved, bot is merging ⏳
