Repository OCA/product-attribute, pull requests merged in 2024-06, with the labels that each got.

#1623 [16.0][IMP] product_attribute_value_menu: Add title to button to avoid warning
  product_attribute_value_menu/views/product_attribute_value_views.xml
Labels: bot is merging ⏳

#1374 [14.0][ADD] Search by category include extra categories
  product_multi_category/models/product.py
  product_multi_category/views/product_view.xml
Labels: approved, bot is merging ⏳, stale

#1435 [14.0] [ADD] product_attribute_variant_rules
  product_attribute_variant_rules/README.rst
  product_attribute_variant_rules/__init__.py
  product_attribute_variant_rules/__manifest__.py
  product_attribute_variant_rules/models/__init__.py
  product_attribute_variant_rules/models/product_attribute_rule.py
  product_attribute_variant_rules/models/product_template.py
  product_attribute_variant_rules/readme/CONTRIBUTORS.rst
  product_attribute_variant_rules/readme/DESCRIPTION.rst
  product_attribute_variant_rules/readme/USAGE.rst
  product_attribute_variant_rules/security/ir.model.access.csv
  product_attribute_variant_rules/static/description/index.html
  product_attribute_variant_rules/tests/__init__.py
  product_attribute_variant_rules/tests/test_product_attribute_variant_rules.py
  product_attribute_variant_rules/views/product_template_views.xml
  setup/product_attribute_variant_rules/odoo/addons/product_attribute_variant_rules
  setup/product_attribute_variant_rules/setup.py
Labels: needs review, approved, bot is merging ⏳

#1655 [16.0][FIX] product_pricelist_direct_print: Error when display wizard without administration permision
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: bot is merging ⏳

#1656 [16.0][FIX] product_pricelist_direct_print : Prevent access error if a user that doesn't belong to 'Administration/Access Rights' try to print pricelists.
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: bot is merging ⏳

#1654 [FIX] product_cost_security: apply to prices in supplier info too
  product_cost_security/__manifest__.py
  product_cost_security/models/__init__.py
  product_cost_security/models/product_supplierinfo.py
  product_cost_security/static/description/index.html
Labels: approved, bot is merging ⏳

#1661 [16.0][MIG] pos_product_cost_security: Migration to 16.0
  pos_product_cost_security/README.rst
  pos_product_cost_security/__init__.py
  pos_product_cost_security/__manifest__.py
  pos_product_cost_security/i18n/it.po
  pos_product_cost_security/i18n/pos_product_cost_security.pot
  pos_product_cost_security/models/__init__.py
  pos_product_cost_security/models/pos_session.py
  pos_product_cost_security/models/product_product.py
  pos_product_cost_security/readme/CONTRIBUTORS.rst
  pos_product_cost_security/readme/DESCRIPTION.rst
  pos_product_cost_security/static/description/icon.png
  pos_product_cost_security/static/description/index.html
  pos_product_cost_security/tests/__init__.py
  pos_product_cost_security/tests/test_pos_product_cost.py
  setup/pos_product_cost_security/odoo/addons/pos_product_cost_security
  setup/pos_product_cost_security/setup.py
Labels: approved, bot is merging ⏳

#1663 [FIX] product_cost_security: use view-only security for product.supplierinfo
  product_cost_security/README.rst
  product_cost_security/__manifest__.py
  product_cost_security/models/__init__.py
  product_cost_security/models/product_supplierinfo.py
  product_cost_security/readme/ROADMAP.rst
  product_cost_security/static/description/index.html
  product_cost_security/views/product_supplierinfo_views.xml
Labels: bot is merging ⏳

#1659 [16.0] [IMP] product pricelist alternative skip alternative pricelist
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/tests/common.py
  product_pricelist_alternative/tests/test_pricelist_alternative.py
Labels: approved, ready to merge, bot is merging ⏳

#1632 [17.0] [MIG] product_pricelist_supplierinfo: Migration to 17.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/pyproject.toml
  product_pricelist_supplierinfo/readme/CONFIGURE.md
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.md
  product_pricelist_supplierinfo/readme/DESCRIPTION.md
  product_pricelist_supplierinfo/readme/INSTALL.md
  product_pricelist_supplierinfo/readme/ROADMAP.md
  product_pricelist_supplierinfo/readme/USAGE.md
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
Labels: bot is merging ⏳
