Repository OCA/product-attribute, pull requests merged in 2024-12, with the labels that each got.

#1789 [18.0][MIG] product_print_category: Migration to 18.0
  product_print_category/README.rst
  product_print_category/__init__.py
  product_print_category/__manifest__.py
  product_print_category/data/report_paperformat.xml
  product_print_category/demo/product_print_category.xml
  product_print_category/demo/product_print_category_rule.xml
  product_print_category/demo/product_product.xml
  product_print_category/demo/qweb_template.xml
  product_print_category/demo/res_groups.xml
  product_print_category/i18n/es.po
  product_print_category/i18n/fr.po
  product_print_category/i18n/it.po
  product_print_category/i18n/product_print_category.pot
  product_print_category/models/__init__.py
  product_print_category/models/product_print_category.py
  product_print_category/models/product_print_category_mixin.py
  product_print_category/models/product_print_category_rule.py
  product_print_category/models/product_product.py
  product_print_category/models/product_template.py
  product_print_category/pyproject.toml
  product_print_category/readme/CONFIGURE.md
  product_print_category/readme/CONTRIBUTORS.md
  product_print_category/readme/DESCRIPTION.md
  product_print_category/readme/USAGE.md
  product_print_category/report/__init__.py
  product_print_category/report/ir_actions_report.xml
  product_print_category/report/report_pricetag.py
  product_print_category/report/report_pricetag.xml
  product_print_category/security/ir.model.access.csv
  product_print_category/security/ir_rule.xml
  product_print_category/security/res_groups.xml
  product_print_category/static/description/icon.png
  product_print_category/static/description/index.html
  product_print_category/static/description/index.png
  product_print_category/static/description/product_print_category_form.png
  product_print_category/static/description/product_print_category_rule_tree.png
  product_print_category/static/description/product_print_wizard_form.png
  product_print_category/static/description/product_product_form.png
  product_print_category/tests/__init__.py
  product_print_category/tests/test_product_print_category.py
  product_print_category/views/view_product_print_category.xml
  product_print_category/views/view_product_print_category_rule.xml
  product_print_category/views/view_product_product.xml
  product_print_category/views/view_product_template.xml
  product_print_category/wizard/__init__.py
  product_print_category/wizard/product_print_wizard.py
  product_print_category/wizard/product_print_wizard_line.py
  product_print_category/wizard/view_product_print_wizard.xml
Labels: approved, bot is merging ⏳

#1660 [17.0][MIG] product_main_supplierinfo
  product_main_supplierinfo/README.rst
  product_main_supplierinfo/__init__.py
  product_main_supplierinfo/__manifest__.py
  product_main_supplierinfo/i18n/fr.po
  product_main_supplierinfo/i18n/product_main_supplierinfo.pot
  product_main_supplierinfo/models/__init__.py
  product_main_supplierinfo/models/product_product.py
  product_main_supplierinfo/pyproject.toml
  product_main_supplierinfo/readme/CONTRIBUTORS.md
  product_main_supplierinfo/readme/DESCRIPTION.md
  product_main_supplierinfo/static/description/icon.png
  product_main_supplierinfo/static/description/index.html
  product_main_supplierinfo/tests/__init__.py
  product_main_supplierinfo/tests/test_product_main_supplier.py
  product_main_supplierinfo/views/product_product.xml
Labels: approved, bot is merging ⏳

#1816 [14.0][MIG] product_readonly_security: Migration to 14.0
  product_readonly_security/README.rst
  product_readonly_security/__init__.py
  product_readonly_security/__manifest__.py
  product_readonly_security/i18n/es.po
  product_readonly_security/i18n/product_readonly_security.pot
  product_readonly_security/models/__init__.py
  product_readonly_security/models/product_product.py
  product_readonly_security/models/product_readonly_security_mixin.py
  product_readonly_security/models/product_template.py
  product_readonly_security/readme/CONTRIBUTORS.rst
  product_readonly_security/readme/DESCRIPTION.rst
  product_readonly_security/readme/USAGE.rst
  product_readonly_security/security/product_readonly_security.xml
  product_readonly_security/static/description/icon.png
  product_readonly_security/static/description/index.html
  product_readonly_security/tests/__init__.py
  product_readonly_security/tests/test_product_readonly_security.py
  setup/product_readonly_security/odoo/addons/product_readonly_security
  setup/product_readonly_security/setup.py
Labels: approved, bot is merging ⏳

#1810 [18.0][MIG] product_main_supplierinfo: Migration to 18.0
  product_main_supplierinfo/README.rst
  product_main_supplierinfo/__init__.py
  product_main_supplierinfo/__manifest__.py
  product_main_supplierinfo/i18n/fr.po
  product_main_supplierinfo/i18n/product_main_supplierinfo.pot
  product_main_supplierinfo/models/__init__.py
  product_main_supplierinfo/models/product_product.py
  product_main_supplierinfo/pyproject.toml
  product_main_supplierinfo/readme/CONTRIBUTORS.md
  product_main_supplierinfo/readme/CREDITS.md
  product_main_supplierinfo/readme/DESCRIPTION.md
  product_main_supplierinfo/static/description/icon.png
  product_main_supplierinfo/static/description/index.html
  product_main_supplierinfo/tests/__init__.py
  product_main_supplierinfo/tests/test_product_main_supplier.py
  product_main_supplierinfo/views/product_product.xml
Labels: approved, bot is merging ⏳

#1667 [16.0][ADD] product_supplierinfo_import_by_barcode: New module
  product_supplierinfo_import_by_barcode/README.rst
  product_supplierinfo_import_by_barcode/__init__.py
  product_supplierinfo_import_by_barcode/__manifest__.py
  product_supplierinfo_import_by_barcode/i18n/es.po
  product_supplierinfo_import_by_barcode/i18n/product_supplierinfo_import_by_barcode.pot
  product_supplierinfo_import_by_barcode/models/__init__.py
  product_supplierinfo_import_by_barcode/models/product_supplierinfo_import_template.py
  product_supplierinfo_import_by_barcode/models/product_template.py
  product_supplierinfo_import_by_barcode/readme/CONFIGURE.md
  product_supplierinfo_import_by_barcode/readme/CONTRIBUTORS.md
  product_supplierinfo_import_by_barcode/readme/DESCRIPTION.md
  product_supplierinfo_import_by_barcode/readme/USAGE.md
  product_supplierinfo_import_by_barcode/security/ir.model.access.csv
  product_supplierinfo_import_by_barcode/static/description/index.html
  product_supplierinfo_import_by_barcode/tests/__init__.py
  product_supplierinfo_import_by_barcode/tests/test_product_supplierinfo_import_by_barcode.py
  product_supplierinfo_import_by_barcode/tests/test_supplier_drinks_complex_sheet.xlsx
  product_supplierinfo_import_by_barcode/tests/test_supplier_spanish_drinks.xlsx
  product_supplierinfo_import_by_barcode/views/product_supplierinfo_import_template_views.xml
  product_supplierinfo_import_by_barcode/wizards/__init__.py
  product_supplierinfo_import_by_barcode/wizards/product_supplierinfo_import.py
  product_supplierinfo_import_by_barcode/wizards/product_supplierinfo_import_views.xml
  setup/product_supplierinfo_import_by_barcode/odoo/addons/product_supplierinfo_import_by_barcode
  setup/product_supplierinfo_import_by_barcode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1781 [18.0][MIG] product_manufacturer: Migration to 18.0
  product_manufacturer/README.rst
  product_manufacturer/__init__.py
  product_manufacturer/__manifest__.py
  product_manufacturer/i18n/ar.po
  product_manufacturer/i18n/bg.po
  product_manufacturer/i18n/bs.po
  product_manufacturer/i18n/ca.po
  product_manufacturer/i18n/cs.po
  product_manufacturer/i18n/da.po
  product_manufacturer/i18n/de.po
  product_manufacturer/i18n/el.po
  product_manufacturer/i18n/es.po
  product_manufacturer/i18n/es_AR.po
  product_manufacturer/i18n/es_CR.po
  product_manufacturer/i18n/es_EC.po
  product_manufacturer/i18n/es_MX.po
  product_manufacturer/i18n/es_VE.po
  product_manufacturer/i18n/et.po
  product_manufacturer/i18n/fi.po
  product_manufacturer/i18n/fr.po
  product_manufacturer/i18n/gl.po
  product_manufacturer/i18n/hr.po
  product_manufacturer/i18n/hu.po
  product_manufacturer/i18n/it.po
  product_manufacturer/i18n/ja.po
  product_manufacturer/i18n/lt.po
  product_manufacturer/i18n/lv.po
  product_manufacturer/i18n/mk.po
  product_manufacturer/i18n/mn.po
  product_manufacturer/i18n/nb.po
  product_manufacturer/i18n/nl.po
  product_manufacturer/i18n/nl_NL.po
  product_manufacturer/i18n/pl.po
  product_manufacturer/i18n/product_manufacturer.pot
  product_manufacturer/i18n/pt.po
  product_manufacturer/i18n/pt_BR.po
  product_manufacturer/i18n/ro.po
  product_manufacturer/i18n/ru.po
  product_manufacturer/i18n/sl.po
  product_manufacturer/i18n/sr.po
  product_manufacturer/i18n/sr@latin.po
  product_manufacturer/i18n/sv.po
  product_manufacturer/i18n/tr.po
  product_manufacturer/i18n/zh_CN.po
  product_manufacturer/i18n/zh_TW.po
  product_manufacturer/models/__init__.py
  product_manufacturer/models/product_product.py
  product_manufacturer/models/product_template.py
  product_manufacturer/pyproject.toml
  product_manufacturer/readme/CONTRIBUTORS.md
  product_manufacturer/readme/DESCRIPTION.md
  product_manufacturer/static/description/icon.png
  product_manufacturer/static/description/index.html
  product_manufacturer/tests/__init__.py
  product_manufacturer/tests/test_product_manufacturer.py
  product_manufacturer/views/product_manufacturer_view.xml
Labels: approved, bot is merging ⏳

#1817 [17.0][ADD] product_document_domain
  product_document_domain/README.rst
  product_document_domain/__init__.py
  product_document_domain/__manifest__.py
  product_document_domain/i18n/es.po
  product_document_domain/models/__init__.py
  product_document_domain/models/product_product.py
  product_document_domain/models/product_template.py
  product_document_domain/pyproject.toml
  product_document_domain/readme/CONTRIBUTORS.md
  product_document_domain/readme/DESCRIPTION.md
  product_document_domain/readme/USAGE.md
  product_document_domain/static/description/icon.png
  product_document_domain/static/description/icon.svg
  product_document_domain/static/description/index.html
  product_document_domain/tests/__init__.py
  product_document_domain/tests/test_product_document_domain.py
  product_document_domain/views/product_document_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1824 [17.0][MIG] product_category_active: Migration to 17.0
  product_category_active/README.rst
  product_category_active/__init__.py
  product_category_active/__manifest__.py
  product_category_active/i18n/ca.po
  product_category_active/i18n/es.po
  product_category_active/i18n/hr.po
  product_category_active/i18n/it.po
  product_category_active/i18n/product_category_active.pot
  product_category_active/i18n/pt.po
  product_category_active/models/__init__.py
  product_category_active/models/product_category.py
  product_category_active/pyproject.toml
  product_category_active/readme/CONTRIBUTORS.md
  product_category_active/readme/DESCRIPTION.md
  product_category_active/readme/USAGE.md
  product_category_active/static/description/icon.png
  product_category_active/static/description/index.html
  product_category_active/tests/__init__.py
  product_category_active/tests/test_product_category_active.py
  product_category_active/views/product_views.xml
Labels: approved, bot is merging ⏳

#1751 [18.0][MIG] product_logistics_uom: Migration to 18.0
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/hooks.py
  product_logistics_uom/i18n/de.po
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/it.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/i18n/pt_BR.po
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_product.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/pyproject.toml
  product_logistics_uom/readme/CONFIGURE.md
  product_logistics_uom/readme/CONTRIBUTORS.md
  product_logistics_uom/readme/CREDITS.md
  product_logistics_uom/readme/DESCRIPTION.md
  product_logistics_uom/readme/INSTALL.md
  product_logistics_uom/readme/USAGE.md
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/tests/__init__.py
  product_logistics_uom/tests/test_product_logistics_uom.py
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1793 [18.0][MIG] product_pricelist_fixed_currency_rate: Migration to 18.0
  product_pricelist_fixed_currency_rate/README.rst
  product_pricelist_fixed_currency_rate/__init__.py
  product_pricelist_fixed_currency_rate/__manifest__.py
  product_pricelist_fixed_currency_rate/i18n/es.po
  product_pricelist_fixed_currency_rate/i18n/it.po
  product_pricelist_fixed_currency_rate/i18n/product_pricelist_fixed_currency_rate.pot
  product_pricelist_fixed_currency_rate/models/__init__.py
  product_pricelist_fixed_currency_rate/models/product_pricelist_item.py
  product_pricelist_fixed_currency_rate/models/res_currency.py
  product_pricelist_fixed_currency_rate/pyproject.toml
  product_pricelist_fixed_currency_rate/readme/CONTRIBUTORS.md
  product_pricelist_fixed_currency_rate/readme/DESCRIPTION.md
  product_pricelist_fixed_currency_rate/readme/USAGE.md
  product_pricelist_fixed_currency_rate/static/description/icon.png
  product_pricelist_fixed_currency_rate/static/description/index.html
  product_pricelist_fixed_currency_rate/tests/__init__.py
  product_pricelist_fixed_currency_rate/tests/test_product_pricelist_fixed_currency_rate.py
  product_pricelist_fixed_currency_rate/views/pricelist_views.xml
Labels: approved, bot is merging ⏳

#1753 [18.0][MIG] product_medical: Migration to 18.0
  product_medical/README.rst
  product_medical/__init__.py
  product_medical/__manifest__.py
  product_medical/data/in_vitro_diagnostic_data.xml
  product_medical/data/medical_data.xml
  product_medical/data/medicine_category_data.xml
  product_medical/data/ppe_category_data.xml
  product_medical/i18n/ca.po
  product_medical/i18n/de.po
  product_medical/i18n/es.po
  product_medical/i18n/it.po
  product_medical/i18n/product_medical.pot
  product_medical/migrations/18.0.1.0.0/pre-migrate.py
  product_medical/models/__init__.py
  product_medical/models/in_vitro_diagnostic.py
  product_medical/models/medical_category.py
  product_medical/models/medical_class.py
  product_medical/models/ppe_category.py
  product_medical/models/product_template.py
  product_medical/pyproject.toml
  product_medical/readme/CONTRIBUTORS.md
  product_medical/readme/CREDITS.md
  product_medical/readme/DESCRIPTION.md
  product_medical/security/ir.model.access.csv
  product_medical/static/description/icon.png
  product_medical/static/description/index.html
  product_medical/views/in_vitro_diagnostic.xml
  product_medical/views/medical_class.xml
  product_medical/views/medicine_category.xml
  product_medical/views/ppe_category.xml
  product_medical/views/product_template.xml
  requirements.txt
Labels: needs review, approved, migration, bot is merging ⏳

#1787 [18.0][MIG] product_net_weight
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/es.po
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/it.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/pyproject.toml
  product_net_weight/readme/CONTRIBUTORS.md
  product_net_weight/readme/DESCRIPTION.md
  product_net_weight/readme/ROADMAP.md
  product_net_weight/readme/USAGE.md
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/tests/__init__.py
  product_net_weight/tests/test_product_net_weight.py
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
Labels: bot is merging ⏳
