Repository OCA/product-attribute, pull requests merged in 2024-05, with the labels that each got.

#1600 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  product_set/models/product_set.py
  product_set/wizard/product_set_wizard.py
Labels: help wanted, needs review, bot is merging ⏳

#1598 [15.0][IMP] product_pricelist_direct_print: Allow define the category level to print in report
  product_pricelist_direct_print/i18n/es.po
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1559 [PORT] product_lot_sequence: #1323 from 15.0
  product_lot_sequence/README.rst
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/stock_lot.py
  product_lot_sequence/models/stock_move.py
  product_lot_sequence/readme/CONTRIBUTORS.rst
  product_lot_sequence/readme/ROADMAP.rst
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/test_product_lot_sequence.py
Labels: approved, bot is merging ⏳

#1578 [14.0][FIX] pos_product_cost_security: multi-company issues
  pos_product_cost_security/models/product_product.py
Labels: approved, ready to merge, bot is merging ⏳

#1585 [ADD][16.0] product_code_mixin
  product_code_mixin/README.rst
  product_code_mixin/__init__.py
  product_code_mixin/__manifest__.py
  product_code_mixin/models/__init__.py
  product_code_mixin/models/product.py
  product_code_mixin/readme/CONTRIBUTORS.rst
  product_code_mixin/readme/DESCRIPTION.rst
  product_code_mixin/static/description/index.html
  setup/product_code_mixin/odoo/addons/product_code_mixin
  setup/product_code_mixin/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1549 [15.0] [IMP] product_state: move access to Sales + Inventory Manager
  product_state/security/ir.model.access.csv
  product_status/tests/test_product_status.py
Labels: bot is merging ⏳

#1277 [ADD] 16.0 product_category_level module
  product_category_level/README.rst
  product_category_level/__init__.py
  product_category_level/__manifest__.py
  product_category_level/demo/product_category.xml
  product_category_level/i18n/fr.po
  product_category_level/i18n/product_category_level.pot
  product_category_level/models/__init__.py
  product_category_level/models/product_category.py
  product_category_level/readme/DESCRIPTION.rst
  product_category_level/tests/__init__.py
  product_category_level/tests/test_category_level.py
  product_category_level/views/product_category.xml
  setup/product_category_level/odoo/addons/product_category_level
  setup/product_category_level/setup.py
Labels: approved, bot is merging ⏳

#1550 [16.0] [IMP] product_state: move access to Sales + Inventory Manager
  product_state/security/ir.model.access.csv
Labels: bot is merging ⏳

#1610 [16.0][FIX] product_pricelist_direct_print: Revert commit
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: bot is merging ⏳

#1592 [17.0][MIG] product_status: Migration to 17.0
  product_status/README.rst
  product_status/__init__.py
  product_status/__manifest__.py
  product_status/data/function_deactive_default_product_state_data.xml
  product_status/data/ir_cron.xml
  product_status/data/product_state_data.xml
  product_status/i18n/es.po
  product_status/i18n/it.po
  product_status/i18n/product_status.pot
  product_status/models/__init__.py
  product_status/models/product.py
  product_status/models/product_state.py
  product_status/models/product_template.py
  product_status/pyproject.toml
  product_status/readme/CONTRIBUTORS.md
  product_status/readme/CREDITS.md
  product_status/readme/DESCRIPTION.md
  product_status/readme/ROADMAP.md
  product_status/static/description/icon.png
  product_status/static/description/index.html
  product_status/tests/__init__.py
  product_status/tests/test_product_status.py
  product_status/views/product_views.xml
Labels: needs review, migration, bot is merging ⏳

#1389 [MIG][16.0] product_origin
  product_origin/README.rst
  product_origin/__init__.py
  product_origin/__manifest__.py
  product_origin/i18n/fr.po
  product_origin/models/__init__.py
  product_origin/models/product_product.py
  product_origin/models/product_template.py
  product_origin/readme/CONTRIBUTORS.rst
  product_origin/readme/DESCRIPTION.rst
  product_origin/readme/HISTORY.rst
  product_origin/readme/USAGE.rst
  product_origin/static/description/icon.png
  product_origin/static/description/index.html
  product_origin/static/description/product_form.png
  product_origin/tests/__init__.py
  product_origin/tests/test_module.py
  product_origin/views/product_product.xml
  product_origin/views/product_template.xml
  setup/product_origin/odoo/addons/product_origin
  setup/product_origin/setup.py
Labels: needs review, migration, bot is merging ⏳

#1472 [16.0][mig] product_standard_price_tax_included
  product_standard_price_tax_included/README.rst
  product_standard_price_tax_included/__init__.py
  product_standard_price_tax_included/__manifest__.py
  product_standard_price_tax_included/demo/account_tax.xml
  product_standard_price_tax_included/demo/product_pricelist.xml
  product_standard_price_tax_included/demo/product_product.xml
  product_standard_price_tax_included/i18n/ca.po
  product_standard_price_tax_included/i18n/de.po
  product_standard_price_tax_included/i18n/es.po
  product_standard_price_tax_included/i18n/fr.po
  product_standard_price_tax_included/i18n/product_standard_price_tax_included.pot
  product_standard_price_tax_included/i18n/sl.po
  product_standard_price_tax_included/models/__init__.py
  product_standard_price_tax_included/models/product_pricelist_item.py
  product_standard_price_tax_included/models/product_product.py
  product_standard_price_tax_included/models/product_template.py
  product_standard_price_tax_included/readme/CONFIGURE.rst
  product_standard_price_tax_included/readme/CONTRIBUTORS.rst
  product_standard_price_tax_included/readme/DESCRIPTION.rst
  product_standard_price_tax_included/static/description/icon.png
  product_standard_price_tax_included/static/description/index.html
  product_standard_price_tax_included/static/description/product_pricelist_item_form.png
  product_standard_price_tax_included/static/description/sale_order_form_with_module.png
  product_standard_price_tax_included/static/description/sale_order_form_without_module.png
  product_standard_price_tax_included/tests/__init__.py
  product_standard_price_tax_included/tests/test_module.py
  setup/product_standard_price_tax_included/odoo/addons/product_standard_price_tax_included
  setup/product_standard_price_tax_included/setup.py
Labels: bot is merging ⏳

#1508 [17.0][MIG] product_supplierinfo_for_customer: Migration to 17.0
  product_supplierinfo_for_customer/README.rst
  product_supplierinfo_for_customer/__init__.py
  product_supplierinfo_for_customer/__manifest__.py
  product_supplierinfo_for_customer/demo/product_demo.xml
  product_supplierinfo_for_customer/i18n/ca.po
  product_supplierinfo_for_customer/i18n/de.po
  product_supplierinfo_for_customer/i18n/es.po
  product_supplierinfo_for_customer/i18n/fr.po
  product_supplierinfo_for_customer/i18n/it.po
  product_supplierinfo_for_customer/i18n/product_supplierinfo_for_customer.pot
  product_supplierinfo_for_customer/i18n/pt_BR.po
  product_supplierinfo_for_customer/i18n/sl.po
  product_supplierinfo_for_customer/models/__init__.py
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/models/product_pricelist.py
  product_supplierinfo_for_customer/models/product_product.py
  product_supplierinfo_for_customer/models/product_supplierinfo.py
  product_supplierinfo_for_customer/models/product_template.py
  product_supplierinfo_for_customer/models/res_partner.py
  product_supplierinfo_for_customer/pyproject.toml
  product_supplierinfo_for_customer/readme/CONFIGURE.md
  product_supplierinfo_for_customer/readme/CONTRIBUTORS.md
  product_supplierinfo_for_customer/readme/DESCRIPTION.md
  product_supplierinfo_for_customer/readme/ROADMAP.md
  product_supplierinfo_for_customer/readme/USAGE.md
  product_supplierinfo_for_customer/security/ir.model.access.csv
  product_supplierinfo_for_customer/static/description/icon.png
  product_supplierinfo_for_customer/static/description/index.html
  product_supplierinfo_for_customer/static/xls/product_customerinfo.xls
  product_supplierinfo_for_customer/tests/__init__.py
  product_supplierinfo_for_customer/tests/test_product_supplierinfo_for_customer.py
  product_supplierinfo_for_customer/views/product_views.xml
Labels: approved, bot is merging ⏳

#1616 [16.0][FIX] product_optional_product_quantity: Fix warning labels optional products
  product_optional_product_quantity/i18n/es.po
  product_optional_product_quantity/i18n/it.po
  product_optional_product_quantity/i18n/product_optional_product_quantity.pot
  product_optional_product_quantity/models/product_template.py
Labels: bot is merging ⏳

#1604 [15.0][FIX] base_product_mass_addition: _complete_quick_line_vals function.
  base_product_mass_addition/models/product_mass_addition.py
Labels: approved, ready to merge, bot is merging ⏳

#1612 [IMP] product_print_category: Do not write on 'to_print' when printing on product if 'to_print' is not flagged.
  product_print_category/report/report_pricetag.py
Labels: bot is merging ⏳

#1588 [16.0][ADD] product_category_product_qty
  product_category_product_qty/README.rst
  product_category_product_qty/__init__.py
  product_category_product_qty/__manifest__.py
  product_category_product_qty/l10n/fr.po
  product_category_product_qty/models/__init__.py
  product_category_product_qty/models/product_category.py
  product_category_product_qty/readme/CONTRIBUTORS.rst
  product_category_product_qty/readme/DESCRIPTION.rst
  product_category_product_qty/static/description/index.html
  product_category_product_qty/static/description/product_category_form.png
  product_category_product_qty/static/description/product_category_tree.png
  product_category_product_qty/tests/__init__.py
  product_category_product_qty/tests/test_product_category_product_qty.py
  product_category_product_qty/views/view_product_category.xml
  setup/product_category_product_qty/odoo/addons/product_category_product_qty
  setup/product_category_product_qty/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
