Repository OCA/product-attribute, pull requests merged in 2024-08, with the labels that each got.

#1693 [16.0][MIG] product_code_mandatory
  product_code_mandatory/README.rst
  product_code_mandatory/__init__.py
  product_code_mandatory/__manifest__.py
  product_code_mandatory/data/product_code_seq.xml
  product_code_mandatory/i18n/ca.po
  product_code_mandatory/i18n/fr.po
  product_code_mandatory/i18n/fr_FR.po
  product_code_mandatory/i18n/it.po
  product_code_mandatory/i18n/product_code_mandatory.pot
  product_code_mandatory/i18n/pt.po
  product_code_mandatory/models/__init__.py
  product_code_mandatory/models/product.py
  product_code_mandatory/readme/CONTRIBUTORS.rst
  product_code_mandatory/readme/DESCRIPTION.rst
  product_code_mandatory/readme/USAGE.rst
  product_code_mandatory/static/description/icon.png
  product_code_mandatory/static/description/index.html
  product_code_mandatory/tests/__init__.py
  product_code_mandatory/tests/test_product_code.py
  product_code_mandatory/views/product_view.xml
  setup/product_code_mandatory/odoo/addons/product_code_mandatory
  setup/product_code_mandatory/setup.py
Labels: approved, bot is merging ⏳

#1697 [17.0][MIG] product_code_mandatory
  product_code_mandatory/README.rst
  product_code_mandatory/__init__.py
  product_code_mandatory/__manifest__.py
  product_code_mandatory/data/product_code_seq.xml
  product_code_mandatory/i18n/ca.po
  product_code_mandatory/i18n/fr.po
  product_code_mandatory/i18n/fr_FR.po
  product_code_mandatory/i18n/it.po
  product_code_mandatory/i18n/product_code_mandatory.pot
  product_code_mandatory/i18n/pt.po
  product_code_mandatory/models/__init__.py
  product_code_mandatory/models/product.py
  product_code_mandatory/pyproject.toml
  product_code_mandatory/readme/CONTRIBUTORS.md
  product_code_mandatory/readme/DESCRIPTION.md
  product_code_mandatory/readme/USAGE.md
  product_code_mandatory/static/description/icon.png
  product_code_mandatory/static/description/index.html
  product_code_mandatory/tests/__init__.py
  product_code_mandatory/tests/test_product_code.py
  product_code_mandatory/views/product_view.xml
Labels: approved, bot is merging ⏳

#1564 [17.0][MIG] uom category active
  uom_category_active/README.rst
  uom_category_active/__init__.py
  uom_category_active/__manifest__.py
  uom_category_active/i18n/it.po
  uom_category_active/i18n/uom_category_active.pot
  uom_category_active/models/__init__.py
  uom_category_active/models/uom_category.py
  uom_category_active/pyproject.toml
  uom_category_active/readme/CONTRIBUTORS.md
  uom_category_active/readme/DESCRIPTION.md
  uom_category_active/readme/USAGE.md
  uom_category_active/static/description/icon.png
  uom_category_active/static/description/index.html
  uom_category_active/tests/__init__.py
  uom_category_active/tests/test_uom_category_active.py
  uom_category_active/views/uom_category_views.xml
Labels: bot is merging ⏳, stale

#1628 [17.0][MIG] product_packaging_dimension: Migration to 17.0
  product_packaging_dimension/README.rst
  product_packaging_dimension/__init__.py
  product_packaging_dimension/__manifest__.py
  product_packaging_dimension/i18n/ca.po
  product_packaging_dimension/i18n/de.po
  product_packaging_dimension/i18n/es.po
  product_packaging_dimension/i18n/it.po
  product_packaging_dimension/i18n/product_packaging_dimension.pot
  product_packaging_dimension/models/__init__.py
  product_packaging_dimension/models/product_packaging.py
  product_packaging_dimension/pyproject.toml
  product_packaging_dimension/readme/CONTRIBUTORS.md
  product_packaging_dimension/readme/DESCRIPTION.md
  product_packaging_dimension/static/description/icon.png
  product_packaging_dimension/static/description/index.html
  product_packaging_dimension/tests/__init__.py
  product_packaging_dimension/tests/test_packaging_volume.py
  product_packaging_dimension/views/product_packaging.xml
Labels: approved, ready to merge, bot is merging ⏳

#1704 [13.0][ADD] product_readonly_security: New module
  product_readonly_security/README.rst
  product_readonly_security/__init__.py
  product_readonly_security/__manifest__.py
  product_readonly_security/i18n/es.po
  product_readonly_security/i18n/product_readonly_security.pot
  product_readonly_security/models/__init__.py
  product_readonly_security/models/product_product.py
  product_readonly_security/models/product_readonly_security_mixin.py
  product_readonly_security/models/product_template.py
  product_readonly_security/readme/CONTRIBUTORS.rst
  product_readonly_security/readme/DESCRIPTION.rst
  product_readonly_security/readme/USAGE.rst
  product_readonly_security/security/product_readonly_security.xml
  product_readonly_security/static/description/icon.png
  product_readonly_security/tests/__init__.py
  product_readonly_security/tests/test_product_readonly_security.py
  setup/product_readonly_security/odoo/addons/product_readonly_security
  setup/product_readonly_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1484 [17.0][MIG] sale_product_template_tags: Migration to 17.0
  sale_product_template_tags/README.rst
  sale_product_template_tags/__init__.py
  sale_product_template_tags/__manifest__.py
  sale_product_template_tags/i18n/ca.po
  sale_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/pt.po
  sale_product_template_tags/i18n/pt_BR.po
  sale_product_template_tags/i18n/sale_product_template_tags.pot
  sale_product_template_tags/pyproject.toml
  sale_product_template_tags/readme/CONTRIBUTORS.md
  sale_product_template_tags/readme/DESCRIPTION.md
  sale_product_template_tags/static/description/icon.png
  sale_product_template_tags/static/description/index.html
  sale_product_template_tags/views/product_template_tag.xml
Labels: approved, ready to merge, bot is merging ⏳

#1687 [17.0][IMP] product_supplierinfo_for_customer: add search view
  product_supplierinfo_for_customer/models/product_customerinfo.py
  product_supplierinfo_for_customer/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1607 [17.0] [MIG] product_print_category
  product_print_category/README.rst
  product_print_category/__init__.py
  product_print_category/__manifest__.py
  product_print_category/data/report_paperformat.xml
  product_print_category/demo/product_print_category.xml
  product_print_category/demo/product_print_category_rule.xml
  product_print_category/demo/product_product.xml
  product_print_category/demo/qweb_template.xml
  product_print_category/demo/res_groups.xml
  product_print_category/i18n/es.po
  product_print_category/i18n/fr.po
  product_print_category/i18n/it.po
  product_print_category/i18n/product_print_category.pot
  product_print_category/models/__init__.py
  product_print_category/models/product_print_category.py
  product_print_category/models/product_print_category_mixin.py
  product_print_category/models/product_print_category_rule.py
  product_print_category/models/product_product.py
  product_print_category/models/product_template.py
  product_print_category/pyproject.toml
  product_print_category/readme/CONFIGURE.md
  product_print_category/readme/CONTRIBUTORS.md
  product_print_category/readme/DESCRIPTION.md
  product_print_category/readme/USAGE.md
  product_print_category/report/__init__.py
  product_print_category/report/ir_actions_report.xml
  product_print_category/report/report_pricetag.py
  product_print_category/report/report_pricetag.xml
  product_print_category/security/ir.model.access.csv
  product_print_category/security/ir_rule.xml
  product_print_category/security/res_groups.xml
  product_print_category/static/description/icon.png
  product_print_category/static/description/index.html
  product_print_category/static/description/index.png
  product_print_category/static/description/product_print_category_form.png
  product_print_category/static/description/product_print_category_rule_tree.png
  product_print_category/static/description/product_print_wizard_form.png
  product_print_category/static/description/product_product_form.png
  product_print_category/tests/__init__.py
  product_print_category/tests/test_product_print_category.py
  product_print_category/views/view_product_print_category.xml
  product_print_category/views/view_product_print_category_rule.xml
  product_print_category/views/view_product_product.xml
  product_print_category/views/view_product_template.xml
  product_print_category/wizard/__init__.py
  product_print_category/wizard/product_print_wizard.py
  product_print_category/wizard/product_print_wizard_line.py
  product_print_category/wizard/view_product_print_wizard.xml
Labels: approved, bot is merging ⏳
