Repository OCA/product-attribute, pull requests merged in 2024-07, with the labels that each got.

#1583 [16.0][FIX] product_packaging_container_deposit : performance
  product_packaging_container_deposit/models/container_deposit_order_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#1679 [16.0][IMP] product_pricelist_direct_print: printing a pricelist and selecting an product category, include its child categories.
  product_pricelist_direct_print/README.rst
  product_pricelist_direct_print/i18n/product_pricelist_direct_print.pot
  product_pricelist_direct_print/readme/CONTRIBUTORS.rst
  product_pricelist_direct_print/static/description/index.html
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1682 [16.0][FIX] product_assortment: Product black_list_domain invalidates whitelist_product_ids. New cache methods to performance
  product_assortment/__manifest__.py
  product_assortment/data/ir_cron.xml
  product_assortment/i18n/es.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/static/description/index.html
Labels: approved, bot is merging ⏳

#1568 [17.0][MIG] product_code_unique: migration to 17.0
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/ca.po
  product_code_unique/i18n/de.po
  product_code_unique/i18n/es.po
  product_code_unique/i18n/fr.po
  product_code_unique/i18n/fr_FR.po
  product_code_unique/i18n/it.po
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/i18n/pt.po
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/pyproject.toml
  product_code_unique/readme/CONTRIBUTORS.md
  product_code_unique/readme/DESCRIPTION.md
  product_code_unique/readme/ROADMAP.md
  product_code_unique/readme/USAGE.md
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
Labels: approved, bot is merging ⏳

#1606 [17.0] [MIG] product_logistics_uom: Migration to 17.0
  product_logistics_uom/README.rst
  product_logistics_uom/__init__.py
  product_logistics_uom/__manifest__.py
  product_logistics_uom/hooks.py
  product_logistics_uom/i18n/de.po
  product_logistics_uom/i18n/es.po
  product_logistics_uom/i18n/it.po
  product_logistics_uom/i18n/product_logistics_uom.pot
  product_logistics_uom/i18n/pt_BR.po
  product_logistics_uom/models/__init__.py
  product_logistics_uom/models/product_product.py
  product_logistics_uom/models/product_template.py
  product_logistics_uom/models/res_config_settings.py
  product_logistics_uom/pyproject.toml
  product_logistics_uom/readme/CONFIGURE.md
  product_logistics_uom/readme/CONTRIBUTORS.md
  product_logistics_uom/readme/CREDITS.md
  product_logistics_uom/readme/DESCRIPTION.md
  product_logistics_uom/readme/INSTALL.md
  product_logistics_uom/readme/USAGE.md
  product_logistics_uom/static/description/icon.png
  product_logistics_uom/static/description/index.html
  product_logistics_uom/tests/__init__.py
  product_logistics_uom/tests/test_product_logistics_uom.py
  product_logistics_uom/views/product.xml
  product_logistics_uom/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1505 [16.0][IMP] `product_template_tag`: add parent tags
  product_template_tags/models/product_template_tag.py
  product_template_tags/views/product_template_tag.xml
Labels: approved, bot is merging ⏳, stale

#1621 [17.0] [MIG] product_supplierinfo_revision: Migration to 17.0
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/ca.po
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/it.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/pyproject.toml
  product_supplierinfo_revision/readme/CONTRIBUTORS.md
  product_supplierinfo_revision/readme/DESCRIPTION.md
  product_supplierinfo_revision/readme/USAGE.md
  product_supplierinfo_revision/security/ir.model.access.csv
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
Labels: approved, bot is merging ⏳

#1698 [16.0][MIG] product_sticker: Migration to 16.0
  product_sticker/README.rst
  product_sticker/__init__.py
  product_sticker/__manifest__.py
  product_sticker/data/menus.xml
  product_sticker/i18n/es.po
  product_sticker/i18n/it.po
  product_sticker/i18n/product_sticker.pot
  product_sticker/models/__init__.py
  product_sticker/models/product_attribute.py
  product_sticker/models/product_attribute_value.py
  product_sticker/models/product_product.py
  product_sticker/models/product_sticker.py
  product_sticker/models/product_sticker_mixin.py
  product_sticker/models/product_template.py
  product_sticker/readme/CONTRIBUTORS.rst
  product_sticker/readme/DESCRIPTION.rst
  product_sticker/readme/USAGE.rst
  product_sticker/security/ir.model.access.csv
  product_sticker/static/description/icon.png
  product_sticker/static/description/index.html
  product_sticker/tests/__init__.py
  product_sticker/tests/common.py
  product_sticker/tests/test_product.py
  product_sticker/views/product_attribute_views.xml
  product_sticker/views/product_sticker_views.xml
  product_sticker/views/product_template_views.xml
  setup/product_sticker/odoo/addons/product_sticker
  setup/product_sticker/setup.py
Labels: approved, bot is merging ⏳

#1699 [16.0][IMP] product_abc_classification_sale_stock: add hook for querying the profile data
  product_abc_classification_sale_stock/models/abc_classification_profile.py
Labels: approved, bot is merging ⏳

#1694 [16.0][IMP] product_abc_classification: allow setting profiles at category
  product_abc_classification/__manifest__.py
  product_abc_classification/models/__init__.py
  product_abc_classification/models/product_category.py
  product_abc_classification/models/product_product.py
  product_abc_classification/tests/test_product.py
  product_abc_classification/views/product_category.xml
  product_abc_classification/views/product_template.xml
Labels: approved, bot is merging ⏳
