Repository OCA/product-attribute, pull requests merged in 2025-03, with the labels that each got.

#1906 [18.0] [MIG] product_barcode_required
  product_barcode_required/README.rst
  product_barcode_required/__init__.py
  product_barcode_required/__manifest__.py
  product_barcode_required/i18n/ca.po
  product_barcode_required/i18n/es.po
  product_barcode_required/i18n/it.po
  product_barcode_required/i18n/product_barcode_required.pot
  product_barcode_required/models/__init__.py
  product_barcode_required/models/product_barcode_mixin.py
  product_barcode_required/models/product_product.py
  product_barcode_required/models/product_template.py
  product_barcode_required/models/res_company.py
  product_barcode_required/models/res_config_settings.py
  product_barcode_required/pyproject.toml
  product_barcode_required/readme/CONFIGURE.md
  product_barcode_required/readme/CONTRIBUTORS.md
  product_barcode_required/readme/DESCRIPTION.md
  product_barcode_required/static/description/icon.png
  product_barcode_required/static/description/index.html
  product_barcode_required/tests/__init__.py
  product_barcode_required/tests/test_barcode.py
  product_barcode_required/views/product_template_view.xml
  product_barcode_required/views/product_view.xml
  product_barcode_required/views/res_config_settings.xml
Labels: bot is merging ⏳

#1805 [18.0][MIG] product_template_tags_code: Migration to 18.0 (renamed `product_tags_code`)
  product_tags_code/README.rst
  product_tags_code/__init__.py
  product_tags_code/__manifest__.py
  product_tags_code/i18n/es.po
  product_tags_code/i18n/it.po
  product_tags_code/i18n/product_tags_code.pot
  product_tags_code/models/__init__.py
  product_tags_code/models/product_tag.py
  product_tags_code/pyproject.toml
  product_tags_code/readme/CONFIGURE.md
  product_tags_code/readme/CONTRIBUTORS.md
  product_tags_code/readme/CREDITS.md
  product_tags_code/readme/DESCRIPTION.md
  product_tags_code/static/description/icon.png
  product_tags_code/static/description/index.html
  product_tags_code/tests/__init__.py
  product_tags_code/tests/test_product_tags_code.py
  product_tags_code/views/product_tag_views.xml
Labels: approved, bot is merging ⏳

#1903 [18.0][MIG] product_secondary_unit: Migration to version 18.0
  product_secondary_unit/README.rst
  product_secondary_unit/__init__.py
  product_secondary_unit/__manifest__.py
  product_secondary_unit/i18n/es.po
  product_secondary_unit/i18n/es_MX.po
  product_secondary_unit/i18n/fr.po
  product_secondary_unit/i18n/it.po
  product_secondary_unit/i18n/product_secondary_unit.pot
  product_secondary_unit/i18n/pt_BR.po
  product_secondary_unit/i18n/zh_CN.po
  product_secondary_unit/models/__init__.py
  product_secondary_unit/models/product_product.py
  product_secondary_unit/models/product_second_unit.py
  product_secondary_unit/models/product_secondary_unit_mixin.py
  product_secondary_unit/models/product_template.py
  product_secondary_unit/pyproject.toml
  product_secondary_unit/readme/CONTRIBUTORS.md
  product_secondary_unit/readme/DESCRIPTION.md
  product_secondary_unit/readme/USAGE.md
  product_secondary_unit/security/ir.model.access.csv
  product_secondary_unit/static/description/icon.png
  product_secondary_unit/static/description/index.html
  product_secondary_unit/tests/__init__.py
  product_secondary_unit/tests/models.py
  product_secondary_unit/tests/test_product_second_unit.py
  product_secondary_unit/tests/test_secondary_unit_mixin.py
  product_secondary_unit/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1852 [16.0][ADD] product_list_price_from_pricelist: Automatically compute product list prices based on a pricelist.
  product_list_price_from_pricelist/README.rst
  product_list_price_from_pricelist/__init__.py
  product_list_price_from_pricelist/__manifest__.py
  product_list_price_from_pricelist/data/cron.xml
  product_list_price_from_pricelist/i18n/es.po
  product_list_price_from_pricelist/i18n/product_list_price_from_pricelist.pot
  product_list_price_from_pricelist/models/__init__.py
  product_list_price_from_pricelist/models/product_pricelist.py
  product_list_price_from_pricelist/models/res_company.py
  product_list_price_from_pricelist/models/res_config_settings.py
  product_list_price_from_pricelist/readme/CONFIGURE.rst
  product_list_price_from_pricelist/readme/CONTRIBUTORS.rst
  product_list_price_from_pricelist/readme/DESCRIPTION.rst
  product_list_price_from_pricelist/readme/ROADMAP.rst
  product_list_price_from_pricelist/readme/USAGE.rst
  product_list_price_from_pricelist/static/description/index.html
  product_list_price_from_pricelist/tests/__init__.py
  product_list_price_from_pricelist/tests/test_pricelist.py
  product_list_price_from_pricelist/views/res_config_settings_views.xml
  setup/product_list_price_from_pricelist/odoo/addons/product_list_price_from_pricelist
  setup/product_list_price_from_pricelist/setup.py
Labels: approved, bot is merging ⏳

#1796 [18.0][MIG] product_status: Migration to 18.0
  product_status/README.rst
  product_status/__init__.py
  product_status/__manifest__.py
  product_status/data/function_deactive_default_product_state_data.xml
  product_status/data/ir_cron.xml
  product_status/data/product_state_data.xml
  product_status/i18n/es.po
  product_status/i18n/it.po
  product_status/i18n/product_status.pot
  product_status/models/__init__.py
  product_status/models/product.py
  product_status/models/product_state.py
  product_status/models/product_template.py
  product_status/pyproject.toml
  product_status/readme/CONTRIBUTORS.md
  product_status/readme/CREDITS.md
  product_status/readme/DESCRIPTION.md
  product_status/readme/ROADMAP.md
  product_status/static/description/icon.png
  product_status/static/description/index.html
  product_status/tests/__init__.py
  product_status/tests/test_product_status.py
  product_status/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1808 [18.0][MIG] product_packaging_level_salable: Migration to 18.0
  product_packaging_level_salable/README.rst
  product_packaging_level_salable/__init__.py
  product_packaging_level_salable/__manifest__.py
  product_packaging_level_salable/i18n/es.po
  product_packaging_level_salable/i18n/it.po
  product_packaging_level_salable/i18n/product_packaging_level_salable.pot
  product_packaging_level_salable/models/__init__.py
  product_packaging_level_salable/models/product_packaging.py
  product_packaging_level_salable/models/product_packaging_level.py
  product_packaging_level_salable/models/sale_order_line.py
  product_packaging_level_salable/pyproject.toml
  product_packaging_level_salable/readme/CONFIGURE.md
  product_packaging_level_salable/readme/CONTRIBUTORS.md
  product_packaging_level_salable/readme/CREDITS.md
  product_packaging_level_salable/readme/DESCRIPTION.md
  product_packaging_level_salable/static/description/icon.png
  product_packaging_level_salable/static/description/index.html
  product_packaging_level_salable/tests/__init__.py
  product_packaging_level_salable/tests/common.py
  product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
  product_packaging_level_salable/views/product_packaging_level.xml
Labels: approved, migration, bot is merging ⏳

#1669 [17.0] [MIG] product_packaging_level_salable: Migration to 17.0
  product_packaging_level_salable/README.rst
  product_packaging_level_salable/__init__.py
  product_packaging_level_salable/__manifest__.py
  product_packaging_level_salable/i18n/es.po
  product_packaging_level_salable/i18n/it.po
  product_packaging_level_salable/i18n/product_packaging_level_salable.pot
  product_packaging_level_salable/models/__init__.py
  product_packaging_level_salable/models/product_packaging.py
  product_packaging_level_salable/models/product_packaging_level.py
  product_packaging_level_salable/models/sale_order_line.py
  product_packaging_level_salable/pyproject.toml
  product_packaging_level_salable/readme/CONFIGURE.md
  product_packaging_level_salable/readme/CONTRIBUTORS.md
  product_packaging_level_salable/readme/CREDITS.md
  product_packaging_level_salable/readme/DESCRIPTION.md
  product_packaging_level_salable/static/description/icon.png
  product_packaging_level_salable/static/description/index.html
  product_packaging_level_salable/tests/__init__.py
  product_packaging_level_salable/tests/common.py
  product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
  product_packaging_level_salable/views/product_packaging_level.xml
Labels: bot is merging ⏳

#1828 [18.0][IMP] product_set: add packaging for product.set.line
  product_set/models/product_set_line.py
  product_set/readme/CONTRIBUTORS.md
  product_set/tests/__init__.py
  product_set/tests/test_product_set_line.py
  product_set/views/product_set.xml
  product_set/views/product_set_line.xml
Labels: approved, bot is merging ⏳

#1911 [18.0][MIG] stock_lot_production_date
  stock_lot_production_date/README.rst
  stock_lot_production_date/__init__.py
  stock_lot_production_date/__manifest__.py
  stock_lot_production_date/i18n/ca.po
  stock_lot_production_date/i18n/es.po
  stock_lot_production_date/i18n/fr.po
  stock_lot_production_date/i18n/it.po
  stock_lot_production_date/i18n/stock_lot_production_date.pot
  stock_lot_production_date/models/__init__.py
  stock_lot_production_date/models/stock_lot.py
  stock_lot_production_date/pyproject.toml
  stock_lot_production_date/readme/CONTRIBUTORS.md
  stock_lot_production_date/readme/CREDITS.md
  stock_lot_production_date/readme/DESCRIPTION.md
  stock_lot_production_date/readme/USAGE.md
  stock_lot_production_date/static/description/icon.png
  stock_lot_production_date/static/description/index.html
  stock_lot_production_date/static/description/lot.png
  stock_lot_production_date/views/stock_lot.xml
Labels: migration, bot is merging ⏳

#1915 [FIX] volume_uom_id is ambiguous
  product_logistics_uom/hooks.py
Labels: bot is merging ⏳

#1777 [16.0][FIX] product_supplierinfo_stock_picking_type: rename on change picking type method
  product_supplierinfo_stock_picking_type/models/purchase_order.py
  product_supplierinfo_stock_picking_type/tests/test_product_supplierinfo_stock_picking_type.py
Labels: approved, ready to merge, bot is merging ⏳

#1798 [18.0][MIG] product_packaging_unit_price_calculator: Migration to 18.0
  product_packaging_unit_price_calculator/README.rst
  product_packaging_unit_price_calculator/__init__.py
  product_packaging_unit_price_calculator/__manifest__.py
  product_packaging_unit_price_calculator/i18n/es.po
  product_packaging_unit_price_calculator/i18n/product_packaging_unit_price_calculator.pot
  product_packaging_unit_price_calculator/models/__init__.py
  product_packaging_unit_price_calculator/models/product.py
  product_packaging_unit_price_calculator/models/product_packaging.py
  product_packaging_unit_price_calculator/models/product_pricelist.py
  product_packaging_unit_price_calculator/models/product_supplierinfo.py
  product_packaging_unit_price_calculator/pyproject.toml
  product_packaging_unit_price_calculator/readme/CONTRIBUTORS.md
  product_packaging_unit_price_calculator/readme/CREDITS.md
  product_packaging_unit_price_calculator/readme/DESCRIPTION.md
  product_packaging_unit_price_calculator/readme/USAGE.md
  product_packaging_unit_price_calculator/security/ir.model.access.csv
  product_packaging_unit_price_calculator/static/description/icon.png
  product_packaging_unit_price_calculator/static/description/index.html
  product_packaging_unit_price_calculator/tests/__init__.py
  product_packaging_unit_price_calculator/tests/test_product_price_packaging_qty.py
  product_packaging_unit_price_calculator/views/product_packaging.xml
  product_packaging_unit_price_calculator/views/product_pricelist.xml
  product_packaging_unit_price_calculator/views/product_supplierinfo.xml
  product_packaging_unit_price_calculator/views/product_view.xml
  product_packaging_unit_price_calculator/wizards/__init__.py
  product_packaging_unit_price_calculator/wizards/product_package_price.py
  product_packaging_unit_price_calculator/wizards/product_package_price.xml
Labels: approved, bot is merging ⏳

#1790 [18.0][MIG] product_uom_updatable: Migration to 18.0
  product_uom_updatable/README.rst
  product_uom_updatable/__init__.py
  product_uom_updatable/__manifest__.py
  product_uom_updatable/i18n/it.po
  product_uom_updatable/i18n/product_uom_updatable.pot
  product_uom_updatable/models/__init__.py
  product_uom_updatable/models/product_template.py
  product_uom_updatable/pyproject.toml
  product_uom_updatable/readme/CONTRIBUTORS.md
  product_uom_updatable/readme/CREDITS.md
  product_uom_updatable/readme/DESCRIPTION.md
  product_uom_updatable/static/description/icon.png
  product_uom_updatable/static/description/index.html
  product_uom_updatable/tests/__init__.py
  product_uom_updatable/tests/test_product_uom_update.py
Labels: approved, ready to merge, bot is merging ⏳

#1932 [18.0][MOV] stock_packaging_calculator => product_packaging_calculator
  product_packaging_calculator/README.rst
  product_packaging_calculator/__init__.py
  product_packaging_calculator/__manifest__.py
  product_packaging_calculator/hooks.py
  product_packaging_calculator/i18n/it.po
  product_packaging_calculator/i18n/stock_packaging_calculator.pot
  product_packaging_calculator/models/__init__.py
  product_packaging_calculator/models/product.py
  product_packaging_calculator/models/product_qty_by_packaging_mixin.py
  product_packaging_calculator/pyproject.toml
  product_packaging_calculator/readme/CONTRIBUTORS.md
  product_packaging_calculator/readme/CREDITS.md
  product_packaging_calculator/readme/DESCRIPTION.md
  product_packaging_calculator/readme/ROADMAP.md
  product_packaging_calculator/readme/USAGE.md
  product_packaging_calculator/static/description/icon.png
  product_packaging_calculator/static/description/index.html
  product_packaging_calculator/tests/__init__.py
  product_packaging_calculator/tests/common.py
  product_packaging_calculator/tests/models.py
  product_packaging_calculator/tests/test_packaging_calc.py
  product_packaging_calculator/tests/test_pkg_qty_str.py
  product_packaging_calculator/tests/test_product_qty_by_packaging_mixin.py
  product_packaging_calculator/tests/utils.py
Labels: bot is merging ⏳

#1792 [18.0][MIG] product_total_weight_from_packaging: Migration to 18.0
  product_total_weight_from_packaging/README.rst
  product_total_weight_from_packaging/__init__.py
  product_total_weight_from_packaging/__manifest__.py
  product_total_weight_from_packaging/i18n/es.po
  product_total_weight_from_packaging/i18n/it.po
  product_total_weight_from_packaging/i18n/product_total_weight_from_packaging.pot
  product_total_weight_from_packaging/models/__init__.py
  product_total_weight_from_packaging/models/product.py
  product_total_weight_from_packaging/pyproject.toml
  product_total_weight_from_packaging/readme/CONTRIBUTORS.md
  product_total_weight_from_packaging/readme/CREDITS.md
  product_total_weight_from_packaging/readme/DESCRIPTION.md
  product_total_weight_from_packaging/static/description/icon.png
  product_total_weight_from_packaging/static/description/index.html
  product_total_weight_from_packaging/tests/__init__.py
  product_total_weight_from_packaging/tests/test_product_total_weight_from_packaging.py
Labels: approved, ready to merge, bot is merging ⏳

#1926 [18.0][MIG] product_get_price_helper: migrate to v18
  product_get_price_helper/README.rst
  product_get_price_helper/__init__.py
  product_get_price_helper/__manifest__.py
  product_get_price_helper/demo/account.xml
  product_get_price_helper/demo/pricelist.xml
  product_get_price_helper/i18n/it.po
  product_get_price_helper/i18n/product_get_price_helper.pot
  product_get_price_helper/models/__init__.py
  product_get_price_helper/models/product_product.py
  product_get_price_helper/pyproject.toml
  product_get_price_helper/readme/CONTRIBUTORS.rst
  product_get_price_helper/readme/DESCRIPTION.rst
  product_get_price_helper/static/description/icon.png
  product_get_price_helper/static/description/index.html
  product_get_price_helper/tests/__init__.py
  product_get_price_helper/tests/test_product.py
  product_get_price_helper/utils.py
Labels: approved, ready to merge, bot is merging ⏳

#1894 [17.0][MIG] product_multi_category
  product_multi_category/README.rst
  product_multi_category/__init__.py
  product_multi_category/__manifest__.py
  product_multi_category/i18n/ca.po
  product_multi_category/i18n/de.po
  product_multi_category/i18n/es.po
  product_multi_category/i18n/fr.po
  product_multi_category/i18n/fr_BE.po
  product_multi_category/i18n/hr.po
  product_multi_category/i18n/it.po
  product_multi_category/i18n/nl_NL.po
  product_multi_category/i18n/product_multi_category.pot
  product_multi_category/i18n/sv.po
  product_multi_category/i18n/tr.po
  product_multi_category/models/__init__.py
  product_multi_category/models/product.py
  product_multi_category/pyproject.toml
  product_multi_category/readme/CONTRIBUTORS.md
  product_multi_category/readme/DESCRIPTION.md
  product_multi_category/static/description/icon.png
  product_multi_category/static/description/index.html
  product_multi_category/views/product_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1912 [18.0][IMP] product_customerinfo: Allow searching product templates by customer info
  product_customerinfo/models/product_customerinfo.py
  product_customerinfo/models/product_product.py
  product_customerinfo/models/product_template.py
  product_customerinfo/tests/test_product_name_search.py
  product_customerinfo/views/product_views.xml
Labels: approved, bot is merging ⏳
