Repository OCA/product-attribute, pull requests merged in 2025-06, with the labels that each got.

#1978 [17.0][MIG] product_pricelist_assortment: Migration to v17.0
  product_pricelist_assortment/README.rst
  product_pricelist_assortment/__init__.py
  product_pricelist_assortment/__manifest__.py
  product_pricelist_assortment/data/ir_cron.xml
  product_pricelist_assortment/i18n/ca.po
  product_pricelist_assortment/i18n/es.po
  product_pricelist_assortment/i18n/it.po
  product_pricelist_assortment/i18n/nl.po
  product_pricelist_assortment/i18n/product_pricelist_assortment.pot
  product_pricelist_assortment/models/__init__.py
  product_pricelist_assortment/models/product_pricelist.py
  product_pricelist_assortment/models/product_pricelist_assortment_item.py
  product_pricelist_assortment/models/product_pricelist_item.py
  product_pricelist_assortment/pyproject.toml
  product_pricelist_assortment/readme/CONTRIBUTORS.md
  product_pricelist_assortment/readme/DESCRIPTION.md
  product_pricelist_assortment/readme/USAGE.md
  product_pricelist_assortment/security/ir.model.access.csv
  product_pricelist_assortment/security/product_pricelist_assortment_item.xml
  product_pricelist_assortment/static/description/icon.png
  product_pricelist_assortment/static/description/index.html
  product_pricelist_assortment/tests/__init__.py
  product_pricelist_assortment/tests/test_pricelist_assortment.py
  product_pricelist_assortment/views/product_pricelist.xml
  product_pricelist_assortment/views/product_pricelist_assortment_item.xml
  product_pricelist_assortment/views/product_pricelist_item.xml
Labels: approved, ready to merge, merged 🎉

#1943 [17.0] [MIG] product_category_code_unique: Migration to 17.0
  product_category_code_unique/README.rst
  product_category_code_unique/__init__.py
  product_category_code_unique/__manifest__.py
  product_category_code_unique/data/product_category_sequence.xml
  product_category_code_unique/hooks.py
  product_category_code_unique/i18n/it.po
  product_category_code_unique/i18n/product_category_code_unique.pot
  product_category_code_unique/models/__init__.py
  product_category_code_unique/models/product_category.py
  product_category_code_unique/pyproject.toml
  product_category_code_unique/readme/CONTRIBUTORS.md
  product_category_code_unique/readme/DESCRIPTION.md
  product_category_code_unique/static/description/icon.png
  product_category_code_unique/static/description/index.html
  product_category_code_unique/tests/__init__.py
  product_category_code_unique/tests/test_code_unique.py
Labels: needs review, approved, migration, bot is merging ⏳

#1994 [17.0][MIG] purchase_product_template_tags: Migration to 17.0
  purchase_product_template_tags/README.rst
  purchase_product_template_tags/__init__.py
  purchase_product_template_tags/__manifest__.py
  purchase_product_template_tags/i18n/de.po
  purchase_product_template_tags/i18n/it.po
  purchase_product_template_tags/i18n/purchase_product_template_tags.pot
  purchase_product_template_tags/pyproject.toml
  purchase_product_template_tags/readme/CONTRIBUTORS.md
  purchase_product_template_tags/readme/DESCRIPTION.md
  purchase_product_template_tags/static/description/icon.png
  purchase_product_template_tags/static/description/index.html
  purchase_product_template_tags/views/product_template_tag.xml
Labels: approved, ready to merge, bot is merging ⏳

#1977 [17.0][MIG] product_form_pricelist: Migration to 17.0
  product_form_pricelist/README.rst
  product_form_pricelist/__init__.py
  product_form_pricelist/__manifest__.py
  product_form_pricelist/i18n/es.po
  product_form_pricelist/i18n/it.po
  product_form_pricelist/i18n/product_form_pricelist.pot
  product_form_pricelist/models/__init__.py
  product_form_pricelist/models/product_pricelist_item.py
  product_form_pricelist/models/product_template.py
  product_form_pricelist/models/res_config_settings.py
  product_form_pricelist/pyproject.toml
  product_form_pricelist/readme/CONFIGURATION.rst
  product_form_pricelist/readme/CONTRIBUTORS.md
  product_form_pricelist/readme/DESCRIPTION.md
  product_form_pricelist/readme/USAGE.md
  product_form_pricelist/security/res_groups.xml
  product_form_pricelist/static/description/icon.png
  product_form_pricelist/static/description/index.html
  product_form_pricelist/tests/__init__.py
  product_form_pricelist/tests/test_pricelist.py
  product_form_pricelist/views/product_template_view.xml
  product_form_pricelist/views/product_view.xml
  product_form_pricelist/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1905 [16.0][IMP] product_supplierinfo_import_by_barcode: To product_supplierinfo_import
  product_supplierinfo_import_by_barcode/README.rst
  product_supplierinfo_import_by_barcode/__manifest__.py
  product_supplierinfo_import_by_barcode/i18n/es.po
  product_supplierinfo_import_by_barcode/i18n/product_supplierinfo_import_by_barcode.pot
  product_supplierinfo_import_by_barcode/migrations/16.0.2.0.0/pre-migration.py
  product_supplierinfo_import_by_barcode/models/__init__.py
  product_supplierinfo_import_by_barcode/models/product_supplier_info.py
  product_supplierinfo_import_by_barcode/models/product_supplierinfo_import_template.py
  product_supplierinfo_import_by_barcode/models/product_template.py
  product_supplierinfo_import_by_barcode/readme/CONFIGURE.md
  product_supplierinfo_import_by_barcode/readme/CONTRIBUTORS.md
  product_supplierinfo_import_by_barcode/readme/DESCRIPTION.md
  product_supplierinfo_import_by_barcode/readme/ROADMAP.md
  product_supplierinfo_import_by_barcode/readme/USAGE.md
  product_supplierinfo_import_by_barcode/static/description/index.html
  product_supplierinfo_import_by_barcode/tests/test_product_supplierinfo_import_by_barcode.py
  product_supplierinfo_import_by_barcode/tests/test_supplier_drinks_complex_sheet_updated.xlsx
  product_supplierinfo_import_by_barcode/views/product_supplierinfo_import_template_views.xml
  product_supplierinfo_import_by_barcode/wizards/product_supplierinfo_import.py
  product_supplierinfo_import_by_barcode/wizards/product_supplierinfo_import_views.xml
Labels: bot is merging ⏳

#2005 [18.0][FIX] product_secondary_unit: restore search by code and name
  product_secondary_unit/models/product_second_unit.py
Labels: approved, bot is merging ⏳

#2006 [18][FIX] product_status: Remove obsolete arg in group_expand method
  product_status/models/product.py
Labels: approved, bot is merging ⏳

#1582 [17.0][MIG] product_restricted_type
  product_restricted_type/README.rst
  product_restricted_type/__init__.py
  product_restricted_type/__manifest__.py
  product_restricted_type/i18n/ca.po
  product_restricted_type/i18n/es.po
  product_restricted_type/i18n/it.po
  product_restricted_type/i18n/product_restricted_type.pot
  product_restricted_type/models/__init__.py
  product_restricted_type/models/product_category.py
  product_restricted_type/models/product_product.py
  product_restricted_type/models/product_template.py
  product_restricted_type/pyproject.toml
  product_restricted_type/readme/CONTRIBUTORS.md
  product_restricted_type/readme/DESCRIPTION.md
  product_restricted_type/readme/USAGE.md
  product_restricted_type/static/description/icon.png
  product_restricted_type/static/description/index.html
  product_restricted_type/tests/__init__.py
  product_restricted_type/tests/test_product_restricted_type.py
  product_restricted_type/views/product_category_views.xml
  product_restricted_type/views/product_views.xml
Labels: bot is merging ⏳, stale
