Repository OCA/product-attribute, pull requests merged in 2025-01, with the labels that each got.

#1780 [18.0][MIG] product_sequence: Migration to 18.0
  product_sequence/README.rst
  product_sequence/__init__.py
  product_sequence/__manifest__.py
  product_sequence/data/product_sequence.xml
  product_sequence/hooks.py
  product_sequence/i18n/ar.po
  product_sequence/i18n/bg.po
  product_sequence/i18n/bs.po
  product_sequence/i18n/ca.po
  product_sequence/i18n/cs.po
  product_sequence/i18n/da.po
  product_sequence/i18n/de.po
  product_sequence/i18n/el.po
  product_sequence/i18n/es.po
  product_sequence/i18n/es_AR.po
  product_sequence/i18n/es_CR.po
  product_sequence/i18n/es_EC.po
  product_sequence/i18n/es_MX.po
  product_sequence/i18n/es_VE.po
  product_sequence/i18n/et.po
  product_sequence/i18n/fi.po
  product_sequence/i18n/fr.po
  product_sequence/i18n/gl.po
  product_sequence/i18n/hr.po
  product_sequence/i18n/hu.po
  product_sequence/i18n/it.po
  product_sequence/i18n/ja.po
  product_sequence/i18n/lt.po
  product_sequence/i18n/mk.po
  product_sequence/i18n/mn.po
  product_sequence/i18n/nb.po
  product_sequence/i18n/nl.po
  product_sequence/i18n/pl.po
  product_sequence/i18n/product_sequence.pot
  product_sequence/i18n/pt.po
  product_sequence/i18n/pt_BR.po
  product_sequence/i18n/ro.po
  product_sequence/i18n/ru.po
  product_sequence/i18n/sl.po
  product_sequence/i18n/sr.po
  product_sequence/i18n/sv.po
  product_sequence/i18n/tr.po
  product_sequence/i18n/zh_CN.po
  product_sequence/models/__init__.py
  product_sequence/models/ir_sequence.py
  product_sequence/models/product_category.py
  product_sequence/models/product_product.py
  product_sequence/models/res_company.py
  product_sequence/models/res_config_settings.py
  product_sequence/pyproject.toml
  product_sequence/readme/CONTRIBUTORS.md
  product_sequence/readme/DESCRIPTION.md
  product_sequence/readme/USAGE.md
  product_sequence/static/description/icon.png
  product_sequence/static/description/index.html
  product_sequence/tests/__init__.py
  product_sequence/tests/test_product_sequence.py
  product_sequence/views/product_category.xml
  product_sequence/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1836 [IMP] product_pricelist_supplierinfo: improve sale margin string in view and exclude supplier info discount in price
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
Labels: bot is merging ⏳

#1674 [17.0][MIG] product_product_template_link
  product_product_template_link/README.rst
  product_product_template_link/__init__.py
  product_product_template_link/__manifest__.py
  product_product_template_link/i18n/ca.po
  product_product_template_link/i18n/es.po
  product_product_template_link/i18n/it.po
  product_product_template_link/i18n/product_product_template_link.pot
  product_product_template_link/i18n/product_product_template_navigation.pot
  product_product_template_link/models/__init__.py
  product_product_template_link/models/product_product.py
  product_product_template_link/pyproject.toml
  product_product_template_link/readme/CONTRIBUTORS.md
  product_product_template_link/readme/DESCRIPTION.md
  product_product_template_link/static/description/icon.png
  product_product_template_link/static/description/index.html
  product_product_template_link/static/img/template_navigation.gif
  product_product_template_link/tests/__init__.py
  product_product_template_link/tests/test_product_product_template_link.py
  product_product_template_link/views/product_product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1806 [18.0][MIG] product_packaging_level: Migration to 18.0
  product_packaging_level/README.rst
  product_packaging_level/__init__.py
  product_packaging_level/__manifest__.py
  product_packaging_level/data/product_packaging_level.xml
  product_packaging_level/hooks.py
  product_packaging_level/i18n/ca.po
  product_packaging_level/i18n/es.po
  product_packaging_level/i18n/it.po
  product_packaging_level/i18n/nl.po
  product_packaging_level/i18n/product_packaging_level.pot
  product_packaging_level/models/__init__.py
  product_packaging_level/models/product_packaging.py
  product_packaging_level/models/product_packaging_level.py
  product_packaging_level/models/stock_package_type.py
  product_packaging_level/pyproject.toml
  product_packaging_level/readme/CONTRIBUTORS.md
  product_packaging_level/readme/CREDITS.md
  product_packaging_level/readme/DESCRIPTION.md
  product_packaging_level/readme/USAGE.md
  product_packaging_level/security/ir.model.access.csv
  product_packaging_level/static/description/icon.png
  product_packaging_level/static/description/index.html
  product_packaging_level/tests/__init__.py
  product_packaging_level/tests/test_product_packaging_level.py
  product_packaging_level/views/product_packaging_level_view.xml
  product_packaging_level/views/product_packaging_view.xml
  product_packaging_level/views/stock_package_type_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1842 [16.0][MIG] product_category_description: Migration to 16.0
  product_category_description/README.rst
  product_category_description/__init__.py
  product_category_description/__manifest__.py
  product_category_description/i18n/es.po
  product_category_description/i18n/it.po
  product_category_description/i18n/product_category_description.pot
  product_category_description/models/__init__.py
  product_category_description/models/product_category.py
  product_category_description/readme/CONTRIBUTORS.rst
  product_category_description/readme/DESCRIPTION.rst
  product_category_description/static/description/icon.png
  product_category_description/static/description/index.html
  product_category_description/views/product_category.xml
  setup/product_category_description/odoo/addons/product_category_description
  setup/product_category_description/setup.py
Labels: approved, bot is merging ⏳

#1843 [15.0][IMP] product_secondary_unit: Avoid circular recompute uom qty_field …
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, bot is merging ⏳

#1834 [FIX] product_category_active: harmonization of category display.
  product_category_active/README.rst
  product_category_active/__manifest__.py
  product_category_active/migrations/16.0.2.0.0/post-migration.py
  product_category_active/static/description/index.html
  product_category_active/views/product_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#1822 [16.0][MIG] product_attachment_zipped_download: Migration to 16.0
  product_attachment_zipped_download/README.rst
  product_attachment_zipped_download/__init__.py
  product_attachment_zipped_download/__manifest__.py
  product_attachment_zipped_download/data/ir_actions_server_data.xml
  product_attachment_zipped_download/i18n/es.po
  product_attachment_zipped_download/i18n/product_attachment_zipped_download.pot
  product_attachment_zipped_download/models/__init__.py
  product_attachment_zipped_download/models/product_product.py
  product_attachment_zipped_download/models/product_template.py
  product_attachment_zipped_download/readme/CONTRIBUTORS.rst
  product_attachment_zipped_download/readme/DESCRIPTION.rst
  product_attachment_zipped_download/static/description/icon.png
  product_attachment_zipped_download/static/description/index.html
  product_attachment_zipped_download/tests/__init__.py
  product_attachment_zipped_download/tests/test_product_attachment_zipped_download.py
  setup/product_attachment_zipped_download/odoo/addons/product_attachment_zipped_download
  setup/product_attachment_zipped_download/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1848 17.0 mig product_usability
  product_usability/README.rst
  product_usability/__init__.py
  product_usability/__manifest__.py
  product_usability/i18n/fr.po
  product_usability/i18n/it.po
  product_usability/i18n/product_usability.pot
  product_usability/pyproject.toml
  product_usability/readme/CONTRIBUTORS.md
  product_usability/readme/DESCRIPTION.md
  product_usability/readme/ROADMAP.md
  product_usability/security/ir.model.access.csv
  product_usability/security/res_groups.xml
  product_usability/static/description/icon.png
  product_usability/static/description/index.html
  product_usability/static/description/main_menu.png
  product_usability/static/description/product_menu_icon.png
  product_usability/static/description/product_menu_icon.svg
  product_usability/views/menu.xml
Labels: bot is merging ⏳

#1671 [17.0] [MIG] product_uom_measure_type: Migration to 17.0
  product_uom_measure_type/README.rst
  product_uom_measure_type/__init__.py
  product_uom_measure_type/__manifest__.py
  product_uom_measure_type/hooks.py
  product_uom_measure_type/i18n/es.po
  product_uom_measure_type/i18n/fr.po
  product_uom_measure_type/i18n/it.po
  product_uom_measure_type/i18n/product_uom_measure_type.pot
  product_uom_measure_type/models/__init__.py
  product_uom_measure_type/models/product_template.py
  product_uom_measure_type/models/uom_category.py
  product_uom_measure_type/models/uom_uom.py
  product_uom_measure_type/pyproject.toml
  product_uom_measure_type/readme/CONTRIBUTORS.md
  product_uom_measure_type/readme/DESCRIPTION.md
  product_uom_measure_type/static/description/icon.png
  product_uom_measure_type/static/description/index.html
  product_uom_measure_type/views/view_product_template.xml
  product_uom_measure_type/views/view_uom_category.xml
  product_uom_measure_type/views/view_uom_uom.xml
Labels: bot is merging ⏳, stale

#1851 [18.0][MIG] product_category_active: Migration to 18.0
  product_category_active/README.rst
  product_category_active/__init__.py
  product_category_active/__manifest__.py
  product_category_active/i18n/ca.po
  product_category_active/i18n/es.po
  product_category_active/i18n/hr.po
  product_category_active/i18n/it.po
  product_category_active/i18n/product_category_active.pot
  product_category_active/i18n/pt.po
  product_category_active/migrations/16.0.2.0.0/post-migration.py
  product_category_active/models/__init__.py
  product_category_active/models/product_category.py
  product_category_active/pyproject.toml
  product_category_active/readme/CONTRIBUTORS.md
  product_category_active/readme/DESCRIPTION.md
  product_category_active/readme/USAGE.md
  product_category_active/static/description/icon.png
  product_category_active/static/description/index.html
  product_category_active/tests/__init__.py
  product_category_active/tests/test_product_category_active.py
  product_category_active/views/product_views.xml
Labels: approved, bot is merging ⏳

#1825 [18.0][MIG] product_supplierinfo_archive: Migration to 18.0
  product_supplierinfo_archive/README.rst
  product_supplierinfo_archive/__init__.py
  product_supplierinfo_archive/__manifest__.py
  product_supplierinfo_archive/i18n/it.po
  product_supplierinfo_archive/i18n/product_supplierinfo_archive.pot
  product_supplierinfo_archive/models/__init__.py
  product_supplierinfo_archive/models/product_supplierinfo.py
  product_supplierinfo_archive/pyproject.toml
  product_supplierinfo_archive/readme/CONTRIBUTORS.md
  product_supplierinfo_archive/readme/CREDITS.md
  product_supplierinfo_archive/readme/DESCRIPTION.md
  product_supplierinfo_archive/readme/USAGE.md
  product_supplierinfo_archive/static/description/icon.png
  product_supplierinfo_archive/static/description/index.html
  product_supplierinfo_archive/views/product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1653 [17.0] [MIG] product_pricelist_simulation: Migration to 17.0
  product_pricelist_simulation/README.rst
  product_pricelist_simulation/__init__.py
  product_pricelist_simulation/__manifest__.py
  product_pricelist_simulation/i18n/es.po
  product_pricelist_simulation/i18n/it.po
  product_pricelist_simulation/i18n/product_pricelist_simulation.pot
  product_pricelist_simulation/i18n/pt_BR.po
  product_pricelist_simulation/i18n/tr.po
  product_pricelist_simulation/models/__init__.py
  product_pricelist_simulation/models/pricelist.py
  product_pricelist_simulation/pyproject.toml
  product_pricelist_simulation/readme/CONTRIBUTORS.md
  product_pricelist_simulation/readme/DESCRIPTION.md
  product_pricelist_simulation/readme/USAGE.md
  product_pricelist_simulation/security/ir.model.access.csv
  product_pricelist_simulation/static/description/icon.png
  product_pricelist_simulation/static/description/index.html
  product_pricelist_simulation/tests/__init__.py
  product_pricelist_simulation/tests/test_product_pricelist_simulation.py
  product_pricelist_simulation/views/pricelist_views.xml
  product_pricelist_simulation/views/product_views.xml
  product_pricelist_simulation/wizards/__init__.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist.py
  product_pricelist_simulation/wizards/wizard_preview_pricelist_views.xml
Labels: bot is merging ⏳

#1859 [17.0][MIG] product_readonly_security
  product_readonly_security/README.rst
  product_readonly_security/__init__.py
  product_readonly_security/__manifest__.py
  product_readonly_security/i18n/es.po
  product_readonly_security/i18n/it.po
  product_readonly_security/i18n/product_readonly_security.pot
  product_readonly_security/models/__init__.py
  product_readonly_security/models/product_product.py
  product_readonly_security/models/product_readonly_security_mixin.py
  product_readonly_security/models/product_template.py
  product_readonly_security/pyproject.toml
  product_readonly_security/readme/CONTRIBUTORS.md
  product_readonly_security/readme/DESCRIPTION.md
  product_readonly_security/readme/USAGE.md
  product_readonly_security/security/product_readonly_security.xml
  product_readonly_security/static/description/icon.png
  product_readonly_security/static/description/index.html
  product_readonly_security/tests/__init__.py
  product_readonly_security/tests/test_product_readonly_security.py
Labels: approved, bot is merging ⏳

#1838 [18.0][MIG] product_attribute_archive: Migration to 18.0
  product_attribute_archive/README.rst
  product_attribute_archive/__init__.py
  product_attribute_archive/__manifest__.py
  product_attribute_archive/i18n/es.po
  product_attribute_archive/i18n/it.po
  product_attribute_archive/i18n/product_attribute_archive.pot
  product_attribute_archive/models/__init__.py
  product_attribute_archive/models/product_attribute.py
  product_attribute_archive/models/product_attribute_value.py
  product_attribute_archive/pyproject.toml
  product_attribute_archive/readme/CONTRIBUTORS.md
  product_attribute_archive/readme/DESCRIPTION.md
  product_attribute_archive/readme/USAGE.md
  product_attribute_archive/static/description/icon.png
  product_attribute_archive/static/description/index.html
  product_attribute_archive/views/product_attribute.xml
Labels: approved, ready to merge, bot is merging ⏳

#1624 [17.0] [MIG] product_pricelist_item_list_view: Migration to 17.0
  product_pricelist_item_list_view/README.rst
  product_pricelist_item_list_view/__init__.py
  product_pricelist_item_list_view/__manifest__.py
  product_pricelist_item_list_view/i18n/ca.po
  product_pricelist_item_list_view/i18n/de.po
  product_pricelist_item_list_view/i18n/es.po
  product_pricelist_item_list_view/i18n/fr.po
  product_pricelist_item_list_view/i18n/it.po
  product_pricelist_item_list_view/i18n/product_pricelist_item_list_view.pot
  product_pricelist_item_list_view/pyproject.toml
  product_pricelist_item_list_view/static/description/icon.png
  product_pricelist_item_list_view/views/pricelist_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1788 [18.0][MIG] product_supplierinfo_revision: Migration to 18.0
  product_supplierinfo_revision/README.rst
  product_supplierinfo_revision/__init__.py
  product_supplierinfo_revision/__manifest__.py
  product_supplierinfo_revision/i18n/ca.po
  product_supplierinfo_revision/i18n/es.po
  product_supplierinfo_revision/i18n/fr.po
  product_supplierinfo_revision/i18n/it.po
  product_supplierinfo_revision/i18n/product_supplierinfo_revision.pot
  product_supplierinfo_revision/models/__init__.py
  product_supplierinfo_revision/models/product_supplierinfo.py
  product_supplierinfo_revision/pyproject.toml
  product_supplierinfo_revision/readme/CONTRIBUTORS.md
  product_supplierinfo_revision/readme/DESCRIPTION.md
  product_supplierinfo_revision/readme/USAGE.md
  product_supplierinfo_revision/security/ir.model.access.csv
  product_supplierinfo_revision/static/description/icon.png
  product_supplierinfo_revision/static/description/index.html
  product_supplierinfo_revision/tests/__init__.py
  product_supplierinfo_revision/tests/test_product_supplierinfo_revision.py
  product_supplierinfo_revision/views/product_supplierinfo_view.xml
  product_supplierinfo_revision/wizards/__init__.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
  product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard_view.xml
Labels: approved, bot is merging ⏳

#1837 [MIG] product_pricelist_supplierinfo: Migration to 18.0
  product_pricelist_supplierinfo/README.rst
  product_pricelist_supplierinfo/__init__.py
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/ca.po
  product_pricelist_supplierinfo/i18n/es.po
  product_pricelist_supplierinfo/i18n/fr.po
  product_pricelist_supplierinfo/i18n/it.po
  product_pricelist_supplierinfo/i18n/nl.po
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/i18n/pt_BR.po
  product_pricelist_supplierinfo/models/__init__.py
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_product.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/pyproject.toml
  product_pricelist_supplierinfo/readme/CONFIGURE.md
  product_pricelist_supplierinfo/readme/CONTRIBUTORS.md
  product_pricelist_supplierinfo/readme/DESCRIPTION.md
  product_pricelist_supplierinfo/readme/INSTALL.md
  product_pricelist_supplierinfo/readme/ROADMAP.md
  product_pricelist_supplierinfo/readme/USAGE.md
  product_pricelist_supplierinfo/security/res_groups.xml
  product_pricelist_supplierinfo/static/description/icon.png
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/__init__.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
  product_pricelist_supplierinfo/views/product_supplierinfo_view.xml
Labels: approved, ready to merge, bot is merging ⏳
