Repository OCA/product-attribute, pull requests merged in 2025-02, with the labels that each got.

#1795 [18.0][MIG] product_state: Migration to 18.0
  product_state/README.rst
  product_state/__init__.py
  product_state/__manifest__.py
  product_state/data/product_state_data.xml
  product_state/i18n/ca.po
  product_state/i18n/de.po
  product_state/i18n/es.po
  product_state/i18n/fr.po
  product_state/i18n/hr.po
  product_state/i18n/it.po
  product_state/i18n/nl.po
  product_state/i18n/nl_NL.po
  product_state/i18n/product_state.pot
  product_state/i18n/pt.po
  product_state/i18n/sl.po
  product_state/models/__init__.py
  product_state/models/product_state.py
  product_state/models/product_template.py
  product_state/pyproject.toml
  product_state/readme/CONTRIBUTORS.md
  product_state/readme/CREDITS.md
  product_state/readme/DESCRIPTION.md
  product_state/readme/USAGE.md
  product_state/security/ir.model.access.csv
  product_state/security/product_state_security.xml
  product_state/static/description/icon.png
  product_state/static/description/index.html
  product_state/tests/__init__.py
  product_state/tests/test_product_state.py
  product_state/views/product_state_views.xml
  product_state/views/product_template_views.xml
Labels: approved, migration, bot is merging ⏳

#1870 [16.0][MIG] stock_product_template_tags: Migration to 16.0
  setup/stock_product_template_tags/odoo/addons/stock_product_template_tags
  setup/stock_product_template_tags/setup.py
  stock_product_template_tags/README.rst
  stock_product_template_tags/__init__.py
  stock_product_template_tags/__manifest__.py
  stock_product_template_tags/i18n/it.po
  stock_product_template_tags/i18n/stock_product_template_tags.pot
  stock_product_template_tags/readme/CONTRIBUTORS.rst
  stock_product_template_tags/readme/DESCRIPTION.rst
  stock_product_template_tags/static/description/icon.png
  stock_product_template_tags/static/description/index.html
  stock_product_template_tags/views/product_template_tag.xml
Labels: approved, bot is merging ⏳

#1818 [18.0][ADD] product_state_sale
  product_state_sale/README.rst
  product_state_sale/__init__.py
  product_state_sale/__manifest__.py
  product_state_sale/pyproject.toml
  product_state_sale/readme/CONTRIBUTORS.md
  product_state_sale/readme/CREDITS.md
  product_state_sale/readme/DESCRIPTION.md
  product_state_sale/readme/USAGE.md
  product_state_sale/security/security.xml
  product_state_sale/static/description/index.html
  product_state_sale/views/product_state_views.xml
Labels: bot is merging ⏳

#1794 [18.0][MIG] product_stock_state: Migration to 18.0
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/data/data.xml
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/es.po
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/it.po
  product_stock_state/i18n/nl.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/res_config_settings.py
  product_stock_state/pyproject.toml
  product_stock_state/readme/CONFIGURE.md
  product_stock_state/readme/CONTRIBUTORS.md
  product_stock_state/readme/CREDITS.md
  product_stock_state/readme/DESCRIPTION.md
  product_stock_state/readme/USAGE.md
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/icon.png
  product_stock_state/static/description/index.html
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/res_company_view.xml
  product_stock_state/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#1801 [18.0][MIG] product_sale_manufactured_for: Migration to 18.0
  product_sale_manufactured_for/README.rst
  product_sale_manufactured_for/__init__.py
  product_sale_manufactured_for/__manifest__.py
  product_sale_manufactured_for/i18n/es.po
  product_sale_manufactured_for/i18n/it.po
  product_sale_manufactured_for/i18n/product_sale_manufactured_for.pot
  product_sale_manufactured_for/models/__init__.py
  product_sale_manufactured_for/models/product_product.py
  product_sale_manufactured_for/pyproject.toml
  product_sale_manufactured_for/readme/CONTRIBUTORS.md
  product_sale_manufactured_for/readme/CREDITS.md
  product_sale_manufactured_for/readme/DESCRIPTION.md
  product_sale_manufactured_for/static/description/icon.png
  product_sale_manufactured_for/static/description/index.html
  product_sale_manufactured_for/views/product_product.xml
  product_sale_manufactured_for/views/sale_order.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1880 [18.0][MIG] product_supplierinfo_for_customer: Migration to version 18.0 and renamed to product_customerinfo
  product_customerinfo/README.rst
  product_customerinfo/__init__.py
  product_customerinfo/__manifest__.py
  product_customerinfo/demo/product_demo.xml
  product_customerinfo/i18n/ca.po
  product_customerinfo/i18n/de.po
  product_customerinfo/i18n/es.po
  product_customerinfo/i18n/fr.po
  product_customerinfo/i18n/it.po
  product_customerinfo/i18n/product_supplierinfo_for_customer.pot
  product_customerinfo/i18n/pt_BR.po
  product_customerinfo/i18n/sl.po
  product_customerinfo/models/__init__.py
  product_customerinfo/models/product_customerinfo.py
  product_customerinfo/models/product_pricelist.py
  product_customerinfo/models/product_product.py
  product_customerinfo/models/product_supplierinfo.py
  product_customerinfo/models/product_template.py
  product_customerinfo/models/res_partner.py
  product_customerinfo/pyproject.toml
  product_customerinfo/readme/CONFIGURE.md
  product_customerinfo/readme/CONTRIBUTORS.md
  product_customerinfo/readme/DESCRIPTION.md
  product_customerinfo/readme/ROADMAP.md
  product_customerinfo/readme/USAGE.md
  product_customerinfo/security/ir.model.access.csv
  product_customerinfo/static/description/icon.png
  product_customerinfo/static/description/index.html
  product_customerinfo/static/xls/product_customerinfo.xls
  product_customerinfo/tests/__init__.py
  product_customerinfo/tests/test_product_customerinfo.py
  product_customerinfo/views/product_views.xml
Labels: approved, bot is merging ⏳

#1869 [16.0][MIG] purchase_product_template_tags: Migration to 16.0
  purchase_product_template_tags/README.rst
  purchase_product_template_tags/__init__.py
  purchase_product_template_tags/__manifest__.py
  purchase_product_template_tags/i18n/it.po
  purchase_product_template_tags/i18n/purchase_product_template_tags.pot
  purchase_product_template_tags/readme/CONTRIBUTORS.rst
  purchase_product_template_tags/readme/DESCRIPTION.rst
  purchase_product_template_tags/static/description/icon.png
  purchase_product_template_tags/static/description/index.html
  purchase_product_template_tags/views/product_template_tag.xml
  setup/purchase_product_template_tags/odoo/addons/purchase_product_template_tags
  setup/purchase_product_template_tags/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1769 [18.0][MIG] product_code_unique: Migration to 18.0
  product_code_unique/README.rst
  product_code_unique/__init__.py
  product_code_unique/__manifest__.py
  product_code_unique/hook.py
  product_code_unique/i18n/ca.po
  product_code_unique/i18n/de.po
  product_code_unique/i18n/es.po
  product_code_unique/i18n/fr.po
  product_code_unique/i18n/fr_FR.po
  product_code_unique/i18n/it.po
  product_code_unique/i18n/product_code_unique.pot
  product_code_unique/i18n/pt.po
  product_code_unique/models/__init__.py
  product_code_unique/models/product.py
  product_code_unique/pyproject.toml
  product_code_unique/readme/CONTRIBUTORS.md
  product_code_unique/readme/DESCRIPTION.md
  product_code_unique/readme/ROADMAP.md
  product_code_unique/readme/USAGE.md
  product_code_unique/static/description/icon.png
  product_code_unique/static/description/index.html
  product_code_unique/tests/__init__.py
  product_code_unique/tests/test_code_unique.py
Labels: needs review, approved, migration, bot is merging ⏳

#1708 [17.0] [MIG] product lot sequence
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/data/ir_config_parameter.xml
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/it.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/res_company.py
  product_lot_sequence/models/res_config_settings.py
  product_lot_sequence/models/stock_lot.py
  product_lot_sequence/models/stock_move.py
  product_lot_sequence/pyproject.toml
  product_lot_sequence/readme/CONFIGURE.md
  product_lot_sequence/readme/CONTRIBUTORS.md
  product_lot_sequence/readme/DESCRIPTION.md
  product_lot_sequence/readme/ROADMAP.md
  product_lot_sequence/readme/USAGE.md
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  product_lot_sequence/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#1770 [18.0][MIG] product_category_code: Migration to 18.0
  product_category_code/README.rst
  product_category_code/__init__.py
  product_category_code/__manifest__.py
  product_category_code/i18n/es.po
  product_category_code/i18n/it.po
  product_category_code/i18n/product_category_code.pot
  product_category_code/models/__init__.py
  product_category_code/models/product_category.py
  product_category_code/pyproject.toml
  product_category_code/readme/CONTRIBUTORS.md
  product_category_code/readme/DESCRIPTION.md
  product_category_code/static/description/icon.png
  product_category_code/static/description/index.html
  product_category_code/tests/__init__.py
  product_category_code/tests/test_category_code.py
  product_category_code/views/product_category.xml
Labels: bot is merging ⏳

#1883 [17.0][MIG] product_cost_security: Migration to version 17.0
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/ca.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/it.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_cost_security_mixin.py
  product_cost_security/models/product_product.py
  product_cost_security/models/product_template.py
  product_cost_security/pyproject.toml
  product_cost_security/readme/CONFIGURE.md
  product_cost_security/readme/CONTRIBUTORS.md
  product_cost_security/readme/DESCRIPTION.md
  product_cost_security/readme/ROADMAP.md
  product_cost_security/readme/USAGE.md
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/tests/__init__.py
  product_cost_security/tests/test_product_cost_security.py
  product_cost_security/views/product_views.xml
Labels: approved, bot is merging ⏳

#1887 [16.0][IMP] product_pricelist_direct_print: Add decimal precision to price fields
  product_pricelist_direct_print/reports/report_product_pricelist.xml
Labels: approved, bot is merging ⏳

#1863 [18.0][MIG] product_pricelist_alternative: Migration to 18.0
  product_pricelist_alternative/README.rst
  product_pricelist_alternative/__init__.py
  product_pricelist_alternative/__manifest__.py
  product_pricelist_alternative/i18n/fr.po
  product_pricelist_alternative/i18n/it.po
  product_pricelist_alternative/i18n/product_pricelist_alternative.pot
  product_pricelist_alternative/models/__init__.py
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/models/product_pricelist_item.py
  product_pricelist_alternative/pyproject.toml
  product_pricelist_alternative/readme/CONTRIBUTORS.md
  product_pricelist_alternative/readme/DESCRIPTION.md
  product_pricelist_alternative/static/description/icon.png
  product_pricelist_alternative/static/description/index.html
  product_pricelist_alternative/tests/__init__.py
  product_pricelist_alternative/tests/common.py
  product_pricelist_alternative/tests/test_pricelist_alternative.py
  product_pricelist_alternative/views/product_pricelist_item_view.xml
  product_pricelist_alternative/views/product_pricelist_view.xml
Labels: needs review, migration, bot is merging ⏳

#1884 [16.0][IMP] product_pricelist_supplierinfo: Add ignore_supplierinfo_margin option…
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/static/description/index.html
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
Labels: bot is merging ⏳

#1888 [18.0][MIG] product_cost_security: Migration to version 18.0
  product_cost_security/README.rst
  product_cost_security/__init__.py
  product_cost_security/__manifest__.py
  product_cost_security/i18n/ar.po
  product_cost_security/i18n/ca.po
  product_cost_security/i18n/es.po
  product_cost_security/i18n/it.po
  product_cost_security/i18n/product_cost_security.pot
  product_cost_security/models/__init__.py
  product_cost_security/models/product_cost_security_mixin.py
  product_cost_security/models/product_product.py
  product_cost_security/models/product_template.py
  product_cost_security/pyproject.toml
  product_cost_security/readme/CONFIGURE.md
  product_cost_security/readme/CONTRIBUTORS.md
  product_cost_security/readme/DESCRIPTION.md
  product_cost_security/readme/ROADMAP.md
  product_cost_security/readme/USAGE.md
  product_cost_security/security/product_cost_security.xml
  product_cost_security/static/description/icon.png
  product_cost_security/static/description/index.html
  product_cost_security/tests/__init__.py
  product_cost_security/tests/test_product_cost_security.py
  product_cost_security/views/product_views.xml
Labels: approved, bot is merging ⏳

#1881 [FIX] product_print_category: Do no set current company by default on category model
  product_print_category/models/product_print_category.py
Labels: bot is merging ⏳

#1891 [18.0][MIG] product_pricelist_by_contact: Migration to version 18.0
  product_pricelist_by_contact/README.rst
  product_pricelist_by_contact/__init__.py
  product_pricelist_by_contact/__manifest__.py
  product_pricelist_by_contact/i18n/it.po
  product_pricelist_by_contact/i18n/product_pricelist_by_contact.pot
  product_pricelist_by_contact/pyproject.toml
  product_pricelist_by_contact/readme/CONTRIBUTORS.md
  product_pricelist_by_contact/readme/DESCRIPTION.md
  product_pricelist_by_contact/readme/ROADMAP.md
  product_pricelist_by_contact/readme/USAGE.md
  product_pricelist_by_contact/static/description/icon.png
  product_pricelist_by_contact/static/description/index.html
  product_pricelist_by_contact/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#1892 [18.0][ADD] product_attribute_value_avoid_auto_fill: New module to avoid add all values of attribute when selecting it
  product_attribute_value_avoid_auto_fill/README.rst
  product_attribute_value_avoid_auto_fill/__init__.py
  product_attribute_value_avoid_auto_fill/__manifest__.py
  product_attribute_value_avoid_auto_fill/models/__init__.py
  product_attribute_value_avoid_auto_fill/models/product_attribute.py
  product_attribute_value_avoid_auto_fill/models/product_template_attribute_line.py
  product_attribute_value_avoid_auto_fill/pyproject.toml
  product_attribute_value_avoid_auto_fill/readme/CONTRIBUTORS.md
  product_attribute_value_avoid_auto_fill/readme/DESCRIPTION.md
  product_attribute_value_avoid_auto_fill/readme/USAGE.md
  product_attribute_value_avoid_auto_fill/static/description/index.html
  product_attribute_value_avoid_auto_fill/tests/__init__.py
  product_attribute_value_avoid_auto_fill/tests/test_product_attribute_value_avoid_auto_fill.py
  product_attribute_value_avoid_auto_fill/views/product_attribute_views.xml
Labels: approved, bot is merging ⏳

#1893 [FIX] [16.0] product_sticker: Allow to select which models can use Stickers
  product_sticker/README.rst
  product_sticker/i18n/es.po
  product_sticker/i18n/product_sticker.pot
  product_sticker/models/product_product.py
  product_sticker/models/product_sticker.py
  product_sticker/models/product_template.py
  product_sticker/readme/USAGE.rst
  product_sticker/static/description/index.html
  product_sticker/tests/test_product.py
  product_sticker/views/product_sticker_views.xml
Labels: enhancement, needs review, approved

#1895 [17.0][MIG] product_category_product_link: Migration to 17.0
  product_category_product_link/README.rst
  product_category_product_link/__init__.py
  product_category_product_link/__manifest__.py
  product_category_product_link/i18n/ca.po
  product_category_product_link/i18n/it.po
  product_category_product_link/i18n/product_category_product_link.pot
  product_category_product_link/models/__init__.py
  product_category_product_link/models/product_category.py
  product_category_product_link/models/product_template.py
  product_category_product_link/pyproject.toml
  product_category_product_link/readme/CONTRIBUTORS.md
  product_category_product_link/readme/DESCRIPTION.md
  product_category_product_link/static/description/icon.png
  product_category_product_link/static/description/index.html
Labels: approved, bot is merging ⏳

#1899 [18.0][FIX] product_customerinfo: adapt name_search to the new api
  product_customerinfo/models/product_product.py
  product_customerinfo/tests/__init__.py
  product_customerinfo/tests/test_product_name_search.py
Labels: approved, bot is merging ⏳

#1902 [IMP] [16.0] product_sticker: Allow to choose size
  product_sticker/models/product_sticker.py
  product_sticker/tests/common.py
  product_sticker/tests/test_product.py
  product_sticker/views/product_sticker_views.xml
Labels: approved, bot is merging ⏳

#1901 [15.0][IMP] product_pricelist_direct_print: Add UOM column
  product_pricelist_direct_print/report/product_pricelist_xlsx.py
  product_pricelist_direct_print/views/report_product_pricelist.xml
  product_pricelist_direct_print/wizards/product_pricelist_print.py
  product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
Labels: approved, bot is merging ⏳

#1829 [16.0][MIG+IMP] product_category_code_unique: restriciton options
  product_category_code_unique/README.rst
  product_category_code_unique/__init__.py
  product_category_code_unique/__manifest__.py
  product_category_code_unique/data/product_category_sequence.xml
  product_category_code_unique/hooks.py
  product_category_code_unique/i18n/it.po
  product_category_code_unique/i18n/product_category_code_unique.pot
  product_category_code_unique/models/__init__.py
  product_category_code_unique/models/product_category.py
  product_category_code_unique/models/res_config_settings.py
  product_category_code_unique/readme/CONFIGURE.rst
  product_category_code_unique/readme/CONTRIBUTORS.rst
  product_category_code_unique/readme/DESCRIPTION.rst
  product_category_code_unique/readme/USAGE.rst
  product_category_code_unique/static/description/icon.png
  product_category_code_unique/static/description/index.html
  product_category_code_unique/tests/__init__.py
  product_category_code_unique/tests/test_code_unique.py
  product_category_code_unique/views/res_config_settings_views.xml
  setup/product_category_code_unique/odoo/addons/product_category_code_unique
  setup/product_category_code_unique/setup.py
Labels: bot is merging ⏳
