Repository OCA/product-attribute, pull requests merged in 2025-10, with the labels that each got.

#2069 [16.0][ADD] Product_logistics_uom_net_weight
  product_logistics_uom_net_weight/README.rst
  product_logistics_uom_net_weight/__init__.py
  product_logistics_uom_net_weight/__manifest__.py
  product_logistics_uom_net_weight/hooks.py
  product_logistics_uom_net_weight/i18n/es.po
  product_logistics_uom_net_weight/i18n/product_logistics_uom_net_weight.pot
  product_logistics_uom_net_weight/models/__init__.py
  product_logistics_uom_net_weight/models/product_product.py
  product_logistics_uom_net_weight/models/product_template.py
  product_logistics_uom_net_weight/readme/CONFIGURE.rst
  product_logistics_uom_net_weight/readme/CONTRIBUTORS.rst
  product_logistics_uom_net_weight/readme/DESCRIPTION.rst
  product_logistics_uom_net_weight/readme/INSTALL.rst
  product_logistics_uom_net_weight/readme/USAGE.rst
  product_logistics_uom_net_weight/static/description/icon.png
  product_logistics_uom_net_weight/static/description/index.html
  product_logistics_uom_net_weight/tests/__init__.py
  product_logistics_uom_net_weight/tests/test_product_logistics_uom_net_weight.py
  product_logistics_uom_net_weight/views/product_product.xml
  product_logistics_uom_net_weight/views/product_template.xml
  setup/product_logistics_uom_net_weight/odoo/addons/product_logistics_uom_net_weight
  setup/product_logistics_uom_net_weight/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2094 19.0 mig product net weight
  .pre-commit-config.yaml
  product_net_weight/README.rst
  product_net_weight/__init__.py
  product_net_weight/__manifest__.py
  product_net_weight/demo/product_product.xml
  product_net_weight/i18n/es.po
  product_net_weight/i18n/fr.po
  product_net_weight/i18n/it.po
  product_net_weight/i18n/product_net_weight.pot
  product_net_weight/models/__init__.py
  product_net_weight/models/product_product.py
  product_net_weight/models/product_template.py
  product_net_weight/pyproject.toml
  product_net_weight/readme/CONTRIBUTORS.md
  product_net_weight/readme/DESCRIPTION.md
  product_net_weight/readme/ROADMAP.md
  product_net_weight/readme/USAGE.md
  product_net_weight/static/description/icon.png
  product_net_weight/static/description/index.html
  product_net_weight/static/description/product_form.png
  product_net_weight/tests/__init__.py
  product_net_weight/tests/test_product_net_weight.py
  product_net_weight/views/view_product_product.xml
  product_net_weight/views/view_product_template.xml
Labels: bot is merging ⏳

#2086 [19.0][MIG] product_company_default: Migration to 19.0
  product_company_default/README.rst
  product_company_default/__init__.py
  product_company_default/__manifest__.py
  product_company_default/data/ir_config_parameter.xml
  product_company_default/demo/demo_ir_config_parameter.xml
  product_company_default/i18n/it.po
  product_company_default/i18n/product_company_default.pot
  product_company_default/models/__init__.py
  product_company_default/models/product_template.py
  product_company_default/pyproject.toml
  product_company_default/readme/DESCRIPTION.md
  product_company_default/static/description/icon.png
  product_company_default/static/description/index.html
  product_company_default/tests/__init__.py
  product_company_default/tests/test_product_company_default.py
Labels: approved, migration, bot is merging ⏳

#2096 [17.0] [MIG] product_route_mto: Migration to 17.0
  product_route_mto/README.rst
  product_route_mto/__init__.py
  product_route_mto/__manifest__.py
  product_route_mto/i18n/es.po
  product_route_mto/i18n/fr_BE.po
  product_route_mto/i18n/it.po
  product_route_mto/i18n/product_route_mto.pot
  product_route_mto/models/__init__.py
  product_route_mto/models/product_template.py
  product_route_mto/pyproject.toml
  product_route_mto/readme/CONTRIBUTORS.md
  product_route_mto/readme/DESCRIPTION.md
  product_route_mto/static/description/icon.png
  product_route_mto/static/description/index.html
  product_route_mto/tests/__init__.py
  product_route_mto/tests/test_product_route_mto.py
  product_route_mto/views/product_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1953 [17.0][ADD] product_attribute_auto_add: module add
  product_attribute_auto_add/README.rst
  product_attribute_auto_add/__init__.py
  product_attribute_auto_add/__manifest__.py
  product_attribute_auto_add/models/__init__.py
  product_attribute_auto_add/models/product_attribute.py
  product_attribute_auto_add/models/product_attribute_value.py
  product_attribute_auto_add/models/product_template.py
  product_attribute_auto_add/pyproject.toml
  product_attribute_auto_add/readme/CONFIGURE.md
  product_attribute_auto_add/readme/CONTRIBUTORS.md
  product_attribute_auto_add/readme/DESCRIPTION.md
  product_attribute_auto_add/readme/HISTORY.md
  product_attribute_auto_add/readme/USAGE.md
  product_attribute_auto_add/static/description/index.html
  product_attribute_auto_add/static/img/usage.png
  product_attribute_auto_add/tests/__init__.py
  product_attribute_auto_add/tests/test_product_attribute_value.py
  product_attribute_auto_add/views/product_attribute_views.xml
  product_attribute_auto_add/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳
