Repository OCA/product-attribute, pull requests merged in 2025-08, with the labels that each got.

#1747 [16.0][FIX] product_pricelist_alternative: No alternative price in waterfall pricelists
  product_pricelist_alternative/models/product_pricelist.py
  product_pricelist_alternative/models/product_pricelist_item.py
  product_pricelist_alternative/tests/common.py
  product_pricelist_alternative/tests/test_pricelist_alternative.py
Labels: approved, ready to merge, bot is merging ⏳

#2023 [FIX][18.0] product_sticker: Show stickers on one attribute value products with create variant
  product_sticker/README.rst
  product_sticker/__init__.py
  product_sticker/__manifest__.py
  product_sticker/models/product_sticker.py
  product_sticker/static/description/index.html
  product_sticker/tests/common.py
  product_sticker/tests/test_product.py
  product_sticker/views/product_product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1799 [17.0][ADD] product_logistics_uom_total_weight: New module product_logistics_uom_total_weight
  product_logistics_uom_total_weight/README.rst
  product_logistics_uom_total_weight/__init__.py
  product_logistics_uom_total_weight/__manifest__.py
  product_logistics_uom_total_weight/i18n/ca.po
  product_logistics_uom_total_weight/i18n/es.po
  product_logistics_uom_total_weight/models/__init__.py
  product_logistics_uom_total_weight/models/product.py
  product_logistics_uom_total_weight/pyproject.toml
  product_logistics_uom_total_weight/readme/CONTRIBUTORS.md
  product_logistics_uom_total_weight/readme/DESCRIPTION.md
  product_logistics_uom_total_weight/readme/USAGE.md
  product_logistics_uom_total_weight/static/description/icon.png
  product_logistics_uom_total_weight/static/description/icon.svg
  product_logistics_uom_total_weight/static/description/index.html
  product_logistics_uom_total_weight/tests/__init__.py
  product_logistics_uom_total_weight/tests/test_product_weight.py
  product_logistics_uom_total_weight/views/product_views.xml
Labels: approved, bot is merging ⏳

#2000 [17.0][MIG] stock_product_template_tags
  stock_product_template_tags/README.rst
  stock_product_template_tags/__init__.py
  stock_product_template_tags/__manifest__.py
  stock_product_template_tags/i18n/it.po
  stock_product_template_tags/i18n/stock_product_template_tags.pot
  stock_product_template_tags/pyproject.toml
  stock_product_template_tags/readme/CONTRIBUTORS.md
  stock_product_template_tags/readme/DESCRIPTION.md
  stock_product_template_tags/static/description/icon.png
  stock_product_template_tags/static/description/index.html
  stock_product_template_tags/views/product_template_tag.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#1987 [18.0][MIG] uom_alias: Migration to 18.0
  uom_alias/README.rst
  uom_alias/__init__.py
  uom_alias/__manifest__.py
  uom_alias/i18n/it.po
  uom_alias/i18n/uom_alias.pot
  uom_alias/models/__init__.py
  uom_alias/models/uom_alias.py
  uom_alias/models/uom_uom.py
  uom_alias/pyproject.toml
  uom_alias/readme/CONFIGURE.md
  uom_alias/readme/CONTRIBUTORS.md
  uom_alias/readme/DESCRIPTION.md
  uom_alias/readme/ROADMAP.md
  uom_alias/readme/USAGE.md
  uom_alias/security/ir.model.access.csv
  uom_alias/static/description/icon.png
  uom_alias/static/description/index.html
  uom_alias/static/img/screenshot-1.png
  uom_alias/tests/__init__.py
  uom_alias/tests/test_uom_alias.py
  uom_alias/views/uom_category.xml
  uom_alias/views/uom_uom.xml
Labels: approved, bot is merging ⏳

#2049 [MIG] product_category_type: Migration to 18.0
  product_category_type/README.rst
  product_category_type/__init__.py
  product_category_type/__manifest__.py
  product_category_type/demo/product_category.xml
  product_category_type/i18n/de.po
  product_category_type/i18n/es.po
  product_category_type/i18n/fr.po
  product_category_type/i18n/hr.po
  product_category_type/i18n/it.po
  product_category_type/i18n/product_category_type.pot
  product_category_type/models/__init__.py
  product_category_type/models/product_category.py
  product_category_type/models/product_template.py
  product_category_type/pyproject.toml
  product_category_type/readme/CONTRIBUTORS.md
  product_category_type/readme/DESCRIPTION.md
  product_category_type/static/description/icon.png
  product_category_type/static/description/index.html
  product_category_type/static/description/product_category_tree.png
  product_category_type/static/description/product_template_form.png
  product_category_type/views/product_category.xml
Labels: approved, ready to merge, bot is merging ⏳
