Repository OCA/product-attribute, pull requests merged in 2025-05, with the labels that each got.

#1966 [16.0][REF] uom_alias: dev status -> Production/Stable
  uom_alias/__manifest__.py
Labels: approved, bot is merging ⏳

#1913 [17.0][MIG] product_assortment: Migration to 17.0
  product_assortment/README.rst
  product_assortment/__init__.py
  product_assortment/__manifest__.py
  product_assortment/data/ir_cron.xml
  product_assortment/i18n/ca.po
  product_assortment/i18n/de.po
  product_assortment/i18n/es.po
  product_assortment/i18n/fr.po
  product_assortment/i18n/it.po
  product_assortment/i18n/nl.po
  product_assortment/i18n/product_assortment.pot
  product_assortment/models/__init__.py
  product_assortment/models/ir_filters.py
  product_assortment/models/res_partner.py
  product_assortment/pyproject.toml
  product_assortment/readme/CONTRIBUTORS.md
  product_assortment/readme/DESCRIPTION.md
  product_assortment/readme/HISTORY.md
  product_assortment/readme/USAGE.md
  product_assortment/security/product_assortment_security.xml
  product_assortment/static/description/icon.png
  product_assortment/static/description/index.html
  product_assortment/tests/__init__.py
  product_assortment/tests/test_product_assortment.py
  product_assortment/views/product_assortment.xml
  product_assortment/views/res_partner_view.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1561 [ADD] product_pricelist_margin
  product_pricelist_margin/README.rst
  product_pricelist_margin/__init__.py
  product_pricelist_margin/__manifest__.py
  product_pricelist_margin/i18n/fr.pot
  product_pricelist_margin/i18n/product_pricelist_margins.pot
  product_pricelist_margin/models/__init__.py
  product_pricelist_margin/models/product_pricelist_item.py
  product_pricelist_margin/readme/CONTRIBUTORS.rst
  product_pricelist_margin/readme/DESCRIPTION.rst
  product_pricelist_margin/readme/USAGE.rst
  product_pricelist_margin/static/description/icon.png
  product_pricelist_margin/static/description/index.html
  product_pricelist_margin/static/description/pricelist_item.png
  product_pricelist_margin/tests/__init__.py
  product_pricelist_margin/tests/test_margin.py
  product_pricelist_margin/views/product_pricelist_item_views.xml
  product_pricelist_margin/views/product_pricelist_views.xml
  setup/product_pricelist_margin/odoo/addons/product_pricelist_margin
  setup/product_pricelist_margin/setup.py
Labels: bot is merging ⏳, stale

#1974 [18.0][IMP] product_pricelist_supplierinfo: Add ignore_supplierinfo_margin option…
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
Labels: approved, bot is merging ⏳

#1975 [17.0][IMP] product_pricelist_supplierinfo: Add ignore_supplierinfo_margin option…
  product_pricelist_supplierinfo/__manifest__.py
  product_pricelist_supplierinfo/i18n/product_pricelist_supplierinfo.pot
  product_pricelist_supplierinfo/models/product_pricelist_item.py
  product_pricelist_supplierinfo/models/product_supplierinfo.py
  product_pricelist_supplierinfo/models/product_template.py
  product_pricelist_supplierinfo/tests/test_product_supplierinfo.py
  product_pricelist_supplierinfo/views/product_pricelist_item_views.xml
Labels: approved, bot is merging ⏳

#1981 [18.0] product_set: fix archive line + improve UI
  product_set/models/product_set.py
  product_set/models/product_set_line.py
  product_set/tests/test_product_set.py
  product_set/views/product_set.xml
  product_set/views/product_set_line.xml
Labels: bug, approved, bot is merging ⏳

#1979 [18.0][ADD] product_category_name_translatable
  product_category_name_translatable/README.rst
  product_category_name_translatable/__init__.py
  product_category_name_translatable/__manifest__.py
  product_category_name_translatable/models/__init__.py
  product_category_name_translatable/models/product_category.py
  product_category_name_translatable/pyproject.toml
  product_category_name_translatable/readme/CONTRIBUTORS.md
  product_category_name_translatable/readme/DESCRIPTION.md
  product_category_name_translatable/static/description/icon.png
  product_category_name_translatable/static/description/index.html
  product_category_name_translatable/tests/__init__.py
  product_category_name_translatable/tests/test_product_category_name_translatable.py
Labels: approved, bot is merging ⏳

#1900 [18.0][MIG] sale_product_template_tags: Migration to 18.0
  sale_product_template_tags/README.rst
  sale_product_template_tags/__init__.py
  sale_product_template_tags/__manifest__.py
  sale_product_template_tags/i18n/ca.po
  sale_product_template_tags/i18n/it.po
  sale_product_template_tags/i18n/pt.po
  sale_product_template_tags/i18n/pt_BR.po
  sale_product_template_tags/i18n/sale_product_template_tags.pot
  sale_product_template_tags/pyproject.toml
  sale_product_template_tags/readme/CONTRIBUTORS.md
  sale_product_template_tags/readme/DESCRIPTION.md
  sale_product_template_tags/static/description/icon.png
  sale_product_template_tags/static/description/index.html
  sale_product_template_tags/views/product_template_tag.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1984 [17.0][MIG] uom_alias: Migration to 17.0
  uom_alias/README.rst
  uom_alias/__init__.py
  uom_alias/__manifest__.py
  uom_alias/i18n/it.po
  uom_alias/i18n/uom_alias.pot
  uom_alias/models/__init__.py
  uom_alias/models/uom_alias.py
  uom_alias/models/uom_uom.py
  uom_alias/pyproject.toml
  uom_alias/readme/CONFIGURE.md
  uom_alias/readme/CONTRIBUTORS.md
  uom_alias/readme/DESCRIPTION.md
  uom_alias/readme/ROADMAP.md
  uom_alias/readme/USAGE.md
  uom_alias/security/ir.model.access.csv
  uom_alias/static/description/icon.png
  uom_alias/static/description/index.html
  uom_alias/static/img/screenshot-1.png
  uom_alias/tests/__init__.py
  uom_alias/tests/test_uom_alias.py
  uom_alias/views/uom_category.xml
  uom_alias/views/uom_uom.xml
Labels: approved, bot is merging ⏳

#1476 [ADD] product_pricelist_item_uom
  product_pricelist_item_uom/README.rst
  product_pricelist_item_uom/__init__.py
  product_pricelist_item_uom/__manifest__.py
  product_pricelist_item_uom/i18n/it.po
  product_pricelist_item_uom/models/__init__.py
  product_pricelist_item_uom/models/product_pricelist_item.py
  product_pricelist_item_uom/readme/CONFIGURE.rst
  product_pricelist_item_uom/readme/CONTRIBUTORS.rst
  product_pricelist_item_uom/readme/DESCRIPTION.rst
  product_pricelist_item_uom/readme/USAGE.rst
  product_pricelist_item_uom/static/description/index.html
  product_pricelist_item_uom/tests/__init__.py
  product_pricelist_item_uom/tests/test_product_pricelist_item.py
  product_pricelist_item_uom/views/product_pricelist_item_views.xml
  product_pricelist_item_uom/views/product_pricelist_views.xml
  setup/product_pricelist_item_uom/odoo/addons/product_pricelist_item_uom
  setup/product_pricelist_item_uom/setup.py
Labels: approved, bot is merging ⏳

#1988 [18.0] product_packaging_level_salable: drop useless code
  product_packaging_level_salable/models/sale_order_line.py
  product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
Labels: approved, bot is merging ⏳
