Repository OCA/product-attribute, pull requests merged in 2025-04, with the labels that each got.

#1871 [IMP] product_stock_state: Add on demand state
  product_stock_state/i18n/fr.po
  product_stock_state/i18n/product_stock_state.pot
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_template_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1946 [16.0][IMP] product_pricelist_direct_print: Rounding by Product Price
  product_pricelist_direct_print/wizards/product_pricelist_print.py
Labels: bot is merging ⏳

#1950 [18.0][imp] product_get_price_helper: allow to pass price_unit
  product_get_price_helper/models/product_product.py
Labels: approved, bot is merging ⏳

#1933 [18.0][MIG] stock_packaging_calculator_packaging_level: Migration to 18.0 (=> product_packaging_calculator_packaging_level)
  product_packaging_calculator_packaging_level/README.rst
  product_packaging_calculator_packaging_level/__init__.py
  product_packaging_calculator_packaging_level/__manifest__.py
  product_packaging_calculator_packaging_level/i18n/it.po
  product_packaging_calculator_packaging_level/i18n/stock_packaging_calculator_packaging_level.pot
  product_packaging_calculator_packaging_level/i18n/stock_packaging_calculator_packaging_type.pot
  product_packaging_calculator_packaging_level/models/__init__.py
  product_packaging_calculator_packaging_level/models/product.py
  product_packaging_calculator_packaging_level/models/product_qty_by_packaging_mixin.py
  product_packaging_calculator_packaging_level/pyproject.toml
  product_packaging_calculator_packaging_level/readme/CONTRIBUTORS.md
  product_packaging_calculator_packaging_level/readme/CREDITS.md
  product_packaging_calculator_packaging_level/readme/DESCRIPTION.md
  product_packaging_calculator_packaging_level/static/description/icon.png
  product_packaging_calculator_packaging_level/static/description/index.html
  product_packaging_calculator_packaging_level/tests/__init__.py
  product_packaging_calculator_packaging_level/tests/test_packaging_by_qty.py
Labels: needs review, approved, migration, bot is merging ⏳

#1948 [16.0][ADD] product_supplierinfo_standard_price
  product_supplierinfo_standard_price/README.rst
  product_supplierinfo_standard_price/__init__.py
  product_supplierinfo_standard_price/__manifest__.py
  product_supplierinfo_standard_price/i18n/fr.po
  product_supplierinfo_standard_price/models/__init__.py
  product_supplierinfo_standard_price/models/product_supplierinfo.py
  product_supplierinfo_standard_price/readme/CONTRIBUTORS.rst
  product_supplierinfo_standard_price/readme/DESCRIPTION.rst
  product_supplierinfo_standard_price/static/description/changing_standardprice_from_supplierinfo.jpeg
  product_supplierinfo_standard_price/static/description/index.html
  product_supplierinfo_standard_price/static/src/scss/product_supplierinfo_standard_price.scss
  product_supplierinfo_standard_price/tests/__init__.py
  product_supplierinfo_standard_price/tests/test_standard_price.py
  product_supplierinfo_standard_price/views/view_product_supplierinfo.xml
  setup/product_supplierinfo_standard_price/odoo/addons/product_supplierinfo_standard_price
  setup/product_supplierinfo_standard_price/setup.py
Labels: approved, bot is merging ⏳

#1940 [16.0][NEW] uom_alias
  setup/uom_alias/odoo/addons/uom_alias
  setup/uom_alias/setup.py
  uom_alias/README.rst
  uom_alias/__init__.py
  uom_alias/__manifest__.py
  uom_alias/i18n/uom_alias.pot
  uom_alias/models/__init__.py
  uom_alias/models/uom_alias.py
  uom_alias/models/uom_uom.py
  uom_alias/readme/CONFIGURE.rst
  uom_alias/readme/CONTRIBUTORS.rst
  uom_alias/readme/DESCRIPTION.rst
  uom_alias/readme/ROADMAP.rst
  uom_alias/readme/USAGE.rst
  uom_alias/security/ir.model.access.csv
  uom_alias/static/description/icon.png
  uom_alias/static/description/index.html
  uom_alias/static/img/screenshot-1.png
  uom_alias/tests/__init__.py
  uom_alias/tests/test_uom_alias.py
  uom_alias/views/uom_category.xml
  uom_alias/views/uom_uom.xml
Labels: approved, ready to merge, bot is merging ⏳

#1954 [16.0][IMP] product_get_price_helper: improve performance
  product_get_price_helper/models/product_product.py
  product_get_price_helper/tests/test_product.py
Labels: approved, ready to merge, bot is merging ⏳

#1717 [16.0][ADD] product_catalog: new module
  product_catalog/README.rst
  product_catalog/__init__.py
  product_catalog/__manifest__.py
  product_catalog/controllers/__init__.py
  product_catalog/controllers/catalog.py
  product_catalog/models/__init__.py
  product_catalog/models/product_catalog_mixin.py
  product_catalog/readme/CONTEXT.md
  product_catalog/readme/CONTRIBUTORS.md
  product_catalog/readme/DESCRIPTION.md
  product_catalog/readme/ROADMAP.md
  product_catalog/readme/USAGE.md
  product_catalog/static/description/index.html
  product_catalog/static/src/product_catalog/kanban_controller.esm.js
  product_catalog/static/src/product_catalog/kanban_model.esm.js
  product_catalog/static/src/product_catalog/kanban_record.esm.js
  product_catalog/static/src/product_catalog/kanban_record.xml
  product_catalog/static/src/product_catalog/kanban_renderer.esm.js
  product_catalog/static/src/product_catalog/kanban_renderer.xml
  product_catalog/static/src/product_catalog/kanban_view.esm.js
  product_catalog/static/src/product_catalog/kanban_view_buttons.xml
  product_catalog/static/src/product_catalog/order_line/order_line.esm.js
  product_catalog/static/src/product_catalog/order_line/order_line.scss
  product_catalog/static/src/product_catalog/order_line/order_line.xml
  product_catalog/static/src/product_catalog/search/search_panel.esm.js
  product_catalog/static/src/product_catalog/search/search_panel.xml
  product_catalog/views/product_views.xml
  setup/product_catalog/odoo/addons/product_catalog
  setup/product_catalog/setup.py
Labels: approved, bot is merging ⏳, stale

#1719 [16.0][ADD] product_catalog_stock: New module
  product_catalog_stock/README.rst
  product_catalog_stock/__init__.py
  product_catalog_stock/__manifest__.py
  product_catalog_stock/models/__init__.py
  product_catalog_stock/models/stock_picking.py
  product_catalog_stock/models/stock_picking_type.py
  product_catalog_stock/readme/CONTRIBUTORS.md
  product_catalog_stock/readme/DESCRIPTION.md
  product_catalog_stock/readme/ROADMAP.md
  product_catalog_stock/readme/USAGE.md
  product_catalog_stock/static/description/index.html
  product_catalog_stock/views/stock_picking_type_views.xml
  product_catalog_stock/views/stock_picking_views.xml
  setup/product_catalog_stock/odoo/addons/product_catalog_stock
  setup/product_catalog_stock/setup.py
Labels: approved, bot is merging ⏳, stale

#1720 [16.0][ADD] product_catalog_sale: New module
  product_catalog_sale/README.rst
  product_catalog_sale/__init__.py
  product_catalog_sale/__manifest__.py
  product_catalog_sale/models/__init__.py
  product_catalog_sale/models/sale_order.py
  product_catalog_sale/readme/CONTRIBUTORS.md
  product_catalog_sale/readme/DESCRIPTION.md
  product_catalog_sale/readme/ROADMAP.md
  product_catalog_sale/readme/USAGE.md
  product_catalog_sale/static/description/index.html
  product_catalog_sale/views/sale_order_views.xml
  setup/product_catalog_sale/odoo/addons/product_catalog_sale
  setup/product_catalog_sale/setup.py
Labels: approved, bot is merging ⏳
