Repository OCA/product-attribute, pull requests merged in 2025-07, with the labels that each got.

#2004 [18.0][MIG] product_lot_sequence: Migration to 18.0
  product_lot_sequence/README.rst
  product_lot_sequence/__init__.py
  product_lot_sequence/__manifest__.py
  product_lot_sequence/data/ir_config_parameter.xml
  product_lot_sequence/i18n/ca.po
  product_lot_sequence/i18n/es.po
  product_lot_sequence/i18n/fr.po
  product_lot_sequence/i18n/it.po
  product_lot_sequence/i18n/nl.po
  product_lot_sequence/i18n/nl_NL.po
  product_lot_sequence/i18n/product_lot_sequence.pot
  product_lot_sequence/models/__init__.py
  product_lot_sequence/models/product.py
  product_lot_sequence/models/res_company.py
  product_lot_sequence/models/res_config_settings.py
  product_lot_sequence/models/stock_lot.py
  product_lot_sequence/models/stock_move.py
  product_lot_sequence/pyproject.toml
  product_lot_sequence/readme/CONFIGURE.md
  product_lot_sequence/readme/CONTRIBUTORS.md
  product_lot_sequence/readme/CREDITS.md
  product_lot_sequence/readme/DESCRIPTION.md
  product_lot_sequence/readme/ROADMAP.md
  product_lot_sequence/readme/USAGE.md
  product_lot_sequence/static/description/icon.png
  product_lot_sequence/static/description/index.html
  product_lot_sequence/tests/__init__.py
  product_lot_sequence/tests/test_product_lot_sequence.py
  product_lot_sequence/views/product_views.xml
  product_lot_sequence/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2014 [18.0][MIG] product_list_price_from_pricelist: Migration to version 18.0
  product_list_price_from_pricelist/README.rst
  product_list_price_from_pricelist/__init__.py
  product_list_price_from_pricelist/__manifest__.py
  product_list_price_from_pricelist/data/cron.xml
  product_list_price_from_pricelist/i18n/es.po
  product_list_price_from_pricelist/i18n/it.po
  product_list_price_from_pricelist/i18n/product_list_price_from_pricelist.pot
  product_list_price_from_pricelist/models/__init__.py
  product_list_price_from_pricelist/models/product_pricelist.py
  product_list_price_from_pricelist/models/res_company.py
  product_list_price_from_pricelist/models/res_config_settings.py
  product_list_price_from_pricelist/pyproject.toml
  product_list_price_from_pricelist/readme/CONFIGURE.md
  product_list_price_from_pricelist/readme/CONTRIBUTORS.md
  product_list_price_from_pricelist/readme/DESCRIPTION.md
  product_list_price_from_pricelist/readme/ROADMAP.md
  product_list_price_from_pricelist/readme/USAGE.md
  product_list_price_from_pricelist/static/description/icon.png
  product_list_price_from_pricelist/static/description/index.html
  product_list_price_from_pricelist/tests/__init__.py
  product_list_price_from_pricelist/tests/test_pricelist.py
  product_list_price_from_pricelist/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#2010 [15.0][IMP] product_secondary_unit: Add helper methods to compute quantities
  product_secondary_unit/models/product_secondary_unit_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#2012 [18.0][MIG] product product template link: go to template from variant
  product_product_template_link/README.rst
  product_product_template_link/__init__.py
  product_product_template_link/__manifest__.py
  product_product_template_link/i18n/ca.po
  product_product_template_link/i18n/es.po
  product_product_template_link/i18n/it.po
  product_product_template_link/i18n/product_product_template_link.pot
  product_product_template_link/i18n/product_product_template_navigation.pot
  product_product_template_link/models/__init__.py
  product_product_template_link/models/product_product.py
  product_product_template_link/pyproject.toml
  product_product_template_link/readme/CONTRIBUTORS.md
  product_product_template_link/readme/DESCRIPTION.md
  product_product_template_link/static/description/icon.png
  product_product_template_link/static/description/index.html
  product_product_template_link/static/img/template_navigation.gif
  product_product_template_link/tests/__init__.py
  product_product_template_link/tests/test_product_product_template_link.py
  product_product_template_link/views/product_product_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2020 [18.0][MIG] product_supplierinfo_import_by_barcode > product_supplierinfo_import: Migration to 18.0
  product_supplierinfo_import/README.rst
  product_supplierinfo_import/__init__.py
  product_supplierinfo_import/__manifest__.py
  product_supplierinfo_import/i18n/es.po
  product_supplierinfo_import/i18n/it.po
  product_supplierinfo_import/i18n/product_supplierinfo_import.pot
  product_supplierinfo_import/models/__init__.py
  product_supplierinfo_import/models/product_supplier_info.py
  product_supplierinfo_import/models/product_supplierinfo_import_template.py
  product_supplierinfo_import/models/product_template.py
  product_supplierinfo_import/pyproject.toml
  product_supplierinfo_import/readme/CONFIGURE.md
  product_supplierinfo_import/readme/CONTRIBUTORS.md
  product_supplierinfo_import/readme/DESCRIPTION.md
  product_supplierinfo_import/readme/USAGE.md
  product_supplierinfo_import/security/ir.model.access.csv
  product_supplierinfo_import/static/description/icon.png
  product_supplierinfo_import/static/description/index.html
  product_supplierinfo_import/tests/__init__.py
  product_supplierinfo_import/tests/data/test_supplier_drinks_complex_sheet.xlsx
  product_supplierinfo_import/tests/data/test_supplier_drinks_complex_sheet_updated.xlsx
  product_supplierinfo_import/tests/data/test_supplier_spanish_drinks.xlsx
  product_supplierinfo_import/tests/test_product_supplierinfo_import.py
  product_supplierinfo_import/views/product_supplierinfo_import_template_views.xml
  product_supplierinfo_import/wizards/__init__.py
  product_supplierinfo_import/wizards/product_supplierinfo_import.py
  product_supplierinfo_import/wizards/product_supplierinfo_import_views.xml
Labels: approved, bot is merging ⏳

#2021 [18.0][MIG] product_supplierinfo_import_by_barcode_margin > product_supplierinfo_import_margin: Migration to 18.0
  product_supplierinfo_import_margin/README.rst
  product_supplierinfo_import_margin/__init__.py
  product_supplierinfo_import_margin/__manifest__.py
  product_supplierinfo_import_margin/i18n/it.po
  product_supplierinfo_import_margin/i18n/product_supplierinfo_import_margin.pot
  product_supplierinfo_import_margin/pyproject.toml
  product_supplierinfo_import_margin/readme/CONTRIBUTORS.md
  product_supplierinfo_import_margin/readme/DESCRIPTION.md
  product_supplierinfo_import_margin/readme/USAGE.md
  product_supplierinfo_import_margin/static/description/icon.png
  product_supplierinfo_import_margin/static/description/index.html
  product_supplierinfo_import_margin/wizards/__init__.py
  product_supplierinfo_import_margin/wizards/product_supplierinfo_import.py
  product_supplierinfo_import_margin/wizards/product_supplierinfo_import_views.xml
Labels: approved, bot is merging ⏳

#1997 [18.0][MIG] product_category_product_link: Migration to 18.0
  product_category_product_link/README.rst
  product_category_product_link/__init__.py
  product_category_product_link/__manifest__.py
  product_category_product_link/i18n/ca.po
  product_category_product_link/i18n/it.po
  product_category_product_link/i18n/product_category_product_link.pot
  product_category_product_link/models/__init__.py
  product_category_product_link/models/product_category.py
  product_category_product_link/models/product_template.py
  product_category_product_link/pyproject.toml
  product_category_product_link/readme/CONTRIBUTORS.md
  product_category_product_link/readme/DESCRIPTION.md
  product_category_product_link/static/description/icon.png
  product_category_product_link/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1815 [17.0][MIG] product_company_default: Migration to 17.0
  product_company_default/README.rst
  product_company_default/__init__.py
  product_company_default/__manifest__.py
  product_company_default/data/ir_config_parameter.xml
  product_company_default/i18n/it.po
  product_company_default/i18n/product_company_default.pot
  product_company_default/models/__init__.py
  product_company_default/models/product_template.py
  product_company_default/pyproject.toml
  product_company_default/readme/CONTRIBUTORS.md
  product_company_default/readme/DESCRIPTION.md
  product_company_default/static/description/icon.png
  product_company_default/static/description/index.html
  product_company_default/tests/__init__.py
  product_company_default/tests/test_product_company_default.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, stale
